### ISSUE TITLE
Obs package: Needs vaapi deps

### ISSUE THREAD

**Issue by Itamiko** [void-linux/void-packages#10762]
Obs needs 
```
libva-vdpau-driver libvdpau-va-gl libva-intel-driver(for intel only)
```
for ffmpeg-vaapi to be used without errors

**Comment by Itamiko** [comment]
can add to optional deps  or something like that but the above will be needed if someone is gonna use ffmpeg-vaapi output

**Comment by Hoshpak** [comment]
Since there's no concept of optional dependencies in xbps and adding all packages as hard dependencies would be inappropriate. this will be left for the user to decide. An install message could be added to the package to advise users to install the apropriate package for their system in case they want to use that feature.
