### ISSUE TITLE
Package request: aws-cli

### ISSUE THREAD

**Issue by leahneukirchen** [void-linux/void-packages#11435]
https://github.com/aws/aws-cli (Python based, Apache-2.0 licensed)

**Comment by bobertlo** [comment]
I don't have my work anymore, but after packaging tracing a lot of dependencies, and packaging a few of them there was a versioning conflict that wasn't immediately apparent, needed testing to find.

It needs an older version of a python library than we offer. I just installed it with pip and since lost my work. Just wanted to warn whoever tries this.

**Comment by bobertlo** [comment]
Is anyone working on this already? I guess I might as well do it again since I was pretty close. I think one version of python worked with our libraries and the other did not.

**Comment by Anachron** [comment]
The `requirements` actually look quite sane: https://github.com/aws/aws-cli/blob/develop/requirements.txt

(Not working on it)
