### ISSUE TITLE
Tmux update broke stuff // Ways how to handle breaking changes?

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#11606]
With the commit https://github.com/void-linux/void-packages/commit/b7379f6eee1f0d9ba3713720c1b4b68ded4853e7 [a lot of stuff](https://github.com/tmux/tmux/issues/1689) broke on Tmux.

Maybe we can think about how to handle breaking changes? Should we probably find a way to mark a package update as breaking and then let `xbps` tell the user which packages are "breaking" so he is aware of it and can read about it?

**Comment by the-maldridge** [comment]
We have a way to handle breaking changes already.  We strongly encourage our user base to take their problems to upstream so that upstream will stop making breaking changes without following appropriate steps.

If you're curious how certain things like SQL servers get upgraded, well the answer is meta-package magic.
