### ISSUE TITLE
[URGENT] Please update all kernel packages: MBS / Zombieload Vulnerabilities

### ISSUE THREAD

**Issue by ackalker** [void-linux/void-packages#11734]
Systems with Intel processors urgently need kernel updates to try and mitigate the recently disclosed MBS / Zombieload vulnerabilities.

More information [here](https://www.phoronix.com/scan.php?page=news_item&px=MDS-Kernel-Fixes) and [here](https://www.phoronix.com/scan.php?page=news_item&px=Microarch-Data-Sampling).

**Comment by ackalker** [comment]
CVE-2018-12126 Microarchitectural Store Buffer Data Sampling (MSBDS) 
CVE-2018-12130 Microarchitectural Fill Buffer Data Sampling (MFBDS) 
CVE-2018-12127 Microarchitectural Load Port Data Sampling (MLPDS) 
CVE-2019-11091 Microarchitectural Data Sampling Uncacheable Memory (MDSUM)

**Comment by Hoshpak** [comment]
Kernel updates have been pushed with commits 2988b1ae37b53e0e0a2899053241c8b9d37d3981 - 66a502359bda540b937211d54246d2b17ce16f7b . The Intel microcode filles have been update to the current version with 648290e93d51bda548af0c1209e787cbf0f1a8fb . The updated packages will appear in the repository later today since each kernel build takes a few hours.
