### ISSUE TITLE
Process on renaming packages

### ISSUE THREAD

**Issue by Gigahawk** [void-linux/void-packages#11816]
Recently [Slic3rPE](https://github.com/void-linux/void-packages/tree/master/srcpkgs/Slic3rPE) has been renamed to [PrusaSlicer](https://github.com/prusa3d/PrusaSlicer/releases).

As far as I can tell, the documentation doesn't describe what should be done when package names change.
The closest thing I can find is what to do for removing a package.
Should I just remove Slic3rPE and submit a new package called PrusaSlicer?

**Comment by Hoshpak** [comment]
There isn't really a clean way to rename packages. The one that seems to work best so far is: Rename the template and the package, make the original package a sub-meta-package of the new package that depends on the new name. That way people already having the package installed will have the package replaced by the meta-package with the next update and at the same time will get the package with the new name installed. It is important not to add a replaces to the new package name since that will lead to the removal of the meta-package which in turn would lead to xbps to consider the new package subject to removal by `xbps-remove -o` since it wasn't installed manually and no package depends on it. So the meta-package is needed to keep the package with the new name installed.

**Comment by CameronNemo** [comment]
Defer renaming the package, but do update the short description to list the new name.
