### ISSUE TITLE
Question about changing shared library with many dependencies in Mate

### ISSUE THREAD

**Issue by thomas-t-w** [void-linux/void-packages#12165]
I am wanting to finish updating Mate, however, many things depend on Mate Menus. There was a library change and so old items won't work if we rebuild Mate-menus. Some of the older items from mate 1.20 also won't build against the new mate-menus so everything needs to be updated together. HOw do I coordinate this with you all so that things don't break? Its a lot of packages some of which are mate-penel, mate-control-center, mate-screensaver, mate-applets, mate-media, mozo etc. Also, I am not sure if the shared library in shlibs needs to be bumped in this case. Thanks for suggestions on this.

**Comment by xtraeme** [comment]
Hi, I'm the creator of xbps, void, etc. Been watching you,and it's OK but you need first the shared libraries and then all pkgs.
Cheers

**Comment by thomas-t-w** [comment]
Thanks so much for all your help so far. That is what I was planning. HOw do I prevent though mate-menus from building before all the things that depend on it are pushed? If mate mate-menus is pushed to the repos these things that depend on it that are already in the repo will break such as mate-panel and mozo. Also, the current versions won't build against the new mate-menus if that is pushed first.

**Comment by jnbr** [comment]
Usually, if the abi of a chared library gets changed, the soname version gets changed as well.
These sonames are tracked in the file `common/shlibs` and each xbps package has information which version of a shared library it needs.
With this information, xbps prevents updates which would break because some package uses some shared library that isn't provided any more.

The easiest way is to have the updates which are necessary for the mate-menus update in the same  request. The build server will figure out the correct order.

**Comment by thomas-t-w** [comment]
Closing this because its now packaged and pushed. Thanks everyone for your help with this and everything else re: suggestions and teaching as I learn how things work around here.
