### ISSUE TITLE
linux: missing bfq i/o scheduler

### ISSUE THREAD

**Issue by huglovefan** [void-linux/void-packages#12530]
### System

* xuname: `Void 5.1.11_1 x86_64-musl AuthenticAMD uptodate rFF`
* package: `linux4.14` and newer (only tested `5.1` but `bfq` was added in `4.12`)

### Expected behavior

`bfq` should be listed and selectable in `/sys/class/block/*/queue/scheduler`

### Actual behavior

it's not built into the kernel because the configuration option is unset

```
% cat /sys/class/block/sd[ab]/queue/scheduler
[mq-deadline] kyber none
[mq-deadline] kyber none
% zcat /proc/config.gz | grep BFQ
# CONFIG_IOSCHED_BFQ is not set
```

the default is `mq-deadline` but `bfq` is supposedly [better](https://algo.ing.unimo.it/people/paolo/disk_sched/results.php) for responsiveness under load

### Steps to reproduce the behavior

1. boot into `linux5.1`
2. look in `/sys/class/block/*/queue/scheduler`

**Comment by Hoshpak** [comment]
The scheduler is now enabled in the kernel configuration for all relevant kernel versions. I did not increase the revision of the package because the builders have been busy all day building kernels because of the SACK security vulnerability and I don't think we can afford another rebuild right now. So the change will only be effective in binary packages once the next version is released and the packages are rebuilt.
