### ISSUE TITLE
wxWidgets-gtk3: wx-config-gtk3 is not a consistent symlink across arch

### ISSUE THREAD

**Issue by yopito** [void-linux/void-packages#12807]
### System

* xuname:  `Void 4.19.56_1 x86_64 GenuineIntel notuptodate rFF`
  *output of ``xuname`` (part of xtools)*
* package:  `wxWidgets-gtk3-devel-3.0.4_1`
  *affected package(s) including the version*

### Expected behavior

building and cross-building using `wx-config-gtk3` should be fine, whatever the target architecture is.

### Actual behavior

Cross-building using `wx-config-gtk3` for i686 target arch fails.

### Steps to reproduce the behavior

Crossbuild filezilla for i686 for instance:
```
[...]
checking pkg-config is at least version 0.9.0... yes
checking for libfilezilla >= 0.17.1... yes
checking for wx-config-gtk3... /usr/bin/wx-config-gtk3
checking for wxWidgets version >= 3.0.4 (--unicode=yes --universal=no)... no
configure: error: 
    The requested wxWidgets build couldn't be found.
[...]
```

### Additional infos

`wx-config-gtk3` is a symlink , that is not consistent in packages: sometime absolute, sometime relative.  
So `generic_wrapper` don't wrap it for i686, that make build fails then.

Example on some package(s):

```
$ for i in repocache/wxWidgets-gtk3-devel-3.0.4_1.*.xbps; 
     do echo ; echo "# $i" ; tar tvJf $i | grep wx-config
done

# repocache/wxWidgets-gtk3-devel-3.0.4_1.aarch64-musl.xbps
lrwxrwxrwx 0/0               0 2018-09-10 14:43 ./usr/bin/wx-config-gtk3 -> ../lib/wx/config/gtk3-unicode-3.0

# repocache/wxWidgets-gtk3-devel-3.0.4_1.aarch64.xbps
lrwxrwxrwx 0/0               0 2018-09-10 14:43 ./usr/bin/wx-config-gtk3 -> ../lib/wx/config/gtk3-unicode-3.0

# repocache/wxWidgets-gtk3-devel-3.0.4_1.i686.xbps
lrwxrwxrwx 0/0               0 2018-09-10 14:43 ./usr/bin/wx-config-gtk3 -> /usr/lib32/wx/config/gtk3-unicode-3.0

# repocache/wxWidgets-gtk3-devel-3.0.4_1.x86_64.xbps
lrwxrwxrwx 0/0               0 2018-09-10 14:43 ./usr/bin/wx-config-gtk3 -> /usr/lib/wx/config/gtk3-unicode-3.0
```
Edit: not strictly related to fails build of PR #11854, add output for filezilla/i686

**Comment by Johnnynator** [comment]
The problem is that we only overwrite the symlink when cross compiling: 
https://github.com/void-linux/void-packages/blob/462ee5b0468ef5249d1c7ac4466385ec0117cc16/srcpkgs/wxWidgets-gtk3/template#L54-L68

In regards of your issue, you don't need to cross compile i686 on a x86_64 host, just create a seperate masterdir and compile it in there.`./xbps-src -m masterdir-i686 binary-bootsrap i686` and then compile with `./xbps-src -m masterdir-i686 pkg PACKAGE`

**Comment by newbluemoon** [comment]
I think the underlying problem is that i686 puts stuff under `lib32` which no other target does. So I guess that’s why the links aren’t relative. And the wrapper isn’t created. But even when fixing this manually and running `wx-config-gtk3` from within the `chroot`ed masterdir it lists:
```
./wx-config-gtk3 --prefix=/usr/i686-pc-linux-gnu --cflags
-I/usr/lib32/wx/include/gtk3-unicode-3.0 -I/usr/i686-pc-linux-gnu/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread
```

Why isn’t `--prefix` used for the first include? That’s where filezilla’s `configure` script fails again.

**Comment by yopito** [comment]
Thanks for your inputs. I will give a try to provide a consistent wxWidgets-gtk3 package across all arch to make easier to use it whatever is the host & target combination.

**Comment by ericonr** [comment]
I just did filezilla for i686 from an `x86_64-musl` host. Would that be enough to say this is no longer an issue?

**Comment by yopito** [comment]
yes, a kind of a non-issue ...
