### ISSUE TITLE
MEGAsync error update

### ISSUE THREAD

**Issue by edn9** [void-linux/void-packages#12817]
### System

* xuname: MEGAsync-4.0.2.0_2: broken, unresolvable shlib `libmega.so.30408'
Transaction aborted due to unresolved shlibs.
Void 4.19.56_1 x86_64 GenuineIntel uptodate rrrmFFFFF

* package:  MEGAsync-4.1.1.0_1:

### Expected behavior
Update MEGAsync and the system.
### Actual behavior
When I use:
`./xbps-src pkg MEGAsync`

I get this error:
```
=> ERROR: MEGAsync-4.1.1.0_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target} CC="$CC" CXX="$CXX" LINK="$CXX"' exited with 2
=> ERROR:   in do_build() at common/build-style/qmake.sh:29
```

### Steps to reproduce the behavior

`./xbps-src pkg MEGAsync`

**Comment by Johnnynator** [comment]
Make sure that you local repo is up to date. This error looks like you have an outdated MEGAsdk in your local repo.

**Comment by edn9** [comment]
Looks like http://alpha.de.repo.voidlinux.org is offline or something, so I changed all my repo downloads to https://mirrors.dotsrc.org/voidlinux/ and I finally was able to download and then update my system. But the MEGAsync still not working.

https://i.imgur.com/cMufexg.png

**Comment by Hoshpak** [comment]
What exactly is not working? The screenshot shows no error whatsoever, just xbps-src doing its work.

**Comment by edn9** [comment]
![image](https://i.imgur.com/geZtHtH.png)
First the `alpha.de.repo.voidlinux.org` mirror looks like that is not working here and second the xbps-src keep going forever and then I got that error again. So I changed the mirror for xbps-src(?):
> echo 'XBPS_DISTFILES_MIRROR+="https://mirrors.dotsrc.org/voidlinux/distfiles/"' >> etc/conf
https://wiki.voidlinux.org/Xbps-src#Distfiles_mirror.28s.29

And now its working again, I just dont understand why reposync failed.

**Comment by Hoshpak** [comment]
The alpha.de. mirror was down for some time and manual intervention was necessary to get it back up. Luckily it's back now and it should be stable for the foreseeable future. So that was the first issue. The second is that xbps looks for x86_64 repodata in the `aarch64` and `musl` directories. There isn't any there so it reports the reposync error. You can ignore that since it already found the correct repodata in the `current` directory and will use that.

I'm glad it worked out for you in the end and will close this issue now.
