### ISSUE TITLE
qbittorent-nox is dependent on X

### ISSUE THREAD

**Issue by innerspacepilot** [void-linux/void-packages#12964]
> $ xbps-query -R qbittorrent-nox
architecture: armv7l-musl
build-date: 2019-05-11 18:14 CDT
filename-sha256: 97e174b195dfbc4c86a2c46ff1690b77d92c383c6d6ce9bce5b628264f0bf8b2
filename-size: 4773KB
homepage: http://www.qbittorrent.org/
installed_size: 6367KB
license: GPL-2.0-or-later
maintainer: Jürgen Buchmüller <pullmoll@t-online.de>
pkgver: qbittorrent-nox-4.1.6_1
repository: https://alpha.de.repo.voidlinux.org/current/musl
shlib-requires:
	libz.so.1
	libtorrent-rasterbar.so.9
	libQt5Network.so.5
	libQt5Xml.so.5
	libQt5Core.so.5
	libstdc++.so.6
	libgcc_s.so.1
	libc.so
short_desc: Free software alternative to µtorrent - no X11
source-revisions: qbittorrent:9dc56b9edc

**Comment by Hoshpak** [comment]
A software implemented with qt depends on qt, so where's the issue?

**Comment by innerspacepilot** [comment]
this is a special subpackage (qbittorrent-nox), which represents special build option when no gui is built, only daemon and web interface.

**Comment by Hoshpak** [comment]
Yes, but it's still a qt-based application so I see no reason why it shouldn't depend on qt.

**Comment by pullmoll** [comment]
I think the problem is we have no `qt5-core` or `qt5-libs` package with only the `libQt5Core.so.*` files. Depending on `qt5` through `libQt5Core.so.*` means the whole shebang of dependencies is installed. I guess we could fix that for `qt5-5.13.0` by adding a separate `qt5-core` package and moving the libs into it.

**Comment by innerspacepilot** [comment]
Oh, well...
My misunderstanding.
Yes problem with qt.
I am making a docker image with qbittorent-nox, and it install whole X system

**Comment by innerspacepilot** [comment]
@pullmoll  are there any updates on this issue?

**Comment by pullmoll** [comment]
@innerspacepilot I didn't find time since qt5 was upgraded to 5.13.x to take a look at if or how it would be possible to split out qt5-base from qt5. In any case it would require every package depending on qt5 to be rebuilt which is by no means easy and would hit the builders hard, perhaps harder than they can handle.

**Comment by Piraty** [comment]
+1 for the lib split, as it affects packages like quassel-core as well.

**Comment by Johnnynator** [comment]
@pullmoll I did split the qt5 base part into sub packages https://github.com/void-linux/void-packages/pull/15310/commits/f4948bd9e81fd56fac4522e5611ccfeeb6ba9e60 , qt5 only remains as a empty package to pull them all in, so we don't have to rebuild every qt5 revdep right away.

```
242M   ~/xbps-sandbox/qbittorrent-nox-4.2.0_1-x86_64  <- old qt5
126M    ~/xbps-sandbox/qbittorrent-nox-4.2.0_2-x86_64  <- split qt5
```

**Comment by innerspacepilot** [comment]
Good news! :)
Anything I can help with?

**Comment by ericonr** [comment]
Has been fixed :)
