### ISSUE TITLE
nvidia340 fails to build on linux4.19-4.19.59_1

### ISSUE THREAD

**Issue by patoski** [void-linux/void-packages#13128]
### System

* xuname:  
Void 4.19.59_1 x86_64 GenuineIntel
* package:  
nvidia340-340.107_3

### Expected behavior
When updating system with xbps-install -Syu the nvidia DKMS should build.
 
### Actual behavior
While trying to build the nvidia module comes back with "... FAILED!" System will not reboot into X Windows unless using an old kernel.
### Steps to reproduce the behavior
Try to build nvidia340 module with linux4.19-4.19.59_1 and linux4.19-headers-4.19.59_1

### Notes to fix
Log in as root an run: `export IGNORE_CC_MISMATCH=1`
then run: `xbps-install -Sf linux4.19-*`
The nvidia dkms kernel module will compile successfully.

When trying to build the nvidia module manually in /var/lib/nvidia `make` complains that the current compiler version is different than that used to build the kernel or something like that. The error message advises to set IGNORE_CC_MISMATCH to 1

This issue has been happening for me for a few months or so.

**Comment by Hoshpak** [comment]
This only happens if the kernel is built with another gcc version than is currently installed. There was an issue about it a year ago or so and it was determined that the check put in place by upstream won't be changed. You can either wait after a gcc update until the kernel is rebuilt with the new version (usually 2-3 days, kernel updates happen rather often) or manually override the check.
