### ISSUE TITLE
XFCE PolicyKit Agent Error

### ISSUE THREAD

**Issue by yilmzfurkan** [void-linux/void-packages#13511]
After the polkit update every reboot triggers the "XFCE PolicyKit Agent" error pop-up. Which is kinda annoying. ¯\_(ツ)_/¯

Image: 
![error](https://user-images.githubusercontent.com/17622232/62426315-d9410e80-b6eb-11e9-9379-6cd07acfe8e3.png)

**Comment by jarbowski** [comment]
Hi,
Since it seems that consolekit is obsolete, I did this and everything is okay for me with xfce:

sudo rm -R /var/service/consolekit
sudo rm -R /var/service/cgmanager
sudo xbps-remove -R ConsoleKit2

sudo xbps-install -Su elogind


I don't use a login manager so I removed the "--with-ck-launch" option in my xinitrc
and don't forget this for polkit:
sudo ln -sv /etc/sv/polkitd/ /var/service


Hope it helps

**Comment by yilmzfurkan** [comment]
Thank you @jarbowski, its fixed now.

**Comment by silvernode** [comment]
So the cause was consolekit?
