### ISSUE TITLE
VSCode not changing icon

### ISSUE THREAD

**Issue by marcosroot** [void-linux/void-packages#13722]
Sorry if I'm writing the issue the wrong way.

### Expected behavior
I want to use vscode (code oss) but I want its icon to change according to the selected icon theme

### Actual behavior
I have vscode (code oss) installed, but his icon is horrible, but when I change to any icon theme, the icon remains the same. 

> Regarding Vscode: The .desktop file currently has the icon path hard coded, you can open an Issue at http://github.com/void-linux/void-packages/ to ask if Icon can be set to just `code-oss`.

### Steps to reproduce the behavior
just install code-oss and try change the icon theme

**Comment by yjp20** [comment]
I'm pretty confident I have it fixed in my PR, but I don't have a wm that utilizes icons so I can't (without some annoying effort) do my due diligence with checking the final product. 

Could you manually change your .desktop file to use `code-oss` and see if that works for both with and without the icon-theme? If that test passes through then I think we can go ahead and merge.
