### ISSUE TITLE
Package request: Nextcloud

### ISSUE THREAD

**Issue by LPkkjHD** [void-linux/void-packages#13850]
From [Wikipedia](https://en.wikipedia.org/wiki/Nextcloud):
> Nextcloud is a suite of client-server software for creating and using file hosting services. Nextcloud application functionally is similar to Dropbox. Unlike Dropbox, Nextcloud does not offer off-premises file storage hosting. Nextcloud is free and open-source, which means that anyone is allowed to install and operate it on their own private server devices.

Website: https://nextcloud.com/
Source code: https://github.com/nextcloud/server

**Comment by yopito** [comment]
Your request is about -client (desktop) or -server ?  
I have a WIP package for nextcloud client (without e2e encryption because of LibreSSL)

**Comment by LPkkjHD** [comment]
> Your request is about -client (desktop) or -server ?
Sorry for my late reply. My request is about the server.
I saw an closed thread about nextcloud client and LibreSSL, however, I figured that the owncloud client probably works out too

**Comment by harrisonthorne** [comment]
Whoa. Only two comments since 2019. Any progress on this at all? Seems strange to have the client in the repositories but not the server.

**Comment by paper42** [comment]
I do not think this is a good fit for void repositories.

* updates have to happen by one major version every time
* the user has to click on the update button in the UI before a new update comes otherwise they will have to downgrade, click on the button, update one version, click on the button again, etc.
* users can not click on the update button in the administration settings otherwise they will break the package's consistency and get downgraded with the next xbps nextcloud update
* it would be just a repackaging of 400MB of static files, there is nothing to build, so people can as well just extract the tarball to the right location by themselves

If you want to use nextcloud, either use docker or their installer script that also properly handles updates through multiple major versions.
