### ISSUE TITLE
Conflicting udev rules shipped for KVM

### ISSUE THREAD

**Issue by thomas-t-w** [void-linux/void-packages#14440]
eudev ships 50-default.rules which contains
KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"
base-files shipps 66-kvm.rules which contains
KERNEL=="kvm", GROUP="kvm", MODE="0660"

If I had to make a decision, I would vote for 0660 and require users to add themselves to the kvm group but that is only because I am not qualified to speak about the security implications of letting everyone access the kvm module. We could always print an install message for qemu telling users they had to add themselves to the kvm group. I would like to let someone who knows more about this make the final decision though.

**Comment by Hoshpak** [comment]
I'm not sure if that is an issue at all. The rule from base-files has a higher number so it is evaluated after the udev default rule and overrides it. I just checked on my system and the permissions are indeed set to 0660. The static_node options is required on some systems according to the comment in the code and udev doesn't see it as a conflict and just overrides the earlier permissions.

**Comment by thomas-t-w** [comment]
I initially thought that as well actually but it is very strange for me. When I first reboot my system, my permissions on /dev/kvm start out as 0666. After the first time that I run qemu, they change to 0660. If I remove one of the rules, they stay at the permissions that the other rule set even if I run Qemu multiple times. Can you see what your rule is right after reboot? Maybe eudev is getting stuck for some reason on my system and this is uncommon in which case we could just close this.

**Comment by Hoshpak** [comment]
Indeed, I tried on my second Void installation and it had /dev/kvm set to 0666 after a system boot. It was probably libvirt on my first installation that touched the device that touched the device and thus lead to udev setting the correct permissions.

I experimented a bit with it and if I comment out the udev default rule, the permissions get applied correctly. If I remove both rules, the default is root:root and 0600. Not really finding an explanation why the second rule seems to be ignored on boot I thought it might be because the first one is more specific and the rules don't match exactly. I'm still not sure if that is the cause but either removing `OPTIONS+="static_node=kvm"` from the first rule oder adding it to the second rule leads to both rules being executed during udev startup and it works as expected.  

While we could just patch the udev default rules, I think it would be better to change the base-files rule so the default one gets properly overridden.

**Comment by thomas-t-w** [comment]
I agree. I will create a pull request for that adding those options to our base files. I did some research and kvm is created as a static node in eudev because the module isn't loaded on some platforms until first use. Best not to patch the rules file in eudev because that could change from time to time in eudev and because we probably want to keep it as a static node.
