### ISSUE TITLE
Package request: ROS

### ISSUE THREAD

**Issue by xue44** [void-linux/void-packages#1460]
I would like to see ROS in void repos. Especially RPi build can benefit from it.
http://www.ros.org/

**Comment by youngjinpark20** [comment]
doesn't seem to bad, I'll take this

**Comment by maxice8** [comment]
ping

**Comment by youngjinpark20** [comment]
oh i've forgotten about this... I'll get back on it soon

**Comment by youngjinpark20** [comment]
Nevermind me saying this "doesn't seem too bad." It's quite bad.

Since ROS has quite a few packages (~500) we need to create a generator based on their existing infrastructure. I have created a preliminary one [here](https://github.com/youngjinpark20/void-ros-melodic), but it still needs a considerable amount of work. If someone better than me could help it'd be great.

**Comment by youngjinpark20** [comment]
Even then, I'm not completely sure if we want to necessarily ship this on our part, since 500 packages would be a significant burden.

**Comment by xue44** [comment]
nvm, docker image is enough
