### ISSUE TITLE
[Package request] Servo

### ISSUE THREAD

**Issue by egormalyutin** [void-linux/void-packages#14629]
https://github.com/servo/servo

Servo is a modern, high-performance browser engine designed for both application and embedded use.

**Comment by ametisf** [comment]
As of now servo won't build on voidlinux because of incompatible LibreSSL versions.

Crate openssl-sys v0.9.35 doesn't build with the following message
> This crate is only compatible with OpenSSL 1.0.1 through 1.1.1, or LibreSSL 2.5
through 2.7, but a different version of OpenSSL was found. The build is now aborting
due to this version mismatch.

Version openssl-sys v0.9.50 builds just fine on void but it breaks servo, so running `cargo update -p openssl-sys` doesn't fix this.

**Comment by the-maldridge** [comment]
FTBFS and doesn't on its own have value without something built around it.
