### ISSUE TITLE
Package request: castero

### ISSUE THREAD

**Issue by hfel** [void-linux/void-packages#14857]
> TUI podcast client for the terminal

https://github.com/xgi/castero

AFAIK, the only other TUI-client currently offered in the Void repos is newsboat, which however lacks the easy functionality of castero, since the user has to 'enqueue' episodes in `newsboat`, then download them in the sub-program `podboat`, which doesn't however reference the name of the podcast or the episode's title, only the name of the enqueued file.

**Comment by Minoru** [comment]
Hi! Newsboat maintainer here. I understand this issue isn't about Podboat, but just to set one thing right...

> podboat, which doesn't however reference the name of the podcast or the episode's title, only the name of the enqueued file.

That's just a default. Since 2.14, it has a [`download-filename-format` setting](https://newsboat.org/releases/2.17/docs/newsboat.html#download-filename-format) which can include both the podcast and episode title, along with some more info.
