### ISSUE TITLE
libevent repository inconsistency

### ISSUE THREAD

**Issue by Hoshpak** [void-linux/void-packages#15745]
The repositories are in an inconsistent state right now because there is a massive rebuild going on which among other includes all major browsers and qt5. While this incosistency lasts, updated might fail with an error message like:

```
[*] Updating `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
MISSING: libevent>=2.1.11_1
Transaction aborted due to unresolved dependencies.
```

The status of the rebuild can be observed at https://build.voidlinux.org/waterfall. Once the status of all build servers is changed to green, everything should work again. In the meantime, please be patient and postpone updating your system until the repositories are in a consistent state again. This issue will be closed when all builds are finished.

**Comment by xtraeme** [comment]
Hi,

Well, this is really weird because I know in what state we are in... And
this is because the builder admin removed some files while xbps was
working... Heh

**Comment by xtraeme** [comment]
Or a stupid shell script fucked out the builders... I know the code. ffs

**Comment by bugcrazy** [comment]
How I solved the problem for me!

First you need to have the xtools-0.56_1 package installed, in order to use the xdowngrade command, you need to download the libevent-2.1.11_1 package, in my case I needed qt5 packages and remove other packages!

Download Link libevent-2.1.11_1

https://alpha.de.repo.voidlinux.org/current/libevent-2.1.11_1.x86_64.xbps

Links from the qt5 packages I needed!

https://alpha.de.repo.voidlinux.org/current/qt5-webengine-5.13.1_2.x86_64.xbps
https://alpha.de.repo.voidlinux.org/current/qt5-declarative-5.13.1_2.x86_64.xbps
https://alpha.de.repo.voidlinux.org/current/qt5-location-5.13.1_2.x86_64.xbps
https://alpha.de.repo.voidlinux.org/current/qt5-webchannel-5.13.1_2.x86_64.xbps
https://alpha.de.repo.voidlinux.org/current/qt5-serialport-5.13.1_2.x86_64.xbps

How downloaded packages copy them to /var/cache/xbps

Open a terminal, and use the command cd /var/cache/xbps

Use the sudo xdowngrade libevent-2.1.11_1.x86_64.xbps command
  
It will look something like this:
index: added `libevent-2.1.11_1 '(x86_64).
index: 1 packages registered.
firefox-69.0.3_1: broken, unresolvable shlib `libevent-2.1.so.6 '

So uninstall all programs like firefox, chromium, transmission, they prevent the update of libevent-2.1.11_1, minus qt5, if my case is the same as part of the graphical interface!

After removing the programs, use the command and the packages you need most sudo xdowngrade libevent-2.1.11_1.x86_64.xbps
  
Now the sudo xbps-install -Su command works

But I was only able to install firefox again, chromium and transmission are unable to install as they depend on the old libevent-2.1.10_2
I need to repackage with the new libevent-2.1.11_1 library

All packages with the old libevent-2.1.10_2 library need to be repackaged if they are going to have conflicts! 

sudo xbps-install -S chromium
[*] Updating `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[*] Updating `https://alpha.de.repo.voidlinux.org/current/nonfree/x86_64-repodata' ...
chromium-77.0.3865.120_1: broken, unresolvable shlib `libevent-2.1.so.6'


sudo xbps-install -S transmission-2.94_3 transmission-qt-2.94_3
[*] Updating `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[*] Updating `https://alpha.de.repo.voidlinux.org/current/nonfree/x86_64-repodata' ...
transmission-2.94_3: broken, unresolvable shlib `libevent-2.1.so.6'
transmission-qt-2.94_3: broken, unresolvable shlib `libevent-2.1.so.6'
Transaction aborted due to unresolved shlibs.

**Comment by Hoshpak** [comment]
x86_64 is has finished the rebuild in the meantime. i686 still has issues which have to be resolved manually.

**Comment by yopito** [comment]
On my side:
* end-user XBPS update is fine with x86_64/glibc for me: `libevent-2.1.11_1` present on my system
* while crossbuild  a package for amrv6l or armv7l that  needs some target packages like qt5 tools (see PR #14069), I've noticed that `qt5` is unavailable in arm* repos, neither  `libevent-2.1.11_1`.
* crossbuild for armv7l: even sqlite package is missing for armv7l

**Comment by yopito** [comment]
armv7l: compared to https://build.voidlinux.org/builders/armv7l_builder/builds/20640/steps/shell_3/logs/stdio (currently running), it seems that qt5 and libevent are available for arm on the builder but unreferenced in the XBPS repo index ?

**Comment by Johnnynator** [comment]
> armv7l: compared to https://build.voidlinux.org/builders/armv7l_builder/builds/20640/steps/shell_3/logs/stdio (currently running), it seems that qt5 and libevent are available for arm on the builder but unreferenced in the XBPS repo index ?

For arm repos refer to #15674

**Comment by Hoshpak** [comment]
I totally forgot to close this, i686 is fine now.
