### ISSUE TITLE
Installation of Kernel Modules

### ISSUE THREAD

**Issue by schmidh** [void-linux/void-packages#15901]
I am trying to create a template file for the [Data Plane Development Kit (DPDK).
](https://www.dpdk.org/) DPDK uses a GNU makefile build system. Compiling the system creates apart from many library files two kernel object files.
```
masterdir/destdir/dpdk-19.08/lib/modules/5.3.7_1/extra/dpdk/rte_kni.ko
masterdir/destdir/dpdk-19.08/lib/modules/5.3.7_1/extra/dpdk/igb_uio.ko
```
I have no idea how I should install these two files:
1. xbps-src does not accept `lib` directories.
2. Even then I wouldn't know how to load these ko files. Are ko files Void Linux compliant? Do I have to create `dkms.config` files?

**Comment by Johnnynator** [comment]
Firstly these are kernel modules not dkms modules, so you just load them with either `insmode(8)` or`modprobe(8)`. But I would recommend to look into getting it packages as a DKMS module, so it is automatically rebuild on a kernel update. Secondly these files you have there should just be in `/usr/lib` instead if `/lib`, there is probably some variable you can set so it installs them  into the correct dir.

**Comment by schmidh** [comment]
Perfect. This is a good guide line. Thanks a lot!

**Comment by Johnnynator** [comment]
At least with their meson build system you can set `-Denable_kmods=off` and just copy `kernel/linux/{igb_uio,kni}` to `/usr/src/${module-name}-${version}` and add a dkms.conf. E.g. the `rtl8822bu-dkms` package demonstrates on how to create a dkms pacakge out of a non dkms kernel module. Also I think you need to make a subpackage per dkms module, it won't work otherwise afaik.

**Comment by schmidh** [comment]
Even better! Awesome. This helps me a lot.
