### ISSUE TITLE
Deprecate iptables in favor of nftables

### ISSUE THREAD

**Issue by Ypnose** [void-linux/void-packages#16195]
Hi there,

Major actors in Linux world like Red Hat or Debian are starting to replace iptables by nftables. Other firewall solutions like Firewalld are also switching to nftables as the default backend.

On Void, we are still using iptables. Would you agree to gradually start the switch ? What is your opinion ?

https://www.redhat.com/en/blog/using-nftables-red-hat-enterprise-linux-8
https://wiki.debian.org/nftables
https://developers.redhat.com/blog/2018/08/10/firewalld-the-future-is-nftables/

Sincerely

**Comment by ailiop-git** [comment]
iptables is still being actively developed both in kernel and userspace, so I don't think we've reached the point of deprecation (especially since nftables is still not a full replacement, and bpfilter is in the horizon as a potential future replacement).

What would a switch entail anyway? iptables is not part of the base system, and void doesn't provide any default ruleset. Currently there is free choice of installing iptables, nftables or even both concurrently (since they're not mutually exclusive) in any void system, and having choice is a good thing!

**Comment by Ypnose** [comment]
By deprecating, I meant thinking about a smooth transition in the upcoming months. I didn't mean to remove iptables from the repo. It would be unrealistic. So, I agree with you.
Anyway, even if iptables is not part of <code>base-system</code> group, it is installed as a dependency of <code>iproute2</code>.

You also mention bpfilter, which is far from being full featured and widly adopted by the community. bpfilter is promising but it is currently at an early stage.

**Comment by ailiop-git** [comment]
All I am saying is that there's really nothing to be done here. We continue providing both iptables and nftables, and they both work fine (even using them together at the same time).

The dependecy of iproute2 to iptables is not a runtime dependency, but rather a build-time dependency which is very specific to iptables and cannot be provided by nftables anway.

So what would this hypothetical transition do concretely in practice and what would be its goal?

**Comment by leahneukirchen** [comment]
Void does not include any firewall by default and provides iptables as well as nft, so just use what you prefer.

**Comment by brutal-force** [comment]
> Void does not include any firewall by default 

@leahneukirchen It seems you're lying, or perhaps you forgot? iptables is installed by default. Read the first sentence here: https://docs.voidlinux.org/config/network/firewalls.html. It seems you should reconsider this question after 5 years instead of assuming everything is fine as it is.

**Comment by zdykstra** [comment]
It's not a good look to accuse a long-standing and deeply respected member of the Void community of lying. An apology would be a good start.

**Comment by brutal-force** [comment]
I see no reason to apologize to people who think they’re smarter than everyone else. Besides, is telling the truth to someone’s face really rude? Since when is pointing out someone’s mistakes considered impolite? You made a mistake, my friend—accept it, live with it, grow from it, and don’t repeat it in the future. Simple, isn’t it?
