### ISSUE TITLE
SDDM very slow to appear

### ISSUE THREAD

**Issue by MirceaMx** [void-linux/void-packages#1698]
### System
![image](https://user-images.githubusercontent.com/40819799/44006988-1f0542fc-9e96-11e8-8f5e-e937cbe9fc69.png)

### Expected behavior
SDDM should start instead...
### Actual behavior
SDDM appears very slowly. I mean Void boots fast then the cursor appears and I wait for SDDM to load so I can input my password. Checked the forums and tried with 'haveged' ' rng-tools' and same behavior. 
 SDDM is very slow, slower than the entire system booting.

**Comment by travankor** [comment]
Are you using consolekit or elogind for session management?

See also: https://github.com/void-linux/void-packages/issues/535

**Comment by travankor** [comment]
Also void's sddm is fairly outdated due to broken consolekit support. 

Can you compare with lightdm maybe?

**Comment by MirceaMx** [comment]
I'm using consolekit. I compared to lxdm which loads instantly. I can see  SDDM is another version judging from the time being set in 24H format instead of the latest being in 12H format but still it's annoying to see it loads so slow.

**Comment by travankor** [comment]
Sddm is the only DM that depends on dbus to start. Dbus starts fairly slowly on non-systemd distros, and especially on Void, where there is no proper service dependency/state management.

**Comment by MirceaMx** [comment]
I tried lightdm (installed lightdm and lightdm gtk3 greeter) and I could see its login but after I typed the password it would not load the desktop. What should I do. Don't know how to change the cursor on lxdm.

**Comment by ruegerjr** [comment]
No other people seem to be reporting this problem since you raised the issue, and I have not experienced it with sddm on my glibc system, so I suspect you have a configuration issue.  If so, it may be better addressed in the Void forum.   I suggest you open a topic on "https://forum.voidlinux.org".  I am not as skilled as many devs here, but if you are using glibc and X11 (not musl or wayland) I will try to help you on the forum. or others may help you there.
