### ISSUE TITLE
Package request: OCRmyPDF

### ISSUE THREAD

**Issue by jcgruenhage** [void-linux/void-packages#17500]
Tool for adding a text layer to scanned PDF files.

Github page: https://github.com/jbarlow83/OCRmyPDF

**Comment by Anachron** [comment]
@ndowens how is the progress?

**Comment by gch1p** [comment]
I'd recommend to install `python3-pipx`, and then `pipx install ocrmypdf`.

But in order to install `ocrmypdf` with `pipx`, you will also need following dependencies: `libheif-devel`, `python3-devel`, `ghostscript`, `libqpdf-devel` and of course `tesseract-ocr` along with language packages you need.

Then just make sure that `$HOME/.local/bin` is in your `$PATH` and use ocrmypdf!
