### ISSUE TITLE
supertux2 doesn't work on musl

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#17687]
### System

* xuname:  
  *Void 5.4.5_1 x86_64-musl GenuineIntel uptodate rrnDFFFFFFF*
* package:  
  *supertux2-0.6.1_1*

### Expected behavior
supertux launches
### Actual behavior
```
$ supertux2
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted
$
```
### Steps to reproduce the behavior
1. install supertux2 on a musl system
2. run `supertux2`

**Comment by st3r4g** [comment]
`LC_ALL=C supertux2` makes it start

**Comment by ericonr** [comment]
This happened because libstdc++'s locale code is cursed, and their generic locale impl doesn't even exist properly, and that's the one used for musl targets.

If you catch the exception it all works fine (other applications like snapper use C++ locales but inside a try-catch block). There's been some light discussion on fixing this in libstdc++, but nothing has moved forward yet.
