### ISSUE TITLE
Package request: go-tools

### ISSUE THREAD

**Issue by PaperMountainStudio** [void-linux/void-packages#17770]
Currently the only package which provides tools like godoc is the `go1.12-bootstrap`. I think void should have a package for these widely used tools.
I know I can get it by using
```
go get golang.org/x/tools/
```
but still, a package would be better.

**Comment by q66** [comment]
@the-maldridge

**Comment by bobertlo** [comment]
Any opinions on this? My initial gut feeling was that these tools are not exactly released with the tool-chain and should be installed independently. I checked and now I see right away is that there are not releases. Every distro offering this package is using git snapshots.

I would be willing to package this if people are okay with that and there is demand, but I could also see this as not acceptable by the standard guidelines of the package repo.

**Comment by the-maldridge** [comment]
Oh somehow this got lost.  I'd rather not package git snapshots, but if you wanted to package it locked off at a corresponding go release that would be acceptable.

**Comment by bobertlo** [comment]
I would personally just install these with `go get golang.org/x/tools/cmd/...`. I thought there might be value in packaging this based on it's inclusion in other major distributions, but upon further inspection they are installing the source into a system-wide gopath as build dependencies for other packages.

Since void-packages handles golang dependencies differently, I do not see a reason to start packaging in this way. As for the tools provided, they seem pretty diverse and perhaps beyond the scope of a single package.

In my opinion: these tools should, idiomatically, be installed by a developer into their GOPATH. I could maybe see packaging godoc but that seems like a different issue.

**Comment by the-maldridge** [comment]
Yeah, this is developer tooling that should be pulled with go get.  Thanks for looking into it.

**Comment by ghost** [comment]
I'd like `goimports` to be available in the repositories.
