### ISSUE TITLE
Mono: Improper symlink for System.Runtime.Serialization.Formatters.Soap.dll

### ISSUE THREAD

**Issue by The-BigDaddy** [void-linux/void-packages#1783]
### System

* xuname:  
  * `Linux void 4.17.14_1 #1 SMP PREEMPT Sat Aug 11 18:42:04 UTC 2018 x86_64 GNU/Linux`
* package:  
  * mono
  * mono-devel

To make this easy, here's [the issue in detail in Mono's Issues](https://github.com/mono/mono/issues/10025)

From what's in that thread so far, it seems like the issue here is with the Mono Void package itself. If any more specific info is needed, let me know.

**Comment by Hoshpak** [comment]
I think this might be a result of an earlier bug in xbps causing it not to include files with long pathnames into the package. The file is created and installed into the destdir but not currently included in the package in the repository. Since this bug has been fixed, a rebuild of the package will be enough to include the file in the package. I will trigger a rebuild as soon as the current situation with gcc and perl on the builders is resolved.

**Comment by Hoshpak** [comment]
The file is now included in the package: 
```$ tar tJf mono-5.10.1.47_3.x86_64.xbps | grep System.Runtime.Serialization.Formatters.Soap.dll
./usr/lib/mono/gac/System.Runtime.Serialization.Formatters.Soap/4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Serialization.Formatters.Soap.dll
./usr/lib/mono/4.7.1-api/System.Runtime.Serialization.Formatters.Soap.dll
./usr/lib/mono/4.7-api/System.Runtime.Serialization.Formatters.Soap.dll
./usr/lib/mono/4.6.2-api/System.Runtime.Serialization.Formatters.Soap.dll
./usr/lib/mono/4.6.1-api/System.Runtime.Serialization.Formatters.Soap.dll
./usr/lib/mono/4.6-api/System.Runtime.Serialization.Formatters.Soap.dll
./usr/lib/mono/4.5.2-api/System.Runtime.Serialization.Formatters.Soap.dll
./usr/lib/mono/4.5.1-api/System.Runtime.Serialization.Formatters.Soap.dll
./usr/lib/mono/4.5-api/System.Runtime.Serialization.Formatters.Soap.dll
./usr/lib/mono/4.5/System.Runtime.Serialization.Formatters.Soap.dll
./usr/lib/mono/4.0-api/System.Runtime.Serialization.Formatters.Soap.dll
./usr/lib/mono/2.0-api/System.Runtime.Serialization.Formatters.Soap.dll
```
