### ISSUE TITLE
Preload 'service' fails to start

### ISSUE THREAD

**Issue by MirceaMx** [void-linux/void-packages#1792]
### System
![image](https://user-images.githubusercontent.com/40819799/44149037-423bf4b4-a0a3-11e8-88d7-594dee8f92dc.png)

* package:  
Preload

### Steps to reproduce the behavior
sv status preload:
'run: preload: (pid 728) 2248s; down: log: 0s, normally up, want up'

**Comment by Hoshpak** [comment]
The service itself runs, it's the attached logger that fails to start. I'm not sure why that happens, it seems that the script depends on socklog-void.

**Comment by loreb** [comment]
The logger fails to chown rsvlog:adm /var/log/preload because there's no rsvlog user, with or without socklog-void.
I have no idea which package installs rsvlog - if anyone can explain how to find out, thank you in advance.

While we are at it, the preload manpage is... ehm... how is it not a build failure?

**Comment by loreb** [comment]
The log service is copy/pasted from https://github.com/rubyists/sv-helper/blob/master/rsvlog.sh;
installing sv-helper worksforme(tm) and should be a dependency unless someone rewrites log/run.

--

$cat $(man -w preload)
help2man is required to generate this file.
