### ISSUE TITLE
xbps-src is missing tar

### ISSUE THREAD

**Issue by ndowens** [void-linux/void-packages#18058]
### System

* xuname:  
Void 5.3.18_1 x86_64 GenuineIntel uptodate rrrmFFFFFFFFFFFFFFFFFFFFFFFF
* package:  
  xbps-src

### Expected behavior
xbps-src to find tar and extract the distfile
### Actual behavior
=> help2man-1.47.12_1: running do-fetch hook: 00-distfiles ...
=> help2man-1.47.12_1: running do-extract hook: 00-distfiles ...
|=> help2man-1.47.12_1: extracting distfile(s), please wait...
/void-packages/common/hooks/do-extract/00-distfiles.sh: line 74: tar: command not found
### Steps to reproduce the behavior
./xbps-src pkg ${pkgname} (any)

**Comment by leahneukirchen** [comment]
works here? d3ef446021

**Comment by ndowens** [comment]
I've made sure that my xbps-src is up2date and tar is atleast installed locally.

**Comment by leahneukirchen** [comment]
zap and binary-bootstrap perhaps.

**Comment by ndowens** [comment]
> zap and binary-bootstrap perhaps.

Will try that and report back or close(if working)

**Comment by ndowens** [comment]
Re-opening, I thought it was working, but went back to same error

**Comment by wkk** [comment]
@ndowens Hi there. Have you solved the problem? Asking because I'm encountering the same problem.
@leahneukirchen I'm setting my `HEAD` at abe6e966a8 (because I want to install virtualbox 6.0) and the problem remains. I also tried `zap` and `binary-bootstrap` and nothing changed. I also changed `tar` to `/bin/tar` in `common/hooks/do-extract/00-distfiles.sh` line 74 and weirdly I get `/bin/tar: command not found`

**Comment by xtraeme** [comment]
right, because your git tree is outdated and there's base-chroot-0.66_1.

Not our fault

**Comment by soppelmann** [comment]
If you run into this problem try entering the chroot and installing tar
`xbps-src chroot`
`xbps-install tar`

**Comment by leahneukirchen** [comment]
The chroot only contains bsdtar.
