### ISSUE TITLE
NetworkManager 1.22.2 no ipv4 address

### ISSUE THREAD

**Issue by codingHahn** [void-linux/void-packages#18434]
### System

* xuname:  
  `Void 5.4.13_2 x86_64 GenuineIntel notuptodate rrrmDFFFFFFFFFFFFFFFF`
* package:  
  *NetworkManager-1.22.2_1*

### Expected behavior
When connecting to a Wifi AP, automatically fetch ipv4 with dhcp
### Actual behavior
No ipv4 address on wifi interface
### Steps to reproduce the behavior
Install the latest version. 

The same problem happened at 36c3, as mentioned here https://github.com/void-linux/void-packages/pull/13560#issuecomment-569531959 . I currently do not have time to test this further. Downgrading to 1.18 for now.

**Comment by steinex** [comment]
Probably not very helpful, but: works for me.

**Comment by yopito** [comment]
On my side: suddenly unable to reconnect to wifi network, even after a cold stop.  

Fixed this by using device "wlp2s0 (xx:xx:xx:xx:xx:xx)" instead of "wlp2s0" (without MAC address) in NetworkManager connection. Connection instantly works then.

**Comment by yopito** [comment]
Still happens, same than issue's comportment: no ipv4 address from DHCP on renew, only ipv6.  
One workaround is destroying the connection (definition) then recreate it.

upstream : issue https://gitlab.freedesktop.org/NetworkManager/NetworkManager/issues/324 : closed.  
Supposed to be fixed in commit https://gitlab.freedesktop.org/NetworkManager/NetworkManager/commit/cafaa63ec61a0f4214a7036afbf4cda5857a83ea (25th of January on branch nm-1.22)

**Comment by yopito** [comment]
FYI: Upstream released 1.22.6

**Comment by yopito** [comment]
1.22.6 is available in Void's repo. Works fine for me.

**Comment by codingHahn** [comment]
No problems here as well, although I changed NetworkManagers dhcp-client to dhcpcd in the config files

**Comment by xtraeme** [comment]
is this still an issue?

**Comment by yopito** [comment]
NetworkManager-1.22.6_1 is working fine for me ; however network-manager-applet-1.8.24_1 does not not "see" that it's working.

**Comment by codingHahn** [comment]
Could not reproduce this anymore. Will close this, as the version is outdated
