### ISSUE TITLE
dkms: Drop the 'linux-headers' package dependency?

### ISSUE THREAD

**Issue by b1scu1t** [void-linux/void-packages#18976]
### System

* package:  
`dkms_2.8.1`

### Expected behavior
To be able to install `dkms` without requiring the `linux-headers` meta-package. 

### Actual behavior
The `linux-headers` meta-package is installed, even if kernel headers are already provided by another package. E.g: `linux-lts-headers`.

### Steps to reproduce the behavior
`sudo xbps-install -S dkms`

### Notes
As Void provides multiple kernels and kernel headers, I don't think it would be good to have dkms depend on one package in particular. I only use `linux-lts` and `linux-lts-headers`, but dkms will also generate modules for `linux`, which I don't have installed.

**Comment by Piraty** [comment]
This affects platforms with custom kernel packages as well (rpi for example), so dkms pulls linux-headers and failes consequently during dkms builds because the version doesn't match (even further, version clash could occur but is unlikely since rpi kernel follows latest lts)

I doubt xbps in its current state can handle this nicely (as in: make dkms depend on a virtual target (via `depends=virtual?kernel-headers`) and all kernel headers `provide=kernel-headers` and let it pick the right one according to platfirm (or ask the user to install it?)

**Comment by xtraeme** [comment]
Bullshit

**Comment by Johnnynator** [comment]
The problem is, that we would need some way to say, pull in headers of every installed kernel. Our current solution is just, pull in the meta package for the latest version.

**Comment by Piraty** [comment]
dkms pulling in linux-headers by default is only an inconvenience for very few people (running either linux-lts exclusively or rpi*-kernels), who then have to take care to manually install the correct header package along the automatically pulled one. I think that's bearable, because with your proposal you'd still have to install it manually.
It just adds some unnecessary time to dkms build stage

**Comment by travankor** [comment]
You can use `ignorepkg=linux-headers`

**Comment by b1scu1t** [comment]
> You can use `ignorepkg=linux-headers`

Oh, a new feature in `xbps`?
I missed the announcement.
Will I be able to update/install/remove packages normally when a package is 'ignored'?

**Comment by q66** [comment]
yes

**Comment by b1scu1t** [comment]
Looking at what Arch Linux does, it just lists all kernel header packages as 'optional dependencies' of `dkms`. Meaning the end-user has to install it manually. The current behavior of depending on `linux-headers` explicitly, would work well with a default installation of Void but inconvenient in other cases.

Correct me if I'm wrong but `xbps` or at least the package template files doesn't have an 'optional dependencies' field or a `provides` field (based on [this issue](https://github.com/void-linux/xbps/issues/1)).

**Comment by Piraty** [comment]
`provides` is a valid field, just not documented in Manual.md i'm afraid.
Optional dependencies are not a thing in xbps.

`ignorepkg` seems the best option here

**Comment by q66** [comment]
i think it should also be possible to use `virtualpkg=linux-headers:linux-lts-headers` or something like that, to make it use the correct dependency instead of ignoring

**Comment by b1scu1t** [comment]
@q66 Your suggestion worked flawlessly with packages explicitly depending on `linux` and `linux-headers`. E.g. `cdemu-client` and of course `dkms`.

Its a nice and simple workaround/feature of `xbps`, so I think I'll close the issue.

Still hoping for _optional dependencies someday_, but that's an `xbps` thing...;)
