### ISSUE TITLE
Obs studio (GPL2+) includes MIT licensed plugin in package

### ISSUE THREAD

**Issue by obunden** [void-linux/void-packages#19434]
If i'm not mistaken 'ftl-sdk' is MIT licensed and Obs is GPL2 (or later). It's probably best to put it in a separate package to avoid issues or confusion. Might also be worth it to do the same with the rest of the plugins for simplicity/maintenance reasons.

**Comment by obunden** [comment]
Just noticed that I can't see the browser plugin inside of obs so there might be other issues with the package. @lemmi if you are using obs could you check if this is accurate?

**Comment by lemmi** [comment]
I didn't add those plugins and I'm not using them. I think @the-eater added those. Maybe he can jump in. If not, I'll look into it.

**Comment by xtraeme** [comment]
assigned to pkg maintainer

**Comment by the-eater** [comment]
I just added all the then git submodules that existed, the browser doesn't build because we don't have CEF. (might be a nice to have :thinking:)

outside that, ftl-sdk is compiled statically into `obs-outputs.so` plugin, which makes the licenses problem also exist upstream? we can bundle it on it's own, but it's a requirement of running obs so idk what the best action is to take here

**Comment by lemmi** [comment]
so .. finally got the time to look at this. I don't like it one bit and I'm very close to just removing `ftl` from obs unless someone else is willing to make a package for it.
The `obs-vst` plugin doesn't have a release. So it's either out aswell or left as submodule. Plus there is plenty filters to be had via jack/ladspa...
`obs-browser` needs CEF and I will not be maintaining that.

Unless I'm missing something, I'm going to the remove the extra bits soon.

**Comment by lemmi** [comment]
Closed in 7e42a51847e5f5fe5d5fca62b9f0f2b9c3016af6
