### ISSUE TITLE
xbps-src -o does not seem to work anymore

### ISSUE THREAD

**Issue by xtraeme** [void-linux/void-packages#19495]
```
[juan@leysa void-packages]$ ./xbps-src -o ~webengine show-options qt5
=> qt5-5.13.2_2: the following build options are set:
   webengine: Build Chromium-based WebEngine component (ON)
[juan@leysa void-packages]$
[juan@leysa void-packages]$ grep -i opt ~/.xbps-src.conf
XBPS_PKG_OPTIONS=elogind
```

I think this is due to @q66 recent changes to the build options.

**Comment by q66** [comment]
ok, i'll take a look if i can reproduce and fix this

**Comment by q66** [comment]
This never worked, even before my changes. The problem is basically that inside `setup_pkg` there is `. $XBPS_CONFIG_FILE 2>/dev/null` so everything that's set inside config file still overrides arguments unconditionally.

**Comment by q66** [comment]
My proposed fix would be something like...

1) run that line in `setup` pkg only if `$IN_CHROOT`; the main point of it seems to be that inside chroot, the generated `xbps-src.conf` is run
2) change generation of `xbps-src.conf` so that it doesn't just `grep` out variables from the real config file, as that's not very good - if you have any sort of conditional logic in your conf, or e.g. sourcing other confs, that will break - instead take a list of `XBPS_` variables that are set and actually set them for the generated config.

that should probably fix it for real

**Comment by q66** [comment]
@xtraeme Actually, do we need to run that line at all? Since `xbps-src` is executed in both chroot and outside, shouldn't the first config file read that is directly in `xbps-src` deal with it?

**Comment by xtraeme** [comment]
@q66 probably that line is obsolete by the recent changes. I'd vote for the second option, looks cleaner

**Comment by q66** [comment]
Those were steps, not options :) But in order for step 2 to work, we'll need to either drop the line entirely or change it to only run in chroot. As far as I can tell, dropping it entirely should be fine.

**Comment by xtraeme** [comment]
any progress on this?

**Comment by q66** [comment]
sorry, haven't had time to look into it yet, had more urgent things to do; this is not a new issue (or an issue caused by my changes) so it'll have to wait a bit
