### ISSUE TITLE
public custom user repositories

### ISSUE THREAD

**Issue by whoizit** [void-linux/void-packages#19830]
My friend and I got a lot of refusals to add templates to `void-packages` repo. My friend left the Void Linux community too early for this reason. I hate this situation too.

I did not find a guide on how to use my own public repositories. It looks like `xbps-src` is nailed to `void-packages`. 

I want to create my own public repository (not fork `void-packages`). Also without `srcpkgs` dir inside repo. So that other users can easily find, use my templates, and also can add their own templates to my repository.

So my question is how to create my own `void-packages-extra` (or `void-extra-packages`) which is not a fork of `void-packages` or maybe it is worth thinking about taking out `./xbps-src` from the `void-packages` tree and make it available as system package to public user repositories

I can’t lead a discussion about this because I don’t really speak English, it’s an online translator.

**Comment by Anachron** [comment]
So how do you  expect this to work without forking the void-packages repo?
You either have the latest version with `void-packages` or you have to fork it and then keep merging upstream to your fork.

Supporting to `srcpkgs` dirs is not only very error-prone and time-intensive, it's also the wrong way of handling the issue imo.

**Comment by whoizit** [comment]
Arch Linux has a system-wide `makepkg` application that builds user PKGBUILDs
Gentoo has `layman` and separate user repos that are going builds through emerge

**Comment by whoizit** [comment]
The current state of Void Linux is centralization and dictatorship. I have no freedom to create my own public template repositories

**Comment by Anachron** [comment]
You can create your own repository with compiled packages and share it with someone else. 
My suggestion: Make a new git repo, put your `srcpkgs` inside it and build those packages.
Then you host your own repository somewhere and add it to your `xbps` config using https://docs.voidlinux.org/xbps/repositories/custom.html

**Comment by Piraty** [comment]
sure you do have freedom. xbps-src neither is centralized, nor does it dictate anything to you.
it's all open source, so grab the sources and modify+use it to your liking (according to the license), build the packages you want, live happy life.

Some people do have a branch with all their customizations/additions and build packages from that branch.

**Comment by whoizit** [comment]
@Anachron 
> My suggestion: Make a new git repo, put your srcpkgs inside it and build those packages.

This does not work
```
void-packages-extra $ ~/void-packages/xbps-src pkg z
=> ERROR: xbps-src: unexistent file: /home/user/void-packages/srcpkgs/z/template
```

**Comment by xtraeme** [comment]
The `void-packages` is self-contained. What does that mean? that you can clone it everywhere and it will be always up-to-date.

There's no plan to make xbps-src code work outside of it. It was this way years ago and it was a pain to maintain.

As @Anachron pointed out above you can clone it and add your own custom pkgs to share them with your friends.

So closing this because we don't want to be the next AUR.

**Comment by whoizit** [comment]
https://github.com/void-users/packages

**Comment by Anachron** [comment]
I find it quite bad to start a user repository just because its not accepted here. The entry for packages on here is already quite low.

**Comment by fosslinux** [comment]
I regularly create packages in `srcpkgs/`, sometimes for testing, in my local fork of void-packages and `./xbps-src pkg` them up and install them on my system.... this is what almost all contributors do for their pull requests for testing. I do not understand what you are asking for? Adding a new package locally is as simple as making the template and ./xbps-src pkg, and distributing it is as simple as uploading it to any hosting.

If you are asking why not every single PR is accepted? It is simply because not every single PR is up to the quality that is needed in the void linux repository. If you see my commit history here you will see a large number of closed pull requests around a year ago. This was because I was not very good at programming, scripting, xbps or packaging and as a result produced poor templates and broken updates.

The only thing I can see coming out of a user repository is poor/extraneous templates and broken packages/updates, as I created in earlier times.
