### ISSUE TITLE
Package Request: nextdns

### ISSUE THREAD

**Issue by xscd** [void-linux/void-packages#19905]
### Description:

This project is a DNS53 to DNS over HTTPS (DoH) proxy with advanced capabilities to get the most out of NextDNS service. Although the most advanced features will only work with NextDNS, this program can work as a client for any DoH provider.

### Links:
Github: https://github.com/nextdns/nextdns

**Comment by CameronNemo** [comment]
Note there is also Stubby (already packaged) if DNS over TLS is not blocked by your ISP. Supported by NextDNS, Cloudflare, and presumably others.

**Comment by gspe** [comment]
@xscd I've made a template for it.
It doesn't work with Void out of the box, but it's easy to configure to work with Void.

The only NextDNS commands that work is `nextdns run` so you can start it with something similar:
```
sudo nextdns run \
  -config <your config id> ...
```

In order to use it with Void as system service, you have to put your configuration in 
`/etc/nextdns/nextdns_conf` file and symlink `/etc/sv/nextdnsd` to `/var/service`

To setup the system to use NextDNS as a resolver, un-comment the last line in `/etc/resolvconf.conf` to `name_servers=127.0.0.1` and restart resolvconf with `resolvconf -u` now NextDNS should be used as dns resolver

**Comment by dm17** [comment]
Thanks @gspe that is crucial info for setup considering there are barely any mentions of using nextdns with openresolv. The nextdns setup instructions mention "DNSOverTLS=yes" for the systemd-resolved config, but I don't see how to enable or check if that is working in the openresolv + nextdns setup. Any ideas? 
Is there any NetworkManager related config for nextdns in this case?
