### ISSUE TITLE
minigalaxy: /share/minigalaxy/ui/login.ui: No such file or directory

### ISSUE THREAD

**Issue by anjandev** [void-linux/void-packages#21347]
### System

* xuname:  
```
[anjan@navi:~]$ xuname 
Void 5.4.33_2 x86_64 AuthenticAMD notuptodate rFFFF 
```
* package:  
  * minigalaxy-0.9.4_1

### Expected behavior
launching minigalaxy launches minigalaxy.

### Actual behavior

I get the following output:

```
Traceback (most recent call last):
  File "/bin/minigalaxy", line 66, in <module>
    main()
  File "/bin/minigalaxy", line 57, in main
    from minigalaxy.ui import Window
  File "/usr/lib/python3.8/site-packages/minigalaxy/ui/__init__.py", line 2, in <module>
    from minigalaxy.ui.window import Window
  File "/usr/lib/python3.8/site-packages/minigalaxy/ui/window.py", line 5, in <module>
    from minigalaxy.ui.login import Login
  File "/usr/lib/python3.8/site-packages/minigalaxy/ui/login.py", line 13, in <module>
    class Login(Gtk.Dialog):
  File "/usr/lib/python3.8/site-packages/gi/_gtktemplate.py", line 226, in __call__
    bytes_ = GLib.Bytes.new(file_.load_contents()[1])
gi.repository.GLib.Error: g-io-error-quark: Error opening file /share/minigalaxy/ui/login.ui: No such file or directory (
```

### Steps to reproduce the behavior
Try to launch minigalaxy.

**Comment by not-chicken** [comment]
Weird. I wasn't able to reproduce this on my main PC but can do on my other one. 
Check if you can launch it by
```
[~]$ /usr/bin/minigalaxy
```
It looks to me that issue is with the change in paths defined in the source by [this](https://github.com/sharkwouter/minigalaxy/commit/b0f71e5c05972314bf5a7318019e600b2b8d9daf) commit.

As far as I can tell this shouldn't be packaging related. Still I'd prefer someone with experience in python to have a look at this first before I open this issue at upstream.

**Comment by sgn** [comment]
Better receipt for reproducible bug:

    /bin/minigalaxy

**Comment by sgn** [comment]
Please test with #21554, I'll merge it in tomorrow.
