### ISSUE TITLE
Cyclic dependency (notably, mesa, gobject-introspection)

### ISSUE THREAD

**Issue by fosslinux** [void-linux/void-packages#21899]
I found this while trying to build `mesa` using `-N`:

```
=> ERROR: Build-time cyclic dependency gobject-introspection(host), cairo(host), mesa(host), ocl-icd(host), ruby(host), pango(host), gobject-introspection(host) detected.
```

The one-off solution I used was to disable `mesa-opencl`, build mesa, rennable and build mesa again, pulling in all of these dependencies and the cyclic dependency satisified.

However I do not think this is a good long-term solution - we should fix this.

We could make a separate ruby package that disables the `pango` gem, which would remove the cyclic dependency.

**Comment by st3r4g** [comment]
This is not a real build-time cycle, since `ocl-icd` is just a runtime dependency of a `mesa` subpackage. But sadly at the moment `xbps-src` treats build-time and runtime dependencies in the same way (tries to build everything before), so loops like this happen.
That said, removing `ocl-icd` from `mesa-opencl`'s deps doesn't look too wrong imo, because `mesa-opencl` is an implementation and not a program linking to OpenCL.

**Comment by fosslinux** [comment]
AFAIK, it depends at runtime on `libclc`  (or used to) and that is now provided by `ocl-icd`. Pinging @q66 who added the dependency and knows more than me about this. But yes, you are right, it shouldn't create a cycle, as it is a runtime dependency.

**Comment by st3r4g** [comment]
> AFAIK, it depends at runtime on `libclc` (or used to) and that is now provided by `ocl-icd`.

Aren't those two completely different things? `libclc` is a different pkg, and still a dependency:
```
mesa-opencl_package() {
        short_desc="Mesa implementation of OpenCL (r600+ only)"
        depends="libclc-git ocl-icd"
        ...
```

**Comment by fosslinux** [comment]
Oh, whoops I meant `libOpenCL`. See in commit `eb296ea869813430981404352595013718d3cd0c` it was dropped and `ocl-icd` `provides="libOpenCL-1.2_1"` and `eplaces="libOpenCL>=0"`. But I have no idea whether libOpenCL/ocl-icd is truly needed.

**Comment by st3r4g** [comment]
Oh ok, yes it seems `libOpenCL` was renamed to `ocl-icd`, q66 just updated the deps to the new names.
As an equivalent example, `mesa-vulkan-intel` (the API implementation) is not depending on `vulkan-loader` (the loader). Applications using the API pull in the loader, and the user is expected to install the implementation matching its hardware

**Comment by fosslinux** [comment]
I am not very knowledgeable about mesa. If I understand correctly, `mesa-opencl` would not work without `ocl-icd` at all? Similarly with `mesa-vulkan-jntel` and `vulkan-loader`?

**Comment by st3r4g** [comment]
This is not really about mesa specifically.
A user has no reason to install `mesa-opencl` (or any other implementation of an API) alone by itself, unless he wants to do OpenCL development (in this case he should know he needs the loader too). Let's say instead someone wants to use an OpenCL-powered application: he will install that application, which links to the loader, therefore automatically getting the loader as a dependency. The simplest possible example of such an app is `clinfo`. Then you run `clinfo`, which says there are no actual OpenCL implementations in your system. They can't be automatically provided, because we don't know the hardware configuration (or needs of a certain impl) of the user. It is at this point that the user must make a choice: let's say he has an AMD card, so he goes for `mesa-opencl`. Or maybe the soon-to-be-packaged ROCm. Or both. `ocl-icd` is already there, pulled in by the actual application the user is trying to run.

**Comment by fosslinux** [comment]
I see, thanks for the explanation.
