### ISSUE TITLE
Sway requires mesa-dri

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#22007]
### System

* xuname:  
Void 5.4.40_1 x86_64 GenuineIntel uptodate rFFFFFFF
* package:  
`sway-1.4_3`

### Expected behavior
`mesa-dri` is installed with `sway`
### Actual behavior
Sway doesn't start unless I manually install `mesa-dri`.
### Steps to reproduce the behavior
Install `sway`, but not `mesa-dri`.
Start Sway from the console.

**Comment by st3r4g** [comment]
This is currently documented in https://docs.voidlinux.org/config/graphical-session/wayland.html#video-drivers
I agree that the mesa drivers should be automatically installed by default, but adding them to `sway` is wrong. Instead, `libglvnd` should pull them in as default GL provider, but this is not so easy to achieve with current packaging situation

**Comment by notramo** [comment]
What about adding an install message with the link?

**Comment by st3r4g** [comment]
Users are encouraged to read the docs. Relying on install messages is poor because they can be easily lost in xbps install log (and many people don't pay attention to them anyway)

**Comment by ericonr** [comment]
@st3r4g would this really solve the issue? If someone had installed nvidia drivers as the libglvnd provider, and then installed Sway, it still wouldn't work.

**Comment by st3r4g** [comment]
Well I'd say users are expected to know that sway doesn't work with nvidia drivers. Adding a hard-dependency to `mesa-dri` wouldn't work either, because users still won't be prevented from installing `nvidia` (they will be side-by-side with the mesa drivers). The only way would be with a `conflicts=` but... ugh

**Comment by notramo** [comment]
> Users are encouraged to read the docs. Relying on install messages is poor because they can be easily lost in xbps install log (and many people don't pay attention to them anyway)

Do it harm anything? If not, why not add it? It's better than nothing.

**Comment by ericonr** [comment]
@notramo the way I see it, this is due to Void's policy for packages. We tend to not bundle anything that's not essential. For example, you can install an X window manager and that won't pull in the actual Xorg server, because you might desire to run that through the network instead. For wayland, you could use the X backend (for some reason) or even the headless one, and in that case it won't make sense for `mesa-dri` to be installed.

**Comment by Duncaen** [comment]
> Do it harm anything? If not, why not add it? It's better than nothing.

Yes it makes people even less likely to read actually important INSTALL messages, like the recent openssh update that required the user to restart sshd for new connections to work.

**Comment by ericonr** [comment]
This is being discussed in #27286 and #18712 , closing this.
