### ISSUE TITLE
System crashes after kscreenlocker update (5.19.0_1)

### ISSUE THREAD

**Issue by jalelegenda** [void-linux/void-packages#22750]
### System
* machine: Dell XPS 13 9380
* DE: KDE Plasma 5.18.5
* Kernel: 5.6.17_1

* xuname:  
  * Void 5.6.17_1 x86_64 GenuineIntel uptodate rrrmFFFF
* package:  
  * kscreenlocker 5.19.0_1

### Expected behavior
The usual day-to-day DE stuff.

### Actual behavior
* Lockscreen flickers (SDDM)
* KWin does not start, no windows wrappers (can't resize or move, only open through shortcuts)
* System freezes completely after a while, cannot switch to tty, have to hard reset

**Comment by Johnnynator** [comment]
The problem is most likely that only a part of the KDE Plasma update did get into the repo, halfway through the repo was staged (package didn't register) because I missed to trigger a rebuild for kdevelop. I should specify Plasma deps with a more precise version, since mixing multiple Plasma versions is prone to result in errors. The main repo should have full plasma in the next 30min and updating should fix it.

**Comment by jalelegenda** [comment]
I updated and it works now.
