### ISSUE TITLE
MesaLib-devel-32bit dependency tree is requiring non existent packages.

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#22840]
log from `jerwin` in `#voidlinux` : https://clbin.com/dPDeF

So it's basically `MesaLib-devel-32bit` -> `mesa-opencl-32bit` -> `clang-32bit`, and that last package doesn't seem to exist at all.

@q66 and @st3r4g

**Comment by jesseerwin** [comment]
Note that `sudo xbps-remove -R glu-devel-32bit libfreeglut-devel-32bit` fixed the issue.

**Comment by st3r4g** [comment]
The error happens because `clang` is `lib32disabled=yes`

**Comment by q66** [comment]
should be fixed by https://github.com/void-linux/void-packages/commit/81c5dec4859c37ecc84d7f0943d256ac5b7f5f98 and https://github.com/void-linux/void-packages/commit/a2937fff03fbd9d343272b3d9e8d8e62287b8c15

`libclang-32bit` and `libclang-cpp-32bit` will be present on multilb after the build is done
