### ISSUE TITLE
What to do if the 'select label type' doesn't show up during partitioning ? 

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [void-linux/void-packages#22855]
When you start partitioning your disk,  there is a little menu like this:

```
select label type
gpt
dos
sgi
sun
```

what if this menu doesn't show up when installing void ? how to bring it back ?

**Comment by hippi777** [comment]
hi there! :)

according to the manual of cfdisk, there u just cant (if im right; viewed it on deb10, so things may have changed in newer versions)

so u need to choose fdisk in the installer, where `p` will give u the info about the current label, and `g` `G` `o` or `s` for gpt sgi dos sun respectively

otherwise u can also use parted (command line; scriptable), gparted (gui app that can also mess with ur filesystems on top of the partitions), sfdisk (command line; for scripting), gdisk (aka gptfdisk), cgdisk, and sfdisk, that are more or less similar tools to the fdisk family, but they arent equivalent, and u should consult with their manuals if u wanna use them... if u use either of these, then u can skip the partitioning in the installer...

have fun! :)

**Comment by ReductoAdAbsurdum** [comment]
Does parted come with the void installer ? `void-live-x86_64-20191109.iso` ?

**Comment by hippi777** [comment]
i think not, u should either install it or make ur own live if the target machine has no internet connection, or u could even bring ur own repo with that and its deps, but thats maybe nontrivial :D also, u can do it by making the storage available to any other system, as this is not necessary to be done while installing, cuz its permanent on the disk (sorry if i say the obvious, i dunno the exact level of ur knowledge....) however i think the most straightforward is still to use fdisk, its not hard at all, just give it the command `m` and then it will give u back a simple command list :)

**Comment by abenson** [comment]
Before launching the installer, you can issue:

```
wipefs -a /dev/sdX
```

Or
 
```
cfdisk -z /dev/sdX
```

With the latter you can do your partioning then and just accept it in the installer.

**Comment by ericonr** [comment]
Not exactly the correct forum for the question, but it's been inactive for a while as well.

Feel free to reopen.
