### ISSUE TITLE
[libsigrok] 61-libsigrok-uaccess.rules udev rule doesn't work correctly

### ISSUE THREAD

**Issue by Gigahawk** [void-linux/void-packages#23580]
### System

* xuname:  
  *`Void 5.4.50_1 x86_64 GenuineIntel notuptodate rrrmFFFFFFFFFFFFFF`
* package:  
  *`libsigrok-0.5.2_1`

### Expected behavior
Sigrok compatible devices can be accessed without root access.

### Actual behavior
Attempting to access a Sigrok compatible device without root access will result in:
```
λ › sigrok-cli -d saleae-logic16 --scan                                                 ~
sr: ezusb: failed to open device: LIBUSB_ERROR_ACCESS.
sr: saleae-logic16: Firmware upload failed, name saleae-logic16-fx2.fw.
The following devices were found:
saleae-logic16 - Saleae Logic16 with 16 channels: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
```
### Steps to reproduce the behavior
* Install `libsigrok` and `sigrok-cli`
* Run `sigrok-cli --scan`

**Comment by JBKingdon** [comment]
Since this issue is one of the top hits for people searching for sigrok udev problems, I thought it might be useful to add this. I couldn't get the existing udev rules from the contrib directory working on RHEL 8.7, and unfortunately I find the udev system a little difficult to figure out. I eventually gave up and created a smaller udev rule for the specific device I have and this works for me, with <mygroup> replaced with the default group for my userid. I created this as `/usr/lib/udev/rules.d/99-dslogic.rules`

```
ACTION!="add|change", GOTO="libsigrok_rules_end"
SUBSYSTEM!="usb|usbmisc|usb_device|hidraw", GOTO="libsigrok_rules_end"

# DreamSourceLab DSLogic Plus
ATTRS{idVendor}=="2a0e", ATTRS{idProduct}=="0020", MODE="0660", GROUP="<mygroup>"

LABEL="libsigrok_rules_end"
```
