### ISSUE TITLE
plan9port: hardcoded PLAN9 variable is wrong

### ISSUE THREAD

**Issue by goleo108** [void-linux/void-packages#23639]
@leahneukirchen here are examples how to fix it:
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-util/plan9port/plan9port-0_pre20200526.ebuild#n74
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/plan9port#n40
https://github.com/jrmarino/ravensource/blob/master/bucket_95/plan9port/specification#L59

**Comment by mmnmnnmnmm** [comment]
Excuse me if I'm missing anything, but is it wrong?

Line 45 changes the path for the install script:

    xargs -a lib/moveplan9.files -d'\n' sed -i "s#$wrksrc#/usr/lib/plan9#"

And I did a quick grep -r over /usr/lib/plan9 and the only things that I can find that are actually wrong is lookman.index and macedit.

I think lookman.index is wrong because mkindex generates it using the wrksrc before it's moved to /usr/lib.  Although lookman still works despite the incorrect path in the index.

**Comment by leahneukirchen** [comment]
I think this only affects HTML man pages?

**Comment by leahneukirchen** [comment]
ah, this refers to `/usr/local/plan9`.

**Comment by goleo108** [comment]
the problem is the install script doesn't change PLAN9 variable hardcoded to `/usr/local/plan9` in binaries in case you don't set PLAN9 environment variables, which in my case led to failing to start rc as user shell thanks to #23640

both gcc and clang do build astronomicly slow, so I simply `# ln -s /usr/lib/plan9 /usr/local/` just to save my time
