### ISSUE TITLE
OBS Studio missing browser source feature?

### ISSUE THREAD

**Issue by PrinceKael** [void-linux/void-packages#23685]
### System

* xuname:  
   Void 5.7.9_1 x86_64 GenuineIntel uptodate rrrmFFFFFFFFF
* package:  
   obs-25.0.8_1

### Expected behavior

When adding a new source to the scene, there should be a "Browser Source" option available as of version 25.0

### Actual behavior

That setting is missing.

### Steps to reproduce the behavior

Open OBS, in the subwindow that says "Sources" click on the + sign and you'll see it's not there.

This is a pretty big feature that I was excited for and is helpful to anyone that streams and wants to promote community engagement. I don't really know why it doesn't work but I'm hoping someone can help me add it.

**Comment by luhann** [comment]
From https://github.com/obsproject/obs-browser:

This plugin is included by default on official packages on Windows and macOS. **While Linux is supported, the official ppa does not currently include the browser source due to a conflict with GTK**.

See also: https://github.com/obsproject/obs-browser/issues/219

Void tries to stay as close to upstream as possible, and it looks like upstream doesn't include it on linux by default. But it looks like the obsproject people are aware and working on it.

**Comment by ericonr** [comment]
From what I can tell (given https://github.com/obsproject/obs-browser/issues/219#issuecomment-744023786), this requires us to package CEF (chromium embedded framework). That's unlikely to be viable, unless patches from electron are easy to port over.

**Comment by Gotchfutchian** [comment]
> From what I can tell (given [obsproject/obs-browser#219 (comment)](https://github.com/obsproject/obs-browser/issues/219#issuecomment-744023786)), this requires us to package CEF (chromium embedded framework). That's unlikely to be viable, unless patches from electron are easy to port over.

Why would that be unlikely? Maybe have it as a restricted packeges so we can build it from source?

**Comment by ericonr** [comment]
Because compiling / patching chromium based things is a great pain. Both in dev and computer time.

And having it as restricted kind of defeats the purpose, I think.
