### ISSUE TITLE
[Package request] 32-bit wine for x86_64-musl

### ISSUE THREAD

**Issue by Logarithmus** [void-linux/void-packages#24009]
Hello there. I've been using Void Linux with musl for a month now. So far, so good.
But recently I've discovered that `wine` for musl supports only 64-bit programs. After searching for a bit I found out this comment: https://github.com/void-linux/void-packages/pull/21701#issuecomment-624910468.
So my question is, what can be done about this linking problem?
I'll appreciate any help.

**Comment by ericonr** [comment]
You still can't install 32bit wine on a 64bit musl system, because we don't support multilib for musl. So you'd need a 32bit musl chroot, and if you're using a chroot you could be using a plain glibc chroot. That would be my recommended solution for running 32bit games on wine right now.

Regarding the linking issue, we'd have to debug the build process and / or talk with musl devs to see if we can track down what's going wrong.

**Comment by Logarithmus** [comment]
@ericonr OK, I understand that glibc chroot is the way to go now.
But please, can you explain what must be done in order to compile 32-bit (aka `multilib`) programs for `x86_64-musl`?
Is it due to some fundamental limitation of `musl` which make it impossible to run both 32-bit and 64-bit binaries? If no such limitation exist, then tell me, how can I learn to compile a package using `xbps-src` for `i686-musl`  in such way that it could be installed onto my `x86_64-musl` system?

**Comment by ericonr** [comment]
That I don't know :p 

I believe musl doesn't have an easy mechanism for it, neither does our package build system.

**Comment by ericonr** [comment]
@Logarithmus musl doesn't support multilib (the mechanism used by glibc), so for now this can only be solved with a separate 
i686-musl chroot. If/when we get multiarch going, 32bit wine should become automatically available.

**Comment by ericonr** [comment]
I closed this for now, because there's nothing simple that can be done.
