### ISSUE TITLE
Package request: LibreWolf

### ISSUE THREAD

**Issue by handow23** [void-linux/void-packages#24393]
A fork of Firefox, focused on privacy, security and freedom.

LibreWolf is designed to minimize data collection and telemetry as much as possible. This is achieved through hundreds of privacy/security/performance settings and patches. Intrusive integrated addons including updater, crashreporter, and pocket are removed too

Project page: https://librewolf-community.gitlab.io/

**Comment by ericonr** [comment]
This package is available as a Flatpak, and that's probably the best way of using it.

**Comment by pullmoll** [comment]
We have GNU icecat (a.k.a. gnuzilla) and won't add yet another fork of Firefox to the repository.
It takes just too much man and machine power to maintain and build all the browsers.

**Comment by Piraty** [comment]
##515, #2735, #11549, #23628, #23310, #4130,

**Comment by autoteelar** [comment]
> We have GNU icecat (a.k.a. gnuzilla) and won't add yet another fork of Firefox to the repository.
> It takes just too much man and machine power to maintain and build all the browsers.

well, i tried but
Package 'icecat' not found in repository pool.

librewolf i heard is better anyways, and well why be at least a little open about it? being so closed like that doesn't sound like an open source community to me, just because you don't want to maintain it doesn't mean someone else wont want to, and the fact theres multiple duplicate tickets open about it just means theres that much want for it it. and it seems 90% of people myself included abstain against using flatpaks aswell.

**Comment by q66** [comment]
icecat was dropped

in case of a large web browser it's not about someone from the community wanting to maintain it or not, it puts a load on the infrastructure, and forks in general fail to maintain their stuff well enough to keep a reasonable security track record

if you don't want to use the flatpak, that's your problem, not ours

**Comment by q66** [comment]
void does not market itself as a minimalist distro, that's just the crowd projecting their own views on it

**Comment by sgn** [comment]
> Void Linux markets itself as a minimalist distro,

Citation Needed!

**Comment by q66** [comment]
again, citation needed
