### ISSUE TITLE
libreoffice meta package is GPL-3

### ISSUE THREAD

**Issue by sgn** [void-linux/void-packages#24445]
@pullmoll 
* package:  
  * libreoffice v7.0.0.3_1

### Expected behavior
Empty package shouldn't be GPL, since all other packages is derivative of an empty package,

**Comment by pullmoll** [comment]
Well, need to change the template to add license= to all subpackages then.
I don't know if it's worth to change the meta package to BSD-2-Clause just because it's itself empty.
@void-linux/pkg-committers ?

**Comment by Duncaen** [comment]
I don't know if this is even worth the change, `metapackage` as license is worse than just the package license.

Imho to avoid confusion just use the license the software has.

**Comment by Chocimier** [comment]
Not worth it, marking empty package with license= `BSD`, `GPL` or anything other is equally weird.

I would propose to use `empty=yes` instead of `build_style=meta` as this is not a build style, fail if package marked empty has files (unlike `=meta`) and not set license into binpkgs for them. But not setting license that was rejected already.

**Comment by Duncaen** [comment]
Why should `xbps-query -S libreoffice` not contain the license of libreoffice, just because of an implementation design that we are using a meta package?

**Comment by Chocimier** [comment]
Exactly because of implementation: `xbps-query -p license X` is metadata of files contained in package X, not its dependencies.
What should be license of lxqt or xorg that depends on packages under variety of licenses?
That said, in case of "uniform" sets like libreoffice, referencing deps is strictly better than previously-agreed constant `BSD-2-Clause`.

**Comment by Vaelatern** [comment]
I agree with Duncaen and Chocimier.

**Comment by pullmoll** [comment]
I think we agree on WONTFIX - closing.
