### ISSUE TITLE
Weird organization of maven packages

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#24617]
The `apache-maven-bin` package is prebuilt, has files in `/opt`, but symlinks to its files in `/usr/bin`.

On the other hand, the `apache-maven` package has compiled java stuff in `/usr/share`, requires sourcing a profile file to get access to its tools, and if `apache-maven-bin` is installed at the same time, its tools will be first in the PATH anyway, so the profile doesn't really help.

Then, some packages have `apache-maven`, others `apache-maven-bin` in `hostmakedepends`.

IMO neither of these packages really fit the proper packaging guidelines. So my questions are:

- should  the maven binaries become alternatives, or should `apache-maven` become the preferred provider of maven stuff?
- should we move all templates to `apache-maven` (and potentially remove `apache-maven-bin`? Why is it in the repos?)

**Comment by the-maldridge** [comment]
If my memory is correct we had apache-maven-bin first but called apache-maven, and then later I added maven, and what should happen now is everyone should switch to apache-maven, and we should only use apache-maven-bin for bootstrapping.  (Interestingly this is why we have ant as well, because and used to bootstrap maven but this is no longer the case).

**Comment by ericonr** [comment]
But `apache-maven` bootstraps itself. It pulls in a pre-built version and uses it. We should totally remove `apache-maven-bin`.

**Comment by fosslinux** [comment]
In the interest of reproducibility IMO its better to have a `-bootstrap` package or something along those lines. That way `apache-maven` bootstrap wont break every update.

**Comment by ericonr** [comment]
Why would it break?
