### ISSUE TITLE
Add qt5-svg as dependency to ipython / matplotlib / both?

### ISSUE THREAD

**Issue by foopub** [void-linux/void-packages#24871]
Attempt to run `ipython --matplotlib` results in the following:

`ImportError:
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7, PyQt5, PySide >= 1.0.3 or PySide2 is available,
    and only one is imported per session.

    Currently-imported Qt library:                              'pyqt5'
    PyQt4 available (requires QtCore, QtGui, QtSvg):            False
    PyQt5 available (requires QtCore, QtGui, QtSvg, QtWidgets): False
    PySide >= 1.0.3 installed:                                  False
    PySide2 installed:                                          False
    Tried to load:                                              ['pyqt5']`

Which is easily fixed by installing the python3-PyQt5-svg package - although I'm not sure which package (matplotlib or ipython or both) should have it as a dependency.

**Comment by ahesford** [comment]
Unfortunately, XBPS does not support optional dependencies. The `python3-PyQt5-svg` package is only required if the qt5 backend is used in matplotlib. Because this is a configuration option (and isn't even the default), forcing people to pull in or ignore this package isn't appropriate.

You'll just have to manually install `python3-PyQt5-svg` to support this backend.
