### ISSUE TITLE
[TRACKING] removal of webkitgtk{,2} package

### ISSUE THREAD

**Issue by Gottox** [void-linux/void-packages#2488]
webkitgtk2 had its last release 2,5 years ago. Since then various bugs in webkit came up. To reduce the attack surface of applications using webkitgtk we should replace it with its successor webkit2gtk or ultimatively remove applications that depend on webkitgtk. Namely those packages are:

```
$ xbps-query -RX webkitgtk2
````
* [x] geany-plugins-extra-1.33.0_2
* [x] libgnucash-2.6.19_1
* [x] python-webkit-1.1.8_1
* [x] webkitgtk2-devel-2.4.11_6
* [x] wxWidgets-3.0.4_7
* [ ] yad-0.40.3_1
```
$ xbps-query -RX webkitgtk
```
* [x] balsa-2.5.6_1
* [x] birdie-1.1_3
* [x] dwb-2014.03.07_4
* [x] foobnix-3.1.01_2
* [x] lightdm-webkit-greeter-2.0.0_2
* [x] uzbl-0.9.1_4
* [x] webkitgtk-devel-2.4.11_6

**Comment by Johnnynator** [comment]
lightdm-webkit-greeter can be replaced by Antergos [web-greeter](https://github.com/Antergos/web-greeter). I made a template for it already a few month ago https://github.com/Johnnynator/void-packages/commits/lightdm-webkit2

**Comment by Hoshpak** [comment]
No other package depends on `libgnucash` according to `xbps-query -RX` so it's a matter of updating the `gnucash` package to the 3.x release which is able to use `webkit2gtk`. My last attempt at updating that package failed because of issues with some google library. I will try again with the current release.

`wxWidgets` can at least partially be replaced by the `-gtk3` version which can provide the webview functionality using `webkit2gtk`. I havent tried if all packages that currently are compiled against the gtk2 version will work with the gtk3 version yet. The PR for that is https://github.com/void-linux/void-packages/pull/2433 . If the ultimate goal is removal of the `wxWidgets` package, I will modify that to build the `-common` package from the `-gtk3` sourcepkg instead of the `wxWidgets` package to make removal of it later easier.

**Comment by maxice8** [comment]
working on `uzbl`

**Comment by maxice8** [comment]
`uzbl` is still working on webkit2gtk

'dwb` seems to be dead, last commit was on 2016

**Comment by maxice8** [comment]
`birdie` has support upstream but needs a new tagged release.

**Comment by maxice8** [comment]
`yad`  has support upstream but needs a new tagged release.

**Comment by maxice8** [comment]
`dwb` also segfaults so i can say nobody is using it or somebody is using it but never ran xbps-install -Su

**Comment by maxice8** [comment]
Removing webkit dependency on cinnamon (#2730), it was removed on 3.2.0 with this message.

[ itzexor ]
  * cinnamon-settings: remove unused webkit code and dependency

**Comment by maxice8** [comment]
removing webkit dependency on apvlv (#2731), it is guarded behind a switch that is OFF by default and we never touched it, so there is no loss in removing it.

See the [debian changelog](https://sources.debian.org/src/apvlv/0.1.5+dfsg-3/debian/changelog/) for the switch info.

**Comment by Hoshpak** [comment]
Regarding python-webkit: I could not find any package that depends on it and the git repository at https://git.savannah.gnu.org/cgit/pythonwebkit.git lists no changes for the last 7 years. It looks to me like the package could just be removed.

**Comment by asergi** [comment]
`python-webkit` (aka `pywebkitgtk`) is old and dead upstream. Can be safely removed.

**Comment by maxice8** [comment]
python-webkit was removed on #2782

**Comment by Gottox** [comment]
Proposal:
* remove yad. There's zenity, kdialog, dialog,..
* remove lightdm-webkit-greeter-2.0.0_2; add lightdm-webkit-greeter as suggested by @Johnnynator
* remove uzbl
* remove foobnix
* remove birdie

**Comment by maxice8** [comment]
This https://github.com/void-linux/void-packages/pull/4157 removes uzbl foobnix birdie and lightdm-webkit-greeter.

currently webkitgtk fails to build on armv7l-musl and it is blocking the ICU update on that arch.

**Comment by maxice8** [comment]
webkitgtk has been removed :+1:
