### ISSUE TITLE
xbps-src: use mirrors if available

### ISSUE THREAD

**Issue by waynevanson** [void-linux/void-packages#24968]
I live in Australia and was impressed by how fast the mirrors the region are compared to the defaults.
I was however dissatisfied by the how long I have to wait when running `./xbps-src binary-boostrap` and `./xbps-src pkg <pkg>`. 

I would like to see `./xbps-src` use my mirrors where applicable, so I can speed up development.
Some repositories may be unavailable (for example `debug` for MelbourneAU`), so the defaults should be used instead.

If this is unclear, I'll come back and edit the request tomorrow.

### System

* xuname:  `Void 5.8.9_1 x86_64 GenuineIntel uptodate rrFFFFF`

**Comment by Duncaen** [comment]
You can change the mirrors in `etc/xbps.d/repos-remote-*.conf`.

**Comment by waynevanson** [comment]
I have, but would like to see this being detected and changed for me.

**Comment by ericonr** [comment]
> I have, but would like to see this being detected and changed for me.

I'm not sure this works, since your files in `/etc/xbps.d` might include `ignorepkg` or `noextract` entries, which can break builds. `xbps-src` would have to run through your config files and extract only the `repository` entries, instead of just copying files from `etc/xbps.d`. There's also the issue that it'd have to be smart enough to understand how to assemble each arch's repo link when testing cross. I don't think this added complexity is desired in what already is a pretty complex program.

**Comment by ericonr** [comment]
I don't believe it's possible, or worth it, to make an implementation for this reliable. Closing for now.
