### ISSUE TITLE
Change do_check for python modules

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#25052]
Running `python3 setup.py test` outputs the following message:

```
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
```

Should we add `tox` to everything instead, or should packagers specify the tools themselves for all templates? In any case, it might make sense to fully remove `setup.py test` as something that `do_check` does.

**Comment by sgn** [comment]
No `tox` please, `tox` will check with external dependencies, as far as I understand.
(I added tox in the past, and I keep regret)

**Comment by ericonr** [comment]
I am using `pytest` in #25050

**Comment by Chocimier** [comment]
setup.py test is popular, behaves well like use system deps and has little dependencies, so more packages can be tested on first build when updated. Please don't remove until it works.

Requiring to specify do_check in all templates would be tedious.

pytest is good candidate for replacement, we could start with calling it in build style if installed (with checkdepends), otherwise do as before.

**Comment by ericonr** [comment]
> https://github.com/pypa/setuptools/issues/1684

Perhaps even `setup.py install` will be dropped, from what I understood of that issue. I think using pytest if it's available is a good solution.

**Comment by ahesford** [comment]
See #26901 for a proposed solution.
