### ISSUE TITLE
e2e's feature in the nextcloud client

### ISSUE THREAD

**Issue by jt0in3e** [void-linux/void-packages#25216]
### System

* xuname:  
  *Void 5.8.11_1 x86_64 GenuineIntel notuptodate rrFFFF*
* package:  
  *affected package(s) including the version*: ``nextcloud-client-3.0.1_1``

### Expected behavior
Norma installation without warnings.

### Actual behavior
After package installation there is a message 
> NextCloud client end-to-end encryption (e2e) is currently unavailable
(LibreSSL 2.9.2 does not provide EVP_PKEY_CTX_set_rsa_oaep_md primitive)

### Steps to reproduce the behavior
Install nextcloud-client

***

After installation there is the above warning regarding unsupportale e2e's feature in the nextcloud client. This install message were introduced on [August 29, 2019](https://github.com/void-linux/void-packages/commits/master/srcpkgs/nextcloud-client/INSTALL.msg). Since then it seems the EVP_PKEY_CTX_set_rsa_oaep_md primitive was implemented in Libressl (see [here #547](https://github.com/libressl-portable/portable/issues/547)).

Is it still relevant message? Could it be ignored? @yopito

**Comment by yopito** [comment]
generally speaking, this is an informative message.  
you can ignore this message until you want e2e between client and server.

I have to update packaging for nextcloud-client 3.0.2, I will give a look at this too. Stay tune.

BTW, I blindly package it, since I don't have nextcloud server access anymore.  
Feedback are welcome on its usage, don't hesitate to contact. 
I could also provides the maintainership of this package too.

**Comment by yopito** [comment]
BTW related to issue #16489 (same purpose)

**Comment by yopito** [comment]
this issue has been fixed

**Comment by Johnnynator** [comment]
@yopito If you add `closes #25216` to the commit message instead of `close issue` it should close it automatically.
