### ISSUE TITLE
Packaging: get git commit sha?

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-packages#25343]
I am working on packaging `chezmoi` for void, and the project maintainer requests that the git commit hash be added as a linker flag (see [here](https://github.com/twpayne/chezmoi/blob/master/docs/CONTRIBUTING.md#packaging)).

Is there a preferred way to do this in the template, other than hard-coding it?

**Comment by ericonr** [comment]
Hard coding is the way to go, unfortunately. I'm not sure it's entirely necessary, since we would be using tagged releases, which should be directly linkable to a specific commit.

The `-X main.date=$DATE` part is bad, though, and upstream should be told not to require it (or even suggest it, for that matter). It hurts reproducible builds for no gain.

**Comment by classabbyamp** [comment]
Thanks! I'll take that into advisement
