### ISSUE TITLE
proftpd in void linux

### ISSUE THREAD

**Issue by herveq1** [void-linux/void-packages#25914]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``
xuname
Void 5.8.16_1 x86_64-musl GenuineIntel notuptodate rFF
xbps-query  -p pkgver proftpd
proftpd-1.3.7a_1

### Expected behavior
at least let the user to login

### Actual behaviorfailed

login 
### Steps to reproduce the behavior

Hello dear maintainer of proftpd

There is now a few number of years that you are delevering a proftpd server
for which nobody can login in. That is useless...unless you are working with
windows in mind.

The result of your distribution proftpd-1.3.7a_1 is:

Password: 
530 Login incorrect.
ftp: Login failed.
Remote system type is UNIX.
Using binary mode to transfer files.

When I take the proftpd distribution package proftpd-1.3.7a and compile it
with this command :
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var/lib/proftpd --enable-auth-pam

With the same configuration file, I get this result that is quite OK.
Name (olix:hq): 331 Password required for hq
Password: 
230 User hq logged in
Remote system type is UNIX.
Using binary mode to transfer files

Did you spend 1 minute to test your binary ?

Have fun

**Comment by Duncaen** [comment]
> Did you spend 1 minute to test your binary ?

Have you considered that it is intentional and unless someone asks for it the maintainer how probably doesn't even use ftp anymore doesn't know that someone might want to use system users for authentication?

**Comment by fosslinux** [comment]
What @Duncaen said, and, how do you know that it hasn't broken in the meantime by an unrelated change to the Void ecosystem and it did work at the time of commit? The maintainers here are very busy and can't constantly be checking random small packages to check that they work just because they haven't been changed for a few months.

Furthermore, I don't think very many people at all use authenticated FTP... it's probably not something in a testing regime.

Surely, you have the 5 minutes available to make a pull request adding `--enable-auth-pam` to the configure_args?

**Comment by Piraty** [comment]
as a build option, ideally
