### ISSUE TITLE
elogind systemd dependencies

### ISSUE THREAD

**Issue by dreamer1234** [void-linux/void-packages#26177]
The elogind package is dependant on systemd.
Looking at the template:

[code]
post_install() {
        ln -s libelogind.pc $DESTDIR/usr/lib/pkgconfig/libsystemd.pc
        ln -s libelogind.pc $DESTDIR/usr/lib/pkgconfig/libsystemd-logind.pc
        ln -sr $DESTDIR/usr/include/elogind $DESTDIR/usr/include/systemd
        vinstall ./src/systemd/sd-id128.h 644 usr/include
        vinstall ./src/systemd/_sd-common.h 644 usr/include
        vinstall $FILESDIR/elogind.wrapper 755 usr/libexec/elogind
        vmkdir usr/lib/dracut/dracut.conf.d
        echo "install_items+=\" /usr/libexec/elogind/elogind-uaccess-command \"" >> ${DESTDIR}/usr/li
b/dracut/dracut.conf.d/elogind.conf
        vsv elogind
}
[/code]

Which seems a bad desing, since we are introducing systemd dependencies on a non systemd distribution.

**Comment by ofiala-a51** [comment]
This should be expected since elogind is just systemd's logind fork that doesn't depend on the whole systemd itself. If you are opposed to using systemd components in your system like many of us, you should consider using an alternative -- see #24580. You can get it and compile it yourself while the PR is waiting to merged. Please note, that you might have to recompile everything that depends on libelogind to support libseat instead (this should hopefully be slowly fixed by subsequent PRs once #24580 gets merged).

**Comment by ofiala-a51** [comment]
Also note, that the name `libsystemd` is for compatibility reasons. The package's name is `libelogind` and only contains the portions required to work w/ elogind.

**Comment by nonchip** [comment]
i see 3 issues with this issue:

* the `elogind` package doesn't actually depend on `systemd` at all
* github uses markdown, not bbcode, please use ``` instead of `[code]` and `[/code]`
* and nothing in that `post_install` function you're quoting actually introduces any dependency on systemd, the name is simply there for compatibility with software that expects there to be a systemd-logind under that name.

essentially the same as `libressl` installing `/usr/bin/openssl` as a compatibility wrapper. that doesn't mean it "depends on" `openssl`, on the contrary it allows other things to *not* depend on it. same applies here, due to the compatibility stuff installed by `elogind` we make it so we don't have to install systemd-logind but still support software that's "used to" that.
