### ISSUE TITLE
[GNOME] Nextcloud cannot remember login information

### ISSUE THREAD

**Issue by ProjectMoon** [void-linux/void-packages#26275]
See this: https://github.com/nextcloud/desktop/issues/1292

### Expected behavior

You should need to log in once on first run, then not log in again.

### Actual behavior

If libgnome-keyring is not installed, you will have to log in every time the program starts.

### Steps to reproduce the behavior

This may be specific to GNOME itself. Install libgnome-keyring makes the problem go away. Haven't checked it on other desktop environments. It seems to be fixed in the Nextcloud repository by updating to qtkeychain 0.10. Void is still on 0.9.1, so a patch is needed.

**Comment by yopito** [comment]
I confirm the bug, but with  `libgnome-keyring` that is already installed here (required by MATE).  
So I'll give a try with qtkeychain 0.10.

**Comment by yopito** [comment]
Some tests:
* nextcloud + qtkeychain-q5 0.9.1 + gnome-keyring  (not libgnome-keyring) : works fine
* nextcloud + qtkeychain-q5 0.9.1 or 0.11.1 + kwallet : does NOT work

BTW, `libgnome-keyring` is deprecated, see https://gitlab.gnome.org/GNOME/libgnome-keyring/blob/master/README

I have to check why qtkeychain-q5 currently does not work with kwallet.  
Then see what about these runtime requirements for nextcloud (INSTALL.msg or declarative)

**Comment by khumarahn** [comment]
I had this on gentoo linux, where libgnome-keyring has been deprecated. I got success with 
https://packages.gentoo.org/packages/dev-libs/qtkeychain but only if it is compiled with `gnome-keyring` use flag (which adds `-DLIBSECRET_SUPPORT=ON` option to cmake and a couple of dependencies).

**Comment by eth0OS** [comment]
I had this problem with XFCE too, it was fixed by installing libsecret + libsecret-devel.

**Comment by yopito** [comment]
@eth0OS : libsecret-devel is certainly useless. For libsecret, it's unclear at the moment

fix: qtkeychain-qt5 0.11 correctly detects and uses gnome-keyring if available (see PR #26497)

My State of art:
* To use nextcloud-client: please install either `gnome-keyring + libsecret` or `kwallet5` in order to provide a backend to `qtkeychain-qt5`.
* `libkeyring-gnome` is **useless**.
* qtkeychain-qt5 0.11 is working with both keystore backend here.

tip for force using kwallet if not running from KDE/Plasma:  
`$ DESKTOP_SESSION=kde KDE_SESSION_VERSION=5 nextcloud`
