### ISSUE TITLE
ratbagd starts too early?

### ISSUE THREAD

**Issue by sardior** [void-linux/void-packages#26430]
### System

* xuname:  
  Void 5.8.18_1 x86_64 AuthenticAMD uptodate rrrrmmnFFFFF
* package:  
  libratbag-0.14_1

### Expected behavior
After enabling the ratbagd service ratbagctl should automatically see the available devices.

### Actual behavior
When the service is started automatically by runit it seams to be running but `ratbagctl list` doesn't see any devices. If service is restarted manually with `sv down ratbagd && sv up ratbagd` then everything starts working. It looks to me like there is some unknown dependency so I tried adding a condition to the service run script to wait untill a tty login is active, but that didnt help either.

### Steps to reproduce the behavior
1. Enable ratbagd service
2. reboot
3. execute `ratbagctl list`

**Comment by ericonr** [comment]
I wonder if you could try waiting on `udevd`, assuming that's the issue...

**Comment by sardior** [comment]
Tried it just to be sure and it didn't work. In my understanding by the time I login all system services should be running so the tty condition would have worked. 

Also tried a condition to wait untill the x server is started as I use i3 and xinit is triggered post login and it might be some basic gui dependency but no luck.

Here is my run script so far:

```
#!/bin/sh
sv check dbus >/dev/null || exit 1

# Added conditions START
[[ ! xset q >/dev/null ]] || exit 1
sv check udevd >/dev/null || exit 1
[[ ! -z $(w | awk '/tty[0-9]+/ {print $1}') ]] && exit 1
# Added conditions END

exec ratbagd
```

**Comment by ahesford** [comment]
You probably don't even need to start the service. It should be activated by dbus. Make sure your `dbus` service is enabled and that you start your window manager wrapped by `dbus-run-session` to make sure you have a consistent user session.

If, for some reason, you really do need the daemon, your modifications to the run script have several issues. The `xset q` test is guaranteed to fail because the service script doesn't know what 'DISPLAY` to use. The udev check is effectively a no-op. (The `sv check` construct works for dbus because the dbus service defines a `check` script that properly defines conditions under which it may be considered "up". Most services, udev included, do not; in that case, `sv check` effectively tests whether the service is linked in `/var/service`, not whether it's running, and certainly not whether it's in a stable state.) The `w` check, if one user is logged in, may be ok, but will crash and burn with more than one logged-in user because you aren't quoting the subshell output.

**Comment by sardior** [comment]
I need the daemon because the MX master 3 mouse I'm using does not retain settings after poweroff, so after some research I constructed the following udev rule to remedy that when I turn on the mouse:
```
$ cat /etc/udev/rules.d/70-logitec-mouse.rules
ACTION=="change"\
, SUBSYSTEM=="power_supply"\
, ENV{POWER_SUPPLY_MODEL_NAME}=="Wireless Mouse MX Master 3"\
, ENV{POWER_SUPPLY_ONLINE}=="1"\
, ENV{POWER_SUPPLY_STATUS}=="Discharging"\
, RUN+="/usr/bin/su root -c 'ratbagctl Logitech\ MX\ Master\ 3000 dpi set 4000'"
```
However for ratbagctl to work I need the daemon properly running and seeing the device, e.g. `ratbagctl list ` outputting the device list :  `singing-gundi:       Logitech MX Master 3000` , which is not happening for some reason unless I restart the service manually.

I changed i3 startup in my xinit from `exec i3`  to  `exec dbus-run-session i3` but it didn't help in this case.

Also I know the conditions are bad, they aren't meant to stay there :D

**Comment by ericonr** [comment]
Could your udev rule instead restart the `ratbadg` service? Really ugly, but might just work

**Comment by sardior** [comment]
Didnt work. I experimented some more and came to the conclusion that it is not the service file, but I have no idea what might be the problem.

If I unlink the service and reload and trigger the udev rules with `udevadm control --reload-rules && udevadm trigger` the rule gets executed and `ratbagctl` starts working too. That makes me think that @ahesford was right about dbus activating the service when needed, but I don't see how that works without any configuration.

**Comment by sardior** [comment]
I'll close the ticket as it has nothing to do with the package.
If anyone runs into this problem, It seams that runinng `udevadm control --reload-rules && udevadm trigger` **after** the mouse is connected resolves everything untill the next reboot. I'll post an update if I find a complete solution.
