### ISSUE TITLE
ccache isn't working with xbps-src

### ISSUE THREAD

**Issue by Logarithmus** [void-linux/void-packages#26508]
I've added `XBPS_CCACHE=yes` to `etc/config`. After that, when I build packages, the files are written into `hostdir/ccache`. But for some strange reason they are not used during the recompilation of the same package. E. g. I've built chromium-86, now when I'm building chromium-87, the process isn't sped up at all. Also when I open `htop`, it shows `/usr/bin/clang++` and no `ccache` processes. How can I fix that?

**Comment by pullmoll** [comment]
1) You probably cannot expect a single hit between chromium-86 and chromium-87 because headers changed and a change in a central header (think `version.h`) prevents a cache hit.
2) You need to make sure to re-bootstrap your environment, i.e. do `./xbps-src zap` and `./xbps-src binary-bootstrap` again to make the `etc/conf` (not `etc/config` AFAICT) change take effect.
3) Any change in the compiler binary invalidates the entire current cache, because a checksum of the compiler binary (`/usr/bin/clang++` in this case) is used to make sure that compilation results will indeed be identical. So the update of llvm10 to llvm11 already invalidated all your existing cache entries. You can clean and zap it (`ccache -C` and `ccache -Z`) in such a case.

I have a separate 1TB SDD for ccache and currently have 653GiB of 768GiB used with a cache hit rate of 8.06%. I'm building literally tens of thousands of packages for all architectures and can confirm that `ccache` indeed works as it is supposed to.

**Comment by Logarithmus** [comment]
Thank you for the explanation! Unfortunately, my `ccache` hit rate is only 1.40% 😃
Anyway, that's better than 0.
