### ISSUE TITLE
Package request: wine-staging

### ISSUE THREAD

**Issue by FrostKnight** [void-linux/void-packages#27612]
https://github.com/wine-staging/wine-staging

Wondered if you could add it, I doubt I am the only one who has had interest in this.

**Comment by fosslinux** [comment]
I don't believe this is a good idea. We generally don't package beta software and I don't see why wine should be an exception.

**Comment by FrostKnight** [comment]
Hmm,  it works well for me though on other operating systems, I don't think it is beta quality...
I don't see why you couldn't just put a warning on it when you go to install it and have it included that way.   That being said, I don't see any issue myself.

**Comment by aeadio** [comment]
I'm interested in this as well. While Void's policy against beta software is downright sane, Wine is one of those cases where the -staging patchset is often recommended to work around bugs and edge cases because of how Wine has to constantly track a moving target of shifting software behavior and patching for new releases. Considering a large portion of the use case for Wine is running very new versions of software or games, it's pretty much de facto to use -staging by default. Everyone using Wine expects buggy behavior -- it's not a perfect implementation. 

In this case, would it be reasonable to provide -staging as a **non-default** build option? 

I've begun working up a template along those lines and it seems to be fairly trivial to do.

**Comment by ericonr** [comment]
@aeadio do you mean a build option to conditionally apply the patchset relative to the release currently being used?

@Hoshpak has been tracking the wine releases quite a bit, so it might be necessary to wait a bit for the wine-staging release to become available as well. But besides that, it sounds reasonable to me.

**Comment by aeadio** [comment]
> @aeadio do you mean a build option to conditionally apply the patchset relative to the release currently being used?

Yes. Wine-staging is already available for the rc5 version Void is building. I have a template that seems to build and function, and I'm working on building/testing for other archs as well before submitting a PR.
