### ISSUE TITLE
[RFC] signed kernel modules

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#27736]
While trying to build Arch Linux kernel in Void using `xbps-src`, I noticed they use kernel module signature, see e.g. `CONFIG_MODULE_SIG=y` in their [config](https://github.com/archlinux/svntogit-packages/blob/packages/linux/trunk/config), while Void does not, see also Arch wiki [page](https://wiki.archlinux.org/index.php/Signed_kernel_modules).

While this is not an issue, I wonder whether it would be useful to have this feature in Void Linux kernel as well.

**Comment by ericonr** [comment]
I don't see what advantage this brings, since an attacker who has access to the kernel modules could just as well change programs, libraries, or possibly even the kernel itself, making any signing moot.

Furthermore, given that a lot of people might end up requiring one DKMS module or another (nvidia, zfs, ...), this would only be useful if they self built their own kernel with a custom config pointing to the additional key. And then they'd have to set up the whole infrastructure around actually signing the modules and such, plus somehow protect the key adequately.

**Comment by ahesford** [comment]
DKMS is a fundamental part of the distribution of out-of-tree kernel modules in Void. As @ericonr notes, the fact that the kernel must be built to include public counterparts of all keys used to sign modules either forces us to distribute the private keys (which defeats the whole purpose of signing) or to shift the burden of custom compilation from those who want signed modules to those (almost certainly far greater in number) who use out-of-tree modules.

This seems like a bad trade.

**Comment by fosslinux** [comment]
Furthermore, we can't distribute many of these these even if we did build and sign them.

**Comment by dkwo** [comment]
I see, thanks for clarifying.
