### ISSUE TITLE
spotify: SHA256 of EULA mismatching

### ISSUE THREAD

**Issue by waynevanson** [void-linux/void-packages#27998]
### System

* xuname:  
  Void 5.9.16_1 x86_64 GenuineIntel uptodate rrFFFFFFF
* package:  
 spotify-1.1.42_2

### Expected behavior

Installing package works without any errors.

### Actual behavior

`post_extract()` calls `message_error()` because the checksum of Spotify's EULA does not match the current.

```bash
post_extract() {
	curl -L https://www.spotify.com/us/legal/end-user-agreement/ |
		w3m -dump -I utf-8 -T text/html |
		sed -n '/Spotify Terms and Conditions of Use/,/^USA$/p' > EULA

	filesum="$(xbps-digest EULA)"
	if [ "$filesum" != "$_license_checksum" ]; then
		msg_error "SHA256 mismatch for EULA:\n$filesum\n"
	fi
}
```

### Steps to reproduce the behavior

- enable restricted packages
- `./xbps-src pkg spotify` in `void-packages/`

### Questions

@teh-jazzman What is the reason behind checking the EULA and throwing an error?

**Comment by teh-jazzman** [comment]
There was a discussion at #23576, which I missed, so I can't tell you. Maybe @ericonr can explain?

I assume it is to ensure that the downloaded license file is indeed a valid license and not, for example, a 404 error message or something like that. I assume since the package can be semi-automatically updated via void mechanisms it is necessary to provide a valid and up-to-date license file. Or it is to prevent the package from installing when there _might_ be something in the license that forbids that.

**Comment by ericonr** [comment]
> Or it is to prevent the package from installing when there might be something in the license that forbids that.

Basically that. If the license changes, it should be acknowledged and the template should be fixed.

**Comment by ericonr** [comment]
A PR to fix that should be pretty simple. To allow for easier visualization, include the license text in the PR so we can check it out.

**Comment by Chocimier** [comment]
closed by #28022

**Comment by Animeshz** [comment]
License is changed again I guess?

**Comment by teh-jazzman** [comment]
Yes, there have been substantial changes. I created #33439 but have not checked the new EULA for viability.
