### ISSUE TITLE
Building DKMS module: virtualbox-ose-guest-6.1.16... FAILED! for linux5.10-5.10.8_1

### ISSUE THREAD

**Issue by rapha8l** [void-linux/void-packages#28005]
### System

* xuname:  
Void 5.9.16_1 x86_64 GenuineIntel uptodate rrrmFFFF

 * package:  
linux 5.10
### Actual behavior
Building DKMS module: virtualbox-ose-guest-6.1.16... FAILED! 

[make.log](https://github.com/void-linux/void-packages/files/5829620/make.log)

**Comment by ericonr** [comment]
There hasn't been a new VirtualBox release, and the bug is known on their end https://www.virtualbox.org/ticket/20055

Since they don't track linux releases, there isn't really much we can do. You should stick with older kernels or switch to qemu/kvm. Once they have proper patches for this, someone might try backporting them.

**Comment by rapha8l** [comment]
thanks, it's often the case with virtualbox

**Comment by ericonr** [comment]
Related https://github.com/void-linux/void-packages/commit/37513f740b1d039a8d16bd02ce06817760e68f70
