### ISSUE TITLE
gnome shell screencast not working

### ISSUE THREAD

**Issue by maop** [void-linux/void-packages#28987]
### System

* xuname:  
      Void 5.10.17_1 x86_64 AuthenticAMD notuptodate rrFFF

* package:  
      gnome-shell-3.38.3_1

### Expected behavior
When Ctrl-Alt-Shift-r pressed starts recording and video is saved in $HOME/Videos or $HOME

### Actual behavior
Nothing happens.

With `dbus-monitor` i can see the error:

```
method call time=1614027327.526214 sender=:1.38 -> destination=org.gnome.Shell.Screencast serial=68 path=/org/gnome/Shell/Screencast; interface=org.gnome.Shell.Screencast; member=Screencast
   string "Captura del escritorio de %d %t.webm"
   array [
   ]
error time=1614027327.526281 sender=org.freedesktop.DBus -> destination=:1.38 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=68
   string "The name org.gnome.Shell.Screencast was not provided by any .service files"
```

I confirmed there is not /usr/share/dbus-1/services/org.gnome.Shell.Screencast

I've searched for solutions and installed all possible dependencies that may be missing, tried reinstalling, etc... but then i found this bug from openSuSE: https://build.opensuse.org/request/show/859147, is this happening with voidlinux too? or i missed something in the installation? 

Thanks for your time. 

### Steps to reproduce the behavior

Press ctrl-alt-shift-r in a gnome desktop installation.

**Comment by ericonr** [comment]
@maop could you please test #29019 ?

**Comment by maop** [comment]
Ok, this has been a real rabbit hole for a newbie like me (:

So... i edited `srcpkgs/gnome-shell/template` and made the changes like your PR, then `./xbps-src pkg gnome-shell` and then installed `3.38.3_2` and restarted.
Now /usr/share/dbus-1/services/org.gnome.Shell.Screencast.service exists, and with `dbus-monitor` i see A LOT of errors when i press the shortcut to activate the Screencast, some of them are about Mutter

```
method call time=1614145390.381364 sender=:1.71 -> destination=:1.13 serial=37 path=/org/gnome/Mutter/ScreenCast/Session
/u1; interface=org.gnome.Mutter.ScreenCast.Session; member=Start
error time=1614145390.393059 sender=:1.13 -> destination=:1.71 error_name=org.freedesktop.DBus.Error.Failed reply_serial
=37
   string "Failed to start screen cast: Couldn't connect pipewire context"

```
So i began to think, maybe we need to build mutter with pipewire too? Looking for something mutter-related i found this enlightening comment: https://gitlab.gnome.org/GNOME/mutter/-/issues/79#note_84029

Ofc i needed to install pipewire. Ran it in a terminal `$ pipewire` , then pressed the shorcut et voilá ! it started recording correctly and video file was in $HOME/Videos, awesome!

As pipewire is still unstable, and (correct me if i'm wrong) not yet supported by voidlinux, i'd say gnome screencasting is currently broken? unless there is another workaround?

Let me know if i can help with something more.

Best regards!

**Comment by ericonr** [comment]
> Ofc i needed to install pipewire. Ran it in a terminal $ pipewire , then pressed the shorcut et voilá ! it started recording correctly and video file was in $HOME/Videos, awesome!

Great!

> As pipewire is still unstable, and (correct me if i'm wrong) not yet supported by voidlinux, i'd say gnome screencasting is currently broken? unless there is another workaround?

Well, it is a package we ship and constantly update. The main issue it has is that unlike Pulseaudio, it isn't automatically started, so one has to launch it manually or somehow create a user service for it, which are complicated to do as a general solution. So in a way, a seamless pipewire experience is unsupported.

Since the rest of GNOME shell works without pipewire, and using pipewire requires manual work either way, I don't think `gnome-shell` should depend directly on it. Maybe upstream can improve their error messages to let you know things are going wrong without having to use `dbus-monitor`.

But screen casting works once you have pipewire installed and launched, which is the correct way of using pipewire, so I wouldn't say it's broken in any way.

I will merge my PR for now, since it enables the screen cast functionality to work at all, and that will close this issue. If you think we can improve matters further, feel free to reopen or open another one (maybe we need to add pipewire documentation to Void, and maybe mention that GNOME screen cast requires it - you can open an issue in the void-docs repository for this).

Thanks for testing and for bringing the solution :)

**Comment by scorpi11** [comment]
I created a gnome shell extension that applies a GLSL shader to the whole desktop. When moving windows, I get distorted lines at the outer edge of the window shadows. Is this the same issue?
