### ISSUE TITLE
Package Request: linux-pf

### ISSUE THREAD

**Issue by whoizit** [void-linux/void-packages#2939]
I super like Void, but It's only reason why I want to move back in Arch
I can't maintain it, cause it's too hard for me, but I realy need it.

It's ultimate kernel for low memory desktops. I have a 6Gb (4+2) RAM. 
UKSM it's killer feature. 
PDS it's the most modern desktop CPU scheduler

In Arch it's have even TWO binary repos. I prefer Theodan fork. I think it's have a differents in kernel configs... 
CONFIG_HZ_100=y in post-factum
https://build.opensuse.org/package/show/home:post-factum:kernels/linux-pf-generic
CONFIG_HZ_1000=y in Thaodan
https://gitlab.com/Thaodan/linux-pf

https://wiki.archlinux.org/index.php/Kernel#Major_patchsets
https://gitlab.com/post-factum/pf-kernel/wikis/README
https://github.com/pfactum/pf-kernel/compare/v4.18...v4.18-pf6.diff

**Comment by Hoshpak** [comment]
This made me laugh. Since when is 6GB considered "low memory"? If you were using an embedded system with 256MB or maybe 512MB soldered onto the board I would understand that categorization. My Void LXQt desktop usually runs with less than 2GB RAM usage unless I start some memory-intensive application and that includes a Chromium fork with several tabs opened.

But to get onto the serious side of things again: Like with other packages in the repository, I don't think we reasonably could or should support several patched versions of the same package. A full kernel build takes several hours on the builders and there already are a lot of different vanilla kernel versions in the repository.

**Comment by whoamin** [comment]
I do not think that your tone of conversation is relevant, especially if you are a member of the Void Linux community.

In your case, this kernel makes even more sense.

You say that you are limited to github cloud resources. Perhaps this is an occasion to reflect on your own build server

**Comment by Vaelatern** [comment]
@whoamin, please explain why an additional kernel is of interest to Void.
Also, please confirm that you think @Hoshpak was talking about github cloud resources. Please do not put words in our mouths.

**Comment by whoamin** [comment]
UKSM:
https://asciinema.org/a/b8cuKeUnu7GgnpbP8zpQiXZWr

- I turned off the UKSM
`echo 0 > /sys/kernel/mm/uksm/run`
- I closed all open programs
- I've run many different programs to fill my memory.
- I turned on the UKSM at 5 seconds.
`echo 1 > /sys/kernel/mm/uksm/run`

For 3 minutes UKSM deduplicated 1GB of memory.
So, infact with UKSM I have like 6 + 1-1.5 GB memory. And I say, it's ultimate kernel for low memory systems

https://github.com/dolohow/uksm#reference

**Comment by Vaelatern** [comment]
In that case, I look forward to that feature being upstreamed to the mainline kernel.

**Comment by whoamin** [comment]
vanilla kernel already have shitty KSM feature

**Comment by maxice8** [comment]
Sorry but we do not support Linux patchsets.
