### ISSUE TITLE
[Request] Firefox didn't have crash detection (about:crashes does not exist), possibly because Mozilla Crash Reporter is not included in the installer ? 

### ISSUE THREAD

**Issue by thegarlynch** [void-linux/void-packages#29872]
### System

* xuname:  
  Void 5.10.24_1 x86_64-musl GenuineIntel notuptodate rrnFFF
* package:  
  firefox

### Expected behavior

about:crashes exists

### Actual behavior

about:crashes doesn't exists

### Steps to reproduce the behavior

about:crashes

**Comment by ericonr** [comment]
This is by design, due, afaik, to portability concerns with the crash reporter implementations. We might be able to enable it with the next Firefox version for x86_64, but I don't know if others will agree. I also don't know how useful the crash reporter even is with the stripped binaries contained in our packages.

**Comment by thegarlynch** [comment]
As far as i know, the only method for firefox to log the crash is by using crash reporter. Otherwise there will be nothing in both /var/log and ~/.mozilla/CrashReport. Whether or not firefox will send it, is just optional

**Comment by Duncaen** [comment]
Enabling core dumps is the standard way to "log crashes" of all programs.

**Comment by Duncaen** [comment]
Our builds are not blessed by mozilla, sending them crashes or bug reports is not an option at all.

**Comment by ericonr** [comment]
Ok, I wasn't aware of that.
