### ISSUE TITLE
Linux kernel version of armv6l and armv7l stay at v5.5

### ISSUE THREAD

**Issue by ruantu** [void-linux/void-packages#30205]
Linux kernel version of armv6l and armv7l stay at v5.5, and version after v5.6 do not create arm-dotconfig.

**Comment by ericonr** [comment]
What's your platform of interest for using these kernels?

**Comment by ruantu** [comment]
allwinner and nxp SBCs, i want to know if there is a plan to give up arm support?

**Comment by ericonr** [comment]
There isn't, no. `armv6l` maybe shows its age in a lot of places, but it's also a valuable target due to the RPi Zero. `armv7l` is still sufficiently modern and people may need 32-bit on aarch64 devices that support it.

The issue with `armv*` kernels is that very few platforms actually work with the generic kernel, so it isn't of much value to provide one, even. If you're interested in using those platforms with Void and they work with a modern generic kernel, you can probably base the config off of `linux5.4` (which has `arm-dotconfig`) and we'll merge it in and keep it up to date with kernel updates; but I'm not going to add this support to `linux5.11` myself, my rpi uses `rpi-kernel` just fine.

All that said, it should be perfectly possible to install `linux5.4` directly and use that, though it is admittedly more fiddly than just using the `linux` package directly.

**Comment by ruantu** [comment]
I observed that the armv7l target lacking linux 5.10 has a lot of failed package builds.
For example nodejs: https://build.voidlinux.org/builders/armv7l_builder/builds/31532/steps/shell_3/logs/stdio

**Comment by ericonr** [comment]
```
   [runtime] nodejs-14.16.0_1: not found
=> ERROR: nodejs-14.16.0_1: cannot be cross compiled, exiting...
=> ERROR: nodejs-14.16.0_1: host and target must have the same pointer size
```

Where do you figure `linux5.10` fits here?

But yes, there are some packages which depend on `linux-headers`, which blocks us from building them for `arm*`. I think that should probably be fixed.

**Comment by classabbyamp** [comment]
probably not going to happen unless raspberry pi goes mainline
