### ISSUE TITLE
texdoc doesn't work / texlive documentation missing

### ISSUE THREAD

**Issue by tornaria** [void-linux/void-packages#30340]
This used to work (with `texlive-bin`):
```
$ texdoc enumitem
[... opens /opt/texlive/2020/texmf-dist/doc/latex/enumitem/enumitem.pdf ...]
```

With the new packaged `texlive`:
```
$ texdoc enumitem
texdoc error: No texlive.tlpdb nor shipped tlpdb data found.
$ xlocate enumitem.pdf
$
```

That is, `texdoc` seems to be broken, and the corresponding documentation can't be found anywhere.

**Comment by ericonr** [comment]
It would seem this is related to #24013

We don't have a `texlive.tlpdb` file, unfortunately. I wonder if it's necessary for finding the docs? If yes, we should consider trying to generate it based on installed `texlive-*` packages (I have a feeling this isn't possible, but it would be nice)... Otherwise, it could be made to look at `~/texmf/tlpkg` for the db, but that doesn't seem ideal - opening docs shouldn't require so much setup.

@fosslinux

**Comment by fosslinux** [comment]
I will investigate this. It should be possible to generate these without tlpdb.

**Comment by scheckley** [comment]
still failing for texlive 20210325-1 

```
Can't locate TeXLive/TLConfig.pm in @INC (you may need to install the TeXLive::TLConfig module) (@INC contains: /texmf-dist/scripts/texlive /tlpkg /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /usr/share/texmf-dist/scripts/texlive/tlmgr.pl line 60.
BEGIN failed--compilation aborted at /usr/share/texmf-dist/scripts/texlive/tlmgr.pl line 60.
```
