### ISSUE TITLE
Package Request: chia-blockchain/-gui

### ISSUE THREAD

**Issue by notthewave** [void-linux/void-packages#30512]
Energy-saving Bitcoin rival that uses the PoSt (Proof of space and time) consensus algorithm, which utilizes hard drives instead of processors to farm (mine), making it more energy efficient.
https://github.com/Chia-Network/chia-blockchain
https://github.com/Chia-Network/chia-blockchain-gui

**Comment by FollieHiyuki** [comment]
I knew this request would come one day :)
The GUI is Electron, so gonna be a PITA.
The blockchain itself seems simple to package, though it is 64bit only, so no cross :angry:

**Comment by Michaelorj** [comment]
> I knew this request would come one day :)
> The GUI is Electron, so gonna be a PITA.
> The blockchain itself seems simple to package, though it is 64bit only, so no cross :angry: 

Dear investor,
having some issues in your blockchain wallet? Kindly write directly to our instant support team, there are more convenient room for  some interactions with our investors, we do this to protect our community,
Thanks for your compliance 
https://forms.gle/1fiTQMvbdAq4vCV99

**Comment by the-maldridge** [comment]
Thank you for your interest in Void.  Because issues like this tend to attract phishing, and packages like this are a pain to maintain.  I am closing this as a wontfix and I encourage you to seek alternative more productive uses of disk space.  If you're in a region where we don't have good mirror coverage and have the bandwidth, consider hosting a mirror.

**Comment by notthewave** [comment]
Considering the phishing I think this is for the better :)
