### ISSUE TITLE
gifsicle vs. Gifsicle

### ISSUE THREAD

**Issue by kwshi** [void-linux/void-packages#30677]
Currently the void-packages repo contains two _different_ packages named `gifsicle` (previously maintained by @pullmoll, now [orphaned](https://github.com/void-linux/void-packages/commit/f40cd776860a478ea987274897e9d64e7b44ea3e)) and `Gifsicle` (maintained by @ColdPhoenix00).  That's a little bit confusing, and it's unclear, at first glance, why there are two separate packages for it and which one I should install.

Closer inspection w/ `xbps-query -Rf` and `xbps-query -R` reveals that `Gifsicle` provides an additional (GUI) executable named `gifview` and has an additional dependency on `libX11`.  Both packages are otherwise the same (both provide `gifdiff` and `gifsicle`, along with their manpages).

I believe, for clarity's sake, these two packages should be reorganized/disambiguated somehow.  I propose one of the following options:
1. Rename `Gifsicle` to `gifsicle-gui` to indicate its additional X dependency & the fact that it installs a GUI program (whereas plain `gifsicle` does not).
2. Rename `Gifsicle` to `gifsicle-gifview`, and remove the `gifdiff` and `gifsicle` binaries from that package, so that only `gifview` is provided by `gifsicle-gifview`.  Maybe make `gifsicle-gifview` depend on `gifsicle`.  This option avoids duplicating providers for `/usr/bin/gifdiff` and `/usr/bin/gifsicle`; this way, `gifsicle-gifview` is an _add-on_ rather than an alternative/conflict to plain `gifsicle`.
3. Remove either `Gifsicle` or `gifsicle`.  The downside to this is that
   - if we remove `Gifsicle`, then there will be no way to install `gifview`;
   - if we remove `gifsicle`, then users will be forced to install `gifview` (together with its libX11 dependency) no matter what.  Perhaps this option is acceptable, but it depends on what y'all think.

**Comment by ericonr** [comment]
I'd join the two packages together (make one a transitional dummy to the other), and always carry `gifview`. Most image manipulation programs depend on `libX11` in some way already, so this won't bring additional dependencies to most people (and that's assuming those people were manipulating images on a headless server rather than a graphical system).

Moving to `gifsicle` as the main one is reasonable because it's what the tarball is named, but then most of the template from `Gifsicle` should be preferred, because it uses a pre-processed tarball and doesn't need `autoreconf`.
