### ISSUE TITLE
[Request] Distribute zfs module as package

### ISSUE THREAD

**Issue by Ypnose** [void-linux/void-packages#31629]
Hey there,
Building zfs module with DKMS can take a while on older computers. Do you think it might be possible to distribute it as a package ?

**Comment by Vaelatern** [comment]
It's of debatable legality. There is in fact a lively debate about it.

**Comment by Ypnose** [comment]
Even though the situation is somewhat different on Ubuntu (default kernels directly ship zfs module), have you seen this [article](https://ubuntu.com/blog/zfs-licensing-and-linux) ? The full report can be also read [here](https://softwarefreedom.org/resources/2016/linux-kernel-cddl.html).

**Comment by Ypnose** [comment]
Is there any followup ? I forgot to mention Proxmox VE and NixOS when I created that issue. They include the module directly in the kernels. It So far, nobody complained. What I'm requesting is the module as a downloadable package, which is much less intrusive.

**Comment by q66** [comment]
we generally don't distribute dkms-using stuff as binary modules, and i don't see any way to do that anyway considering the number of kernels and variants void ships

if your computer is unbearably slow at building zfs, you probably shouldn't be using zfs on it anyway

**Comment by Ypnose** [comment]
I knew you would come with that conclusion regarding not using zfs on slower machines, especially from you. I am currently failing to see how it's related.

**Comment by ahesford** [comment]
I'm a heavy proponent of ZFS and have a stake in keeping first-class support in Void, but this isn't the answer. Any potential license issues aside, this is a bad idea because:
1. Void isn't set up to have module packages track the kernels directly. We use DKMS because we can't provide installable modules for whatever kernel version you might be running, because our kernel package may have already left you behind.
2. The workaround would be to build ZFS within the kernel package so that each package has the modules you need. However:
* This admits the possibility that ZFS kmods and user land tools get out of sync, which could eventually be catastrophic.
* This adds maintenance burden to the kernel packages, which are complicated enough already.
* This would require we rebuild all kernels for every ZFS bump or else live with out-of-sync kernel and user space components from the outset; both are unattractive.
* Pulling ZFS into the kernel package leads to "what-about" arguments where people start fighting about why their preferred kernel module isn't also precompiled.

I would love binary ZFS modules, especially when I make the mistake of updating the ZFS package without first vkpurging; watching ZFS build 6 times for kernels I want to throw away anyway is painful. Unfortunately, we aren't set up for this.

**Comment by Ypnose** [comment]
Thanks for your message @ahesford !
