### ISSUE TITLE
Package Request - OpenJFX

### ISSUE THREAD

**Issue by anarchomoh** [void-linux/void-packages#3197]
Hi
Could I please request OpenJFX to be packaged for Void?
The Github source code link is: https://github.com/javafxports/openjdk-jfx/archive/11+26.tar.gz
The website is at: https://wiki.openjdk.java.net/display/OpenJFX/Main
Thanks.

**Comment by cr6git** [comment]
Hi,
I guess it is for bisq? https://github.com/void-linux/void-packages/issues/2560

**Comment by anarchomoh** [comment]
Hi, yes please.

**Comment by Cogitri** [comment]
It's also required for some other Java projects such as GeoGebra

**Comment by RoundDuckKira** [comment]
I tried to look for OpenJFX and encountered this too.

I'm gonna try to bring attention to it, or if all else fails I may attempt packaging it myself as I did make 2 packages for Void already, and one still waiting for approval

**Comment by RoundDuckKira** [comment]
@pullmoll @Vaelatern So what should I do about this situation, should you guys package it, or should I have a go at it with your help? You two have experience on how to package OpenJDK so it'd be nice if one of you two worked on OpenJFX, or if I have time you two can help me build the package myself. I'm just scared since OpenJDK looks so complicated in its template :sweat_smile:

**Comment by Vaelatern** [comment]
Go for it. Feel free to ping me when you get anything.

**Comment by Vaelatern** [comment]
https://github.com/openjdk/jfx

**Comment by chilledfrogs** [comment]
Any news on this? Found another Java program which I unfortunately might need soon which requires *any* implementation of JavaFX... I looked at the build instructions, I can try to make it work, but can't guarantee anything

**Comment by illusioon** [comment]
Any news on this? I have some programs which need this implementation .
