### ISSUE TITLE
Package request: cuda

### ISSUE THREAD

**Issue by lastrodamo** [void-linux/void-packages#31984]
I would like to request the cuda package (The latest release is 11.4.0-1) which is a dependencies for blender 2.93.0

Thank you.

**Comment by xslendix** [comment]
This is also useful when doing heavy floating point computations, such as training AI

**Comment by bobertlo** [comment]
To my surprise, CUDA is included with the proprietary NVIDIA packages.

```
nvidia-libs-470.94_1	/usr/lib/libcuda.so -> /usr/lib/libcuda.so.470.94
nvidia-libs-470.94_1	/usr/lib/libcuda.so.1 -> /usr/lib/libcuda.so.470.94
nvidia-libs-470.94_1	/usr/lib/libcuda.so.470.94
```

I was able to install pytorch, `torch.cuda.is_available()` returns true, and the mnist example trains a model.

This issue could be closed but I view this as a documentation issue since there is absolutely no mention of cuda in any package descriptions or documentation. If you google cuda void linux you find multiple open package requests and reports that cuda is not available or supported.

**Comment by cl3m3c7** [comment]
what is the status of the request please? :)

**Comment by bobertlo** [comment]
Nobody seemed to care so I think it is a RTFM from the maintainers.

**Comment by cl3m3c7** [comment]
😭 

thank you :)

**Comment by classabbyamp** [comment]
#20077
