### ISSUE TITLE
upgrading blueman & docker fails "Directory not empty"

### ISSUE THREAD

**Issue by linde12** [void-linux/void-packages#33815]
I'm having multiple weird issues today. First of all blueman-manager stopped working (all of a sudden i was missing dependencies like `gi` and `cairo`) so i thought i'd reinstall after an upgrade. What i did was:

```sh
xbps-remove blueman
xbps-install -Syu
```

After this it would start updaing packages but get stuck at the following:
```
bluez-5.61_1: updating to 5.62_2 ...
bluez-5.62_2: unpacking ...
ERROR: bluez-5.62_2: [unpack] failed to extract file `./etc/sv/bluetoothd/log/supervise': Directory not empty
ERROR: bluez-5.62_2: [unpack] failed to extract files: Directory not empty
ERROR: bluez-5.62_2: [unpack] failed to unpack files from archive: Directory not empty
Transaction failed! see above for errors.
```

I thought that was a weird error because obviously that directory is not empty because i still have bluez installed. However i uninstalled bluez as well because i did not want to spend any more time on this, but now i am getting a similar error from the `moby` package which is telling me that `/etc/sv/docker/log/supervise` also isn't empty which, again, it obviously isn't since i've installed docker previously.

```
moby-20.10.6_1: updating to 20.10.9_2 ...
moby-20.10.9_2: unpacking ...
ERROR: moby-20.10.9_2: [unpack] failed to extract file `./etc/sv/docker/log/supervise': Directory not empty
ERROR: moby-20.10.9_2: [unpack] failed to extract files: Directory not empty
ERROR: moby-20.10.9_2: [unpack] failed to unpack files from archive: Directory not empty
Transaction failed! see above for errors.
```

I'm wondering if anyone can help me shed some light on this. Blueman stopped working overnight and now i'm getting all these errors so i've got no idea whats going on.

### System

* xuname:  
Certificate verification failed for /C=US/O=Internet Security Research Group/CN=ISRG Root X1
SSL_connect returned 1
Certificate verification failed for /C=US/O=Internet Security Research Group/CN=ISRG Root X1
SSL_connect returned 1
Void 5.13.19_1 x86_64 GenuineIntel uptodate rFFF
* package:  
  moby-20.10.6_2, bluez-5.62_2

### Expected behavior
blueman to not break out of nowhere & `xbps-install -Syu` to work.
### Actual behavior
`xbps-install -Syu` fails when upgrading previously installed packages related to services such as dockerd & bluetoothd

**Comment by jchook** [comment]
How does XBPS update other running services without this error?

Why does this one have trouble updating?

**Comment by Duncaen** [comment]
In normal cases the supervise "directory" is actually a symlink pointing to something like `/run/runit/supervise.$service`, this is something we do in void and it avoids runit writing temporary stuff to the filesystem of `/etc`.

What happened to some services was due to a bug in `xbps-src` this symlink was not created for the log services whose run file was a symlink to something, in this case `vlogger`.
This bug was fixed and those packages now contain this symlink. But since they did not previously and runit created the supervise directory, which also was not tracked by xbps we run into this problem.
xbps does not recursively delete previously untracked files, so because this directory is untracked and contains files, manual intervention is required once, once for those 12 services iirc.

**Comment by jchook** [comment]
Brilliant, thanks a lot for the explanation.
