### ISSUE TITLE
lightdm Xsession: is xrdb "-nocpp" option necessary?

### ISSUE THREAD

**Issue by reedts** [void-linux/void-packages#33876]
While investigating some strange problems on xsession startup using lightdm + i3, I found this line in `/etc/lightdm/Xsession` and was wondering whether the `-nocpp` option is used here for a specific reason: [see here](https://github.com/void-linux/void-packages/blob/a279abf769ef7cab6ebb49d8c99bf774a2ff97b8/srcpkgs/lightdm/files/xsession#L19)

As an example from the archlinux package sources for lightdm: they're omitting the `-nocpp` option (see [here](https://github.com/archlinux/svntogit-packages/blob/8d85fa6b8d07e4a82b24efc7635853110c2f93ed/trunk/Xsession#L19))

Furthermore, having a look at xrdb's source code, you can see [here](https://gitlab.freedesktop.org/xorg/app/xrdb/-/blob/master/xrdb.c#L917) that xrdb should correctly check for the existence of the default cpp preprocessor (`/usr/lib/cpp`) and automatically disables preprocessing of `.Xresources` if the binary cannot be found.

So, in my opinion it should be safe omitting `-noccp` in the global `/etc/lightdm/Xsession` script and would simultaneously allow the user to have their `.Xresources` preprocessed on session-startup if a preprocessor can be found.

**Comment by mtboehlke** [comment]
I am not sure of the reason why `-nocpp` is included, perhaps to avoid the overhead of calling a pre-processor at all. The way we package xrdb, it falls back to mcpp when another cpp is not available, since mcpp is installed as a dependency.  The overhead, though, should be pretty minimal.

I don't see why we can't just omit the `-nocpp`.  That way if a user wants pre-processor macros, they can avoid having to rerun xrdb, and avoid the possibility of having their Xresources parsed incorrectly the first time around.
