### ISSUE TITLE
android-file-transfer-linux-4.2_2: Android File Transfer for Linux Is Broken

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#34321]
### System

* xuname:  `Void 5.15.5_1 x86_64 AuthenticAMD uptodate rF`
* package:  *affected package(s) including the version*: ``android-file-transfer-linux-4.2_2``

### Expected behavior
Running `android-file-transfer` should open up the GUI application.

### Actual behavior
The application doesn't start. All I see in the terminal is the following:
```
[fkoap@fkoap ~]$ android-file-transfer
upload worker started
current text color value:  0 , guessed theme:  "light"
scan
probing device...
probing device...
probing device...
probing device...
probing device...
[fkoap@fkoap ~]$
```
### Steps to reproduce the behavior
* Run `sudo xbps-install -u android-file-transfer-linux`
* Run `android-file-transfer`

**Comment by Animeshz** [comment]
+1 I'm facing the same issue, it does not open anything but exits with code 1.

**Comment by Animeshz** [comment]
The old 4.0 at 50518ee178b1d63c6d760d4d2ef1e043f2be2d71 is working fine, the only change is in version and checksum after that, seems like the problem is at upstream, `probing device...` is being printed more than expected times, and also `aft-mtp-cli` says `device not found (filter = ''` (some broken text).

**Comment by Animeshz** [comment]
Um, seems like it was not a bug, but rather not mentioned that it needs superuser access, see https://github.com/whoozle/android-file-transfer-linux/issues/290#issuecomment-984749769.

**Comment by fkoap** [comment]
I previously installed `android-file-transfer` on Fedora. It did not require any additional privileges to run.

Anyway, running a graphical application as `root` is not the best thing in the world. We should find a way to work around this.

**Comment by fkoap** [comment]
@Animeshz Were you able to get `gvfs-mtp` to integrate with a file manager like `Thunar`?

**Comment by Animeshz** [comment]
> I previously installed `android-file-transfer` on Fedora. It did not require any additional privileges to run.
> 
> Anyway, running a graphical application as `root` is not the best thing in the world. We should find a way to work around this.

There is a workaround https://github.com/whoozle/android-file-transfer-linux/blob/master/FAQ.md#no-mtp-device-found-but-its-listed-in-lsusb, but I guess since mounting any dev-block needs sudo rights, it is viable to have this on MTPs as well, anybody should not be permitted to write/read from/to the device (just my opinion).

**Comment by fkoap** [comment]
When you plug in a USB and open up a graphical file manager, are you prompted to enter your admin password just to mount it? No, right? I think `polkit` allows certain applications to access peripherals like USB sticks (or MTP devices). I do not know enough about it, but I'm sure there's a sane workaround instead of running a graphical application as `root`.

**Comment by austinrojers** [comment]
I have just installed _mtpfs_, and all my android file transfers through USB works fine
