### ISSUE TITLE
alacritty-terminfo fails script, because ncurses is not installed

### ISSUE THREAD

**Issue by hasufell** [void-linux/void-packages#34392]
In an empty docker container, I install `bash` and `alacritty-terminfo`, but the latter seems to fail part of the install stage, suggesting dependencies are not correctly declared for this subpackage.

```
# xbps-install alacritty-terminfo

Name               Action    Version           New version            Download size
alacritty-terminfo install   -                 0.9.0_1                3281B

Size to download:              3793B
Size required on disk:         4930B
Space available on disk:       194GB

Do you want to continue? [Y/n]

[*] Downloading packages
alacritty-terminfo-0.9.0_1.x86_64.xbps.sig: 512B [avg rate: 18MB/s]
alacritty-terminfo-0.9.0_1.x86_64.xbps: 3281B [avg rate: 112MB/s]
alacritty-terminfo-0.9.0_1: verifying RSA signature...

[*] Collecting package files
alacritty-terminfo-0.9.0_1: collecting files...

[*] Unpacking packages
alacritty-terminfo-0.9.0_1: unpacking ...

[*] Configuring unpacked packages
alacritty-terminfo-0.9.0_1: configuring ...
/tmp/.xbps-script-DuhzIC: 34: tic: not found
alacritty-terminfo-0.9.0_1: installed successfully.

1 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.
```

### System

voidlinux/voidlinux docker image c26f06f5f5c5

### Expected behavior

Installation and scripts succeed, pulling in `ncurses` as a dependency.

### Actual behavior

Installation succeeds, script fails, ncurses needs to be installed afterwards and then alacritty-terminfo force-reinstalled.

### Steps to reproduce the behavior

1. `docker run -ti --rm voidlinux/voidlinux sh`
2. `xbps-install bash alacritty-terminfo`

**Comment by erwin** [comment]
When I run `toe -a` I'm getting:

```
toe -a >/dev/null
toe: couldn't open terminfo file alacritty.info.
```

Because of the file:

```
/usr/share/terminfo/a/alacritty.info
```

This is the only `.info` file under /usr/share/terminfo. All of the other files installed there have already been converted.

```
❯ find /usr/share/terminfo | grep info$    
/usr/share/terminfo
/usr/share/terminfo/a/alacritty.info
```

Shouldn't this be packaged the way `kitty-terminfo` is?

```
❮ xbps-query -f kitty-terminfo
/usr/share/terminfo/x/xterm-kitty
```

Maybe terminfo/a/alacritty should be moved from `ncurses-term` to `alacritty-terminfo`?

```
xlocate /usr/share/terminfo/a/alacritty
alacritty-terminfo-0.10.1_1	/usr/share/terminfo/a/alacritty.info
ncurses-term-6.3_2	/usr/share/terminfo/a/alacritty
ncurses-term-6.3_2	/usr/share/terminfo/a/alacritty+common
ncurses-term-6.3_2	/usr/share/terminfo/a/alacritty-direct
```

**Comment by meator** [comment]
[`dvtm`](https://github.com/void-linux/void-packages/blob/master/srcpkgs/dvtm/INSTALL) and [`alacritty-terminfo`](https://github.com/void-linux/void-packages/blob/master/srcpkgs/alacritty/alacritty-terminfo.INSTALL) package the `.info` files with them and they are compiled in `INSTALL` script when they are being installed. These should be he only two packages that are doing this. I don't know why they don't simply compile them while building and then ship the compiled files, but I think the maintainers of these packages wouldn't have chosen this more complicated way of packaging terminfo without a reason.

Since these files are compiled on install, you should both have the `.info` and the compiled version @erwin. If not, than there is a problem with the `alacritty-terminfo` and it should be fixed.

And it might be more visible if you would create a separate issue for this if there are any problems with this rather than commenting on a old and closed issue.

**Comment by erwin** [comment]
> These should be he only two packages that are doing this. I don't know why they don't simply compile them while building and then ship the compiled files, but I think the maintainers of these packages wouldn't have chosen this more complicated way of packaging terminfo without a reason.

My point is really just that if you dump the `.info` file inside of `/usr/share/terminfo`, then `toe -a` will complain to STDERR that it can't open the raw .info file.

```
toe: couldn't open terminfo file alacritty.info.
```

So I don't think it's normal to leave the .info files in the /usr/share/terminfo directory.

I'll open a new issue. Just seemed minor and didn't want to alert more people than necessary.

**Comment by meator** [comment]
We are programmers. We don't care about warnings, we care about errors. Here's the fix:
```sh
toe -a 2>/dev/null
```
