### ISSUE TITLE
Develop a bot to automatically update a package version based on its Github repo releases

### ISSUE THREAD

**Issue by rivanfebrian123** [void-linux/void-packages#34898]
Please develop a bot that can parse versions from a Github repo releases automatically (probably using regex), and then get the latest release asset and get its checksum automatically, and finally, make a PR for that

**Comment by cinerea0** [comment]
A script already exists that alerts package maintainers when one of their packages has a new release. The reason the system you're proposing doesn't already exist is because testing that a package actually works is just as important as making sure that it builds, and testing functionality has to be done manually. Even if that weren't the case, there are packages that are deliberately held back for ecosystem compatibility reasons, so this system would end up flooding the repo with useless PRs.

**Comment by rivanfebrian123** [comment]
Okay, that's a good point
