### ISSUE TITLE
vscode: multi-arch support on binary repository

### ISSUE THREAD

**Issue by Animeshz** [void-linux/void-packages#35103]
Since 5762864e7cbfecbd5040ba82cda8afd9708aee3f the vscode isn't built for anything else x86_64{,-musl}.

Since chromium build takes too longer on platforms like raspberry pi (aarch64), its a mess installing it there. Can we get binary distributions?

PS: [raspberry pi os (based on debian) distribute it into deb repository](https://code.visualstudio.com/docs/setup/raspberry-pi)

**Comment by Johnnynator** [comment]
We do not build electron for aarch64 (yet), which would be needed to actually get a vscode aarch64 void package.

I can't comment on the referenced commit, and the reason behind it, but this problem is more likely easier to resolve than the electron one (our current chromium aarch64* build already blocks the builders for well over a day, adding electron of that size is currently not feasible)
