### ISSUE TITLE
Package request - qsqs,Ttyp0

### ISSUE THREAD

**Issue by loreb** [void-linux/void-packages#3549]
### System

* xuname:  
  Void 4.18.12_2 x86_64-musl GenuineIntel uptodate rF
* package:
  xiate

### Expected behavior
start the terminal, get reasonably looking font

### Actual behavior
![xiate-default-font-2018-10-08-175441_482x410_scrot](https://user-images.githubusercontent.com/2369930/46620326-ba520a00-cb24-11e8-8cf5-aa22f4e7245e.png)
See screenshot

### Steps to reproduce the behavior
The problem is that xiate reconfigures its default font by changing config.h and recompiling,
and the default choice isn't available in void; unlike say dwm, recompiling requires plenty of dependencies to be installed.

Changing by hand works, but it must be done every single time.

The default choice is "qsqs,Ttyp0 10" which should be https://www.uninformativ.de/git/qsqs/file/README.html (I honestly have no idea if the "ttyp0" part is a variant or an alternative font like uw-ttyp0 or ???)

**Comment by maxice8** [comment]
qsqs has no stable release

**Comment by loreb** [comment]
Ok, thank you.
Any chance to replace the font selection in config.h with something that is always installed?
I thought it would be trivial, but trying fonts from fc-list I unpredictably get working fonts or errors, eg
```
$ xterm -fn Helvetica
xterm: cannot load font: "Helvetica"
$ xterm -fn xft:Helvetica
# looks horrible
$ urxvt -fn xft:thisfontdoesnotexist
# looks bad but reports no error
$ xterm -fa xft:Go\ Mono
# looks ok
```

**Comment by vain** [comment]
Just for the record, even if this issue is pretty old (I stumbled on it a couple of weeks ago):

-   Since v20.04, xiate defaults to using `Monospace`. Should improve the experience when used out-of-the-box. (Still, I'd recommend manually cloning and compiling as it's the only way to change settings. Similar to suckless tools.)
-   qsqs has a stable release v20.03 now.
-   (The `Ttyp0` part in the old font specifier was a fallback font: If a character was not present in qsqs, then uw-ttyp0 was the next font to check. If it's not present there either, then some generic system fallback mechanism will take place.)
