### ISSUE TITLE
can't start warsow

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#35822]
![image](https://user-images.githubusercontent.com/79333625/155435326-40502e7e-a2bd-41c5-b64c-f094dae5012e.png)

**Comment by Anachron** [comment]
Whats printed in the console if you run it from there?

**Comment by curiousjunior** [comment]
literally nothing, qfusion doesn't print anything to standard output unless you patch its source code so that it prints to stdout/stderr everything it prints to the in-game console, I forgot which function is responsible for that, I guess it's one of `Com_DPrintf`, `Com_Printf` or `Q_snprintfz`, I know it'll print useful output because I had to deal with that when I ported this game to *bsd, it's just I no longer have computer which can compile c++ code fast

**Comment by curiousjunior** [comment]
alternative solution is to statically link *.so files it produces, I have a patch for that https://github.com/TeamForbiddenLLC/warfork-qfusion/pull/22/commits/3bc0880b4a1e9df74ee5a24b0fbe5ff8db475eba

**Comment by curiousjunior** [comment]
I forgot to mention that patch doesn't touch `snd_qf` because I removed that module before I made that patch, to get rid of `snd_qf` you need this patch:

**Comment by curiousjunior** [comment]
I'm sure this error is caused by unnecessary dynamic loading, that's why I'm proposing a patch that just statically links everything except `game` and `cgame` which are built in `modules_21.pk3` from `warsow-data`, the `libcgame_x86_64.so` and `libgame_x86_64.so` you install from `warsow` are loaded only if you disable "pure checks" https://github.com/TeamForbiddenLLC/warfork-qfusion/pull/22/commits/a23c9b818029c390663a16d20528a1a8b368d259 which is useful if you either care about CPU archs beyond x86 or OSes beyond windows, macos and glibc linux or you simply want to add cheats to `cgame` (I did both actually), so if you don't apply a patch that removes "pure checks", warsow won't run on non-x86 archs and musl flavor of void

**Comment by curiousjunior** [comment]
I couldn't run warsow after statically linking `game` and `cgame` modules because they conflict in global variable naming and duplicating code with different variables and functions names is a tedious task, so I recommend leaving those two as is after disabling "pure checks"

**Comment by paper42** [comment]
Please fill out the issue template

**Comment by angrygay** [comment]
@paper42
```
$ xuname
Void 5.15.30_1 x86_64 GenuineIntel uptodate rrrmFFF
$ xbps-query -p pkgver warsow
warsow-2.1_2
$ xbps-query -p pkgver warsow-data
warsow-data-2.1.2_1
```

**Comment by ztx-lyghters** [comment]
This is still a problem, and yet the version from the site works perfectly
