### ISSUE TITLE
Package Request: distrobox

### ISSUE THREAD

**Issue by gitpubber** [void-linux/void-packages#36341]
https://github.com/89luca89/distrobox : Use any linux distribution inside your terminal. Enable both backward and forward compatibility with software and freedom to use whatever distribution you’re more comfortable with.

**Comment by Anachron** [comment]
This is just a wrapper for podman/docker?

**Comment by blacklightpy** [comment]
> If you believe you have an exception, start a PR and make an argument for why that particular piece of software, while not meeting any of the following requirements, is a good candidate for the Void packages system.

Distrobox was developed to make life on immutable operating systems easier. That is, instead of running Podman to run command line packages, one could just `distrobox enter <name>` and work away. When it comes to Podman, I'll have to manually set up the volumes and I'll have to learn other syntax. With Distrobox, I can get my job done without having to know anything. It even sets up a user for you (which is the same as your host username).

Running graphical Xorg app on Podman? aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa. Running it on Distrobox? `distrobox enter ubuntu-container`, `sudo apt install vscode`, `code`. Instead of VS Code, it might just be some app that has a systemd dependency for example.

In `distrobox.conf` I can set the default image, any hooks and my home location. You can also export any binaries from a distrobox container to a `.desktop` file using `distrobox --export /usr/bin/<app>`.

I may wish to use a package that's only built for Arch glibc, I could enter that container.
There may be some proprietary packages that are only available as DEB/RPM. I could just pull up a Debian container and enter it.

What I'm trying to say is that Distrobox has no learning curve. It's just like how Virtualbox or Virt-man is easier than setting up virsh. It could be recommended to use Podman, but when someone wants something done, it's better to have something to work with rather than not being able to do anything because they'll have to learn the underlying tool first.
