### ISSUE TITLE
SyntaxError with python3 update

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#36347]
@ahesford Just wanted to point out, in case it is relevant.
With today's python3 update, I noticed:
```
[*] Configuring unpacked packages
python3-3.10.4_1: configuring ...
Byte-compiling python code in usr/lib/python3.10...
*** Error compiling './usr/lib/python3.10/site-packages/trimesh/resources/templates/blender_boolean.py'...
  File "./usr/lib/python3.10/site-packages/trimesh/resources/templates/blender_boolean.py", line 39
    mesh_pre = $MESH_PRE
               ^
SyntaxError: invalid syntax

Byte-compiling python3.10 code for module README.txt...
Updating ldconfig(8) cache...
python3-3.10.4_1: updated successfully.
python3-devel-3.10.4_1: configuring ...
python3-devel-3.10.4_1: updated successfully.
```

**Comment by ahesford** [comment]
This is an expected side effect of the XBPS trigger that pre-compiles Python source and has been present for some time. The trigger uses the `compileall` module to recursively compile Python source in a module directory. The `blender_boolean.py` file responsible for the error is not valid Python source, but a template that is rendered by... something. (I'm not familiar with this package and don't know where it's used.)

Even if we made the trigger more sophisticated to avoid attempts to compile contents that obviously aren't Python source (the trigger used to try compiling a README for one package!), this particular case would be nearly impossible to detect and avoid because it has a `.py` extension and lives in a Python package hierarchy. The right fix here is for `trimesh` upstream to use a different location or extension for this file; it isn't valid Python until rendered and shouldn't masquerade as such.
