### ISSUE TITLE
[RFC]: decouple zig and llvm packages

### ISSUE THREAD

**Issue by prez** [void-linux/void-packages#36951]
Having to simultaneously update both zig and LLVM leads to Void being two major versions behind in the latter, which is unacceptable imho. 
I suppose the reason for that is there not being enough maintainers capable of updating LLVM who are also willing to deal with zig (only @ifreund).

It seems that with https://github.com/ziglang/zig-bootstrap there's a way to use a bundled LLVM, and I propose the zig package in Void to be changed to use those sources, or failing that, to simply drop zig from void-packages. 
The two zig packages Void currently has do not warrant withholding LLVM updates for such a long time - it should always be a priority of Void to ensure LLVM is up to date.

**Comment by Duncaen** [comment]
Why single out zig, anything using llvm depends on a specific version in one way or another. Building bundled llvm is simply not worth it, if we need multiple versions then we should use versioned packages again if possible.

**Comment by ifreund** [comment]
> Because it's been blocking the update #36229 #34800 for 4 months and is arguably not very useful (2 packages).

zig isn't blocking llvm 13, I sent patches for the zig related things many months ago. The only thing blocking llvm 13 as far as I'm aware is someone with void-packages commit access to find time to review and merge the PR.

I did comment in one of those threads that zig is not compatible with llvm 14 yet and won't be for the next month or so at least. That does not block llvm 13 being merged though.

Zig does not require any patches to llvm or otherwise make it difficult to use a system llvm installation of the proper version. If we need llvm 14 before zig 0.10.0 is released then I recommend doing as duncaen says and keeping a llvm13 package around until zig 0.10.0 is released.

The root cause of this problem is that each llvm release is incompatible with the last and that llvm is a very large and expensive dependency to build from source.

**Comment by prez** [comment]
You are right, it's not zig in this case - apologies. But right now, it's going to require making some zig-specific changes for 14.
I created https://github.com/void-linux/void-packages/pull/36962/.
For the future, it should depend on bundled llvm sources.

**Comment by Duncaen** [comment]
> For the future, it should depend on bundled llvm sources.

No we should just have multiple versions of llvm, its not limited to zig.

**Comment by prez** [comment]
> No we should just have multiple versions of llvm, its not limited to zig.

If there are enough resources to maintain multiple versions, then I agree. 
I will close this now, another issue should be created to track progress on the above-mentioned.

**Comment by Duncaen** [comment]
The alternative would be having to "maintain" bundled llvm's separately, so yes keeping an old version around is a lot easier.
