### ISSUE TITLE
mtxclient causes nheko to segfault

### ISSUE THREAD

**Issue by RunningDroid** [void-linux/void-packages#37442]
### System

* xuname:  
  Void 5.15.45_1 x86_64 GenuineIntel uptodate rrmFFFFFFFFFFFFFFFF
* package:  
  mtxclient-0.7.0_1
  nheko-0.9.2_2

### Expected behavior
Not segfaulting when viewing a room in nheko

### Actual behavior
Segfaulting when viewing a room in nheko

### Steps to reproduce the behavior
1. launch nheko
2. try to view a room

Rebuilding mtxclient fixes this, but as near as I can tell the only dependency that's been updated is [openssl](https://github.com/void-linux/void-packages/commit/134c645bd4fd68c6669f917a10a4bd7e6df7fd0e) so I don't know why it fixes it.

Related: Nheko-Reborn/nheko#1083

**Comment by balejk** [comment]
I believe this was caused by a recent update of `spdlog`, which both `nheko` and `mtxclient` rely on. Only `nheko` was rebuilt against the new version as `spdlog` was not explicitly listed in `makedepends` of `mtxclient` and it was only pulled indirectly as a dependency of `coeurl`. I'm opening a pull request to address this.

**Comment by balejk** [comment]
Never mind, I didn't realize that the dependency on `spdlog` was introduced to `mtxclient` only after its latest release. Now I think the problem is connected with the recent update of `json-c++`, which also seems to be what the backtrace implies. My understanding is limited, but is it possible that the problem was caused by the `nheko` rebuild (required because of the `spdlog` update) which used the new version of `json-c++` while `mtxclient` is built with the older version?

**Comment by deepbluev7** [comment]
Yes, nlohmann/json is a header only lib with afaik no ABI stability. So if it changes minor version, it will generate different code in different files, where it was included. That mismatch can then cause crashes because inlined functions call the wrong noninlined code or so.

**Comment by kartikynwa** [comment]
Was facing the same issue and rebuilding mtxclient fixed it. Thanks for posting the solution.
