### ISSUE TITLE
Package request: Ryujinx

### ISSUE THREAD

**Issue by Nathan-MV** [void-linux/void-packages#38302]
### Package name

ryujinx

### Package homepage

https://ryujinx.org/

### Description

Nintendo Switch emulator, does a better job than yuzu in some games

### Does the requested package meet the quality requirements?

Compiled

### Is the requested package released?

Yes

**Comment by JamiKettunen** [comment]
I don't see a single release/tag on https://github.com/Ryujinx/Ryujinx, see https://github.com/void-linux/void-packages/blob/master/Manual.md#quality_requirements.

There seems to be automated version tagging based on pushes to [master branch](https://github.com/Ryujinx/Ryujinx/commits/master) setup on https://github.com/Ryujinx/release-channel-master/releases/latest but I don't think that falls under the quality requirements if every commit is always tagged, built and artifacts pushed to this separate repo.

Additionally .NET Core building/running requires the .NET Core SDK/runtime respectively which aren't available in repo due to #32974 being closed with no one else picking it back up since then.

**Comment by JamiKettunen** [comment]
I should mention that however not ideal for now there is a [`org.ryujinx.Ryujinx`](https://flathub.org/apps/details/org.ryujinx.Ryujinx) flatpak available through Flathub which also [seems to track release-channel-master](https://github.com/flathub/org.ryujinx.Ryujinx) releases pretty closely.

**Comment by meator** [comment]
> There seems to be automated version tagging based on pushes to [master branch](https://github.com/Ryujinx/Ryujinx/commits/master) setup on https://github.com/Ryujinx/release-channel-master/releases/latest but I don't think that falls under the quality requirements if every commit is always tagged, built and artifacts pushed to this separate repo.

I don't think it would be that big of an issue. For example [hwinfo does that too](https://github.com/openSUSE/hwinfo#opensuse-development).

**Comment by paper42** [comment]
> I don't think it would be that big of an issue. For example [hwinfo does that too](https://github.com/openSUSE/hwinfo#opensuse-development).

We are not OpenSUSE, this is not hwinfo and it doesn't meet our quality requirements.
