### ISSUE TITLE
intellij-idea-community-edition: Start building from source

### ISSUE THREAD

**Issue by JamiKettunen** [void-linux/void-packages#38361]
I suggest we start building [`intellij-idea-community-edition`](https://github.com/void-linux/void-packages/tree/master/srcpkgs/intellij-idea-community-edition) instead of packaging "proprietary" x86 glibc binaries.

This way we can both (ideally) have it available for musl libc systems as well as more architectures such as aarch64.

The source code is available at https://github.com/JetBrains/intellij-community and is licensed under [`Apache-2.0`](https://github.com/JetBrains/intellij-community/blob/master/LICENSE.txt).

From what I can tell Arch Linux for example [already builds it from source](https://github.com/archlinux/svntogit-community/blob/packages/intellij-idea-community-edition/trunk/PKGBUILD) and extracts an artifact archive similar to the one that is currently downloaded directly from JetBrains.

**Comment by Johnnynator** [comment]
Just doing the arch way and building from "source" will give us not much benefit, since the build afaik craps out on anything not x86_64 glibc, since it does fetch a ton of prebuilts.

It would be way easier to just built and replace the binaries and keep the jars as is (kinda the way FreeBSD does this), everything else is close to insanity.
