### ISSUE TITLE
Bug in glib update 2.74.0 (part II)

### ISSUE THREAD

**Issue by biopsin** [void-linux/void-packages#39523]
### Is this a new report?

Yes

### System Info

Linux voidx 5.10.145_1 #1 SMP Sat Sep 24 09:55:29 UTC 2022 x86_64 GNU/Linux

### Package(s) Affected

Any GTK3+ (firefox-esr, scite)

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Unknown

### Expected behaviour

no issues

### Actual behaviour

After a reboot upgrading kernel from 5.4 -> 5.10 and also a update to glib-2.74.0 trying to launch any gtk3 applications (firefox-esr, scite) ends up in a Trace/breakpoint trap.
However I have spacefm (gtk2) and it has no issues.

Downgrading to glibc-2.72. resolves my issue, but I will further do a rebuild of GTK3+ as there seems to be more oddities going on after update.

### Steps to reproduce

launch any gtk3 application from terminal

**Comment by biopsin** [comment]
Upsidupsi a local issue : 
since I run GTK3-classic on this spesific machine, applying https://github.com/lah7/gtk3-classic/commit/8e6176c5eb8a3c45e78be0a9190db44d798bb0f6 should fix my problem.

**Comment by paper42** [comment]
Not a Void bug, but I wonder if @bugcrazy is also using that project.

**Comment by bugcrazy** [comment]
> Not a Void bug, but I wonder if @bugcrazy is also using that project or just an old version of gtk3.
> 
> This seems to be the same as #39390

I use gtk3-classic and gtk3, the bug is in the glib 2.74 version, the blame of the glib devs.

**Comment by paper42** [comment]
That's not how this works, update your gtk.

**Comment by bugcrazy** [comment]
> That's not how this works, update your gtk.
> You shouldn't be able to reproduce this with a regular, not pached, up to date, official gtk+3 package.

I solved my problem, using the glib 2.72 version, I won't update for version 2.74, there are many problems and bugs.

**Comment by paper42** [comment]
We do not support that and as more packages get updated, they will rely on glib 2.74 features. Please fix the underlying problem in your setup, most likely by updating GTK that you downgraded.

**Comment by paper42** [comment]
And if there are any bugs in a normal void setup, not a highly customized one, they should be reported and fixed. So far only the gimp text tool bug was reported and fixed.

**Comment by q66** [comment]
i for one sincerely hope that @bugcrazy's setup gets broken

**Comment by bugcrazy** [comment]
> We do not support that and as more packages get updated, they will rely on glib 2.74 features. Please fix the underlying problem in your setup, most likely by updating GTK that you downgraded.

I'll test Debian patches or wait for a really stable release of version 2.74.

https://launchpad.net/debian/+source/glib2.0/+changelog

**Comment by bugcrazy** [comment]
> And if there are any bugs in a normal void setup, not a highly customized one, they should be reported and fixed. So far only the gimp text tool bug was reported and fixed.

There was another user who told me, who had problems with glib 2.74 in thunar with android-tools. There are problems with glib update in distro:

https://forum.endeavouros.com/t/timeshift-issue/10391/9

**Comment by bugcrazy** [comment]
> i for one sincerely hope that @bugcrazy's setup gets broken

I don't have broken setup, it only happens with glib update.

**Comment by bugcrazy** [comment]
> I will ask one last time, can you reproduce this with an unmodified Void system (especially with the official gtk+3 package) or is it an issue in your modifications?

I have another machine, I use it as a server, no modifications to the packages, I just update, so far I haven't found any errors in glib. If the update problem was just mine, it would be an isolated case, but there are reports in other distros, so  it's not an isolated case.

**Comment by paper42** [comment]
As I already said, if there are issues, they should be reported and fixed. I don't see any indication this (all gtk applications not starting) is an issue and you keep avoiding my question whether you can reproduce this with a official unmodified gtk+3 package. 
It would be nice if users could report bugs to us and not you, I can reproduce the issue with timeshift. Could the user who reported it to you or you open an issue about it?

> If the update problem was just mine, it would be an isolated case, but there are reports in other distros, so it's not an isolated case.

Could you link an issue in another distribution where all gtk applications don't start?

android-tools doesn't even depend on glib, so I am not sure how that would be an issue and I can not reproduce the Thunar issue.

**Comment by bugcrazy** [comment]
> As I already said, if there are issues, they should be reported and fixed. I don't see any indication this (all gtk applications not starting) is an issue and you keep avoiding my question whether you can reproduce this with a official unmodified gtk+3 package. It would be nice if users could report bugs to us and not you, ~I can reproduce the issue with timeshift~. Could the user who reported it to you or you open an issue about it if they are also not using a heavily modified system?
> 
> correction: I can not reproduce a crash with glib 2.74, but I see some failed assertions and there are reports upstream
> 
> > If the update problem was just mine, it would be an isolated case, but there are reports in other distros, so it's not an isolated case.
> 
> Could you link an issue in another distribution where all gtk applications don't start?
> 
> android-tools doesn't even depend on glib, so I am not sure how that would be an issue and I can not reproduce the Thunar issue.

I will only use glib 2.74, when they release a glib version 2.74.1 or higher, which really fixes the problems, as there are no test tools on the glib if it had no bug in the gimp.

Problems in other distros are similar.

Already question of the thunar, would be a problem of stamp data/team, when copies android files to Void. Because user, it didn't open Issue in github, that's a matter of him.

**Comment by paper42** [comment]
> I will only use glib 2.74, when they release a glib version 2.74.1 or higher, which really fixes the problems

"the problems"? You refuse to test this with the official gtk package and none of your reports make sense. Which problems do you have that are not caused by your modifications?

> as there are no test tools on the glib if it had no bug in the gimp.

glib has a test suite, I am not sure what your point is here.

> Problems in other distros are similar.

Problems with which programs that we also have? Links? Can you reproduce the issues? If there are none that you are experiencing, we don't care.

> Already question of the thunar, would be a problem of stamp data/team, when copies android files to Void. Because user, it didn't open Issue in github, that's a matter of him.

I don't really understand the first sentence, but if there isn't an open issue, we will probably ignore it.

You are not trying to be helpful. You just decided that glib 2.74 is bad, you complain in 3 (1 unrelated) threads, ignore me when I ask you to test something and then continue with complaining. This is not Telegram, this is a bug tracker and you are expected to cooperate in order for us to figure out how to solve the issues if there are any.

**Comment by bugcrazy** [comment]
> > I will only use glib 2.74, when they release a glib version 2.74.1 or higher, which really fixes the problems
> 
> "the problems"? You refuse to test this with the official gtk package and none of your reports make sense. Which problems do you have that are not caused by your modifications?
> 
> > as there are no test tools on the glib if it had no bug in the gimp.
> 
> glib has a test suite, I am not sure what your point is here.
> 
> > Problems in other distros are similar.
> 
> Problems with which programs that we also have? Links? Can you reproduce the issues? If there are none that you are experiencing, we don't care.
> 
> > Already question of the thunar, would be a problem of stamp data/team, when copies android files to Void. Because user, it didn't open Issue in github, that's a matter of him.
> 
> I don't really understand the first sentence, but if there isn't an open issue, we will probably ignore it.
> 
> You are not trying to be helpful. You just decided that glib 2.74 is bad, you complain in 3 (1 unrelated) threads, ignore me when I ask you to test something and then continue with complaining. This is not Telegram, this is a bug tracker and you are expected to cooperate in order for us to figure out how to solve the issues if there are any.

I opened a issue here, as the problem was not reproduced, it was closed, so the problem was gimp, I said on the gimp ticket, what a bug was on the glib, you said the problem was at gimp, that glib 2.74 had shown this bug in gimp, then you posted what problem was really glib and hid the posts on the gimp ticket because they were off-tropics. I also opened glib's gitlab ticket, was closed and had poorly answered answers, I started accompanying gitlab glib tickets, has many problems related to glib 2.73, which has a 2.74 code and problems at 2.74, are simply closed and not fixed , they release a version with bugs and misplaced, the gimp is proof of this, because it is a brother project, they create patches later and is like this, just like Debian package full of patches.

If there really is glib testsuite, it does not work, as they would easily detect errors before, the problem with gimp would not exist.

The user who reported a problem with thunar knows how to create Issue here, because he didn't open it, I don't know.

If my needs, they require specific things, glib 2.74 problems cannot be reproduced, how would this help Void?
