### ISSUE TITLE
Disable mining tracker in gtk4

### ISSUE THREAD

**Issue by hzafzz** [void-linux/void-packages#40373]
Please, disable mining tracker (https://tracker.gnome.org/) in gtk4. Why do we need this probe and excessive CPU/io usage?

It would be better to build gtk4 with default options (see meson_options.txt from the source https://download.gnome.org/sources/gtk/4.8/gtk-4.8.2.tar.xz).

**Comment by paper42** [comment]
gtk4 only depends on libtracker with this option, it shouldn't do anything if you don't have tracker-miners installed. I enabled the option to make sure search in the file selection dialog works as expected. I also don't see any excessive resource usage on my computer.
Arch and Fedora also enable tracker support, Alpine and Gentoo do not, Alpine probably because that's a relatively minimal distribution that tries to keep dependencies minimal and the Gentoo ebuild says it's because they don't have tracker3 packaged even though I can see it in the packages :shrug:.

**Comment by hzafzz** [comment]
The tracker in gtk4 is harmful. It's like a systemd concieved not for users' well-being but for corporations (google/ibm/redhat/etc) syphoning our data and killing laptops' batteries (android is nigtmare).
I know I can rebuild gtk4 from the source on my own, but then I have to rebuld all gtk4-dependant software. I don't want to rebuild heavy software like libreoffice and browsers on every gtk4 update. I don't want to transform Voidlinux into Gentoo.

**Comment by paper42** [comment]
If you or someone else has a real reason why it should be disabled, feel free to leave a comment.

**Comment by hzafzz** [comment]
If users' privacy and waste of resourses are not real reasons then I don't know what is real reason.

**Comment by eli-schwartz** [comment]
> If users' privacy

That sounds like a bogus claim, please provide evidence.

> and waste of resourses

Legitimate gripe. I rebuild gtk4 with this feature disabled myself, but I rebuild gtk4 regardless so it's easy for me.

Why is it a problem for you to just have libtracker installed, but not install the miner, or disable it via options? "excessive CPU/io usage" will be avoided, having a small unneeded package installed is not a great burden.
