### ISSUE TITLE
octoxbps is broken

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#40664]
### Is this a new report?

Yes

### System Info

Void 6.0.9_1 x86_64 GenuineIntel uptodate FFFFF

### Package(s) Affected

octoxbps-0.3.0_3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

-

### Expected behaviour

the program starts properly.

### Actual behaviour

```
➜  ~ octoxbps
octoxbps: symbol lookup error: octoxbps: undefined symbol: _ZN11QTermWidget20setScrollBarPositionENS_17ScrollBarPositionE
➜  ~
```

### Steps to reproduce

1. `xbps-install -S octoxbps`
2. run `octoxbps` in terminal

**Comment by classabbyamp** [comment]
24f7f8796ee29ff447ac7d140fa9325f63059d6e

**Comment by AngryPhantom** [comment]
Sorry, guys. It still doesn't start in Void Linux. Is it really fixed or not?

All I get is this:

octoxbps: symbol lookup error: octoxbps: undefined symbol: _ZN11QTermWidget20setScrollBarPositionENS_17ScrollBarPositionE

Thank you in advance.

**Comment by paper42** [comment]
Is your system up to date? What's the output of `xbps-query -p pkgver octoxbps?

**Comment by AngryPhantom** [comment]
@paper42 

Sorry, guys, I just got confused a bit with its versions. It now works in Void. The only thing I would really kindly ask you: to update it from the author's github. Yeah, I know, it's an **upstream version** and **not a release** (seems that there are no releases on his github anymore), but it lacks one feature (a bug actually): it doesn't see a **plus** (+) **symbol** when searching for packages (example: **gtk+**). I reported it some time ago and the author fixed this issue. So, pretty please, if you can do it somehow. I'm using his upstream version as of now because of this bug.

**Comment by paper42** [comment]
octoxbps is not special in any way, if the author considers the current state to be ready, they should tag a release.
