### ISSUE TITLE
[RFC] auto-disable debug and multilib for bootstrap packages?

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-packages#42069]
@void-linux/pkg-committers 

Should setting `repository=bootstrap` automatically disable debug and multilib package generation?

for reference: #39868

**Comment by ahesford** [comment]
Yes.

**Comment by Duncaen** [comment]
Why?

**Comment by ahesford** [comment]
We have no mechanism for actually tying debug/multilib packages to their parents and tend to leave behind stale debugs when we change the package tree even after manually removing the parents. If the bootstrap debug packages end up in the regular debug repo, it will lead to public clutter for packages that are obscured from general visibility anyway. If they end up in a `bootstrap/debug` repo, it's just another directory with a state that will deviate from the master. I can't imagine there's any real utility in the packages, so it's probably better to just skip them.

**Comment by Duncaen** [comment]
> We have no mechanism for actually tying debug/multilib packages to their parents and tend to leave behind stale debugs when we change the package tree even after manually removing the parents.

We have `source-revisions`:
```
$ xbps-query --regex -Rp source-revisions -s "^zlib:"
zlib-1.2.13_1: zlib:5f1d95b23c (https://repo-fastly.voidlinux.org/current)
zlib-devel-1.2.13_1: zlib:5f1d95b23c (https://repo-fastly.voidlinux.org/current)
zlib-dbg-1.2.13_1: zlib:5f1d95b23c (https://repo-fastly.voidlinux.org/current/debug)
zlib-32bit-1.2.13_1: zlib:91837caec7 (https://repo-fastly.voidlinux.org/current/multilib)
zlib-devel-32bit-1.2.13_1: zlib:91837caec7 (https://repo-fastly.voidlinux.org/current/multilib)
```

We could also use that as a better way to delete packages in the future, instead of having file names we just have arch+source-revisions combos that we put in a script that looks up the packages and deletes them.

> If they end up in a bootstrap/debug repo, it's just another directory with a state that will deviate from the master. I can't imagine there's any real utility in the packages, so it's probably better to just skip them.

They should end up there IMHO, adding magic to disable debug based on repository just because there might be no apparent utility doesn't seem like a good idea. Seems like a bug that is only using the templates `repository` for the the package itself and multilib, but not for debug.
