### ISSUE TITLE
godot: mime, man pages file is missing

### ISSUE THREAD

**Issue by Luciogi** [void-linux/void-packages#45917]
godot package has missing files 
```
/usr/share/mime/packages/org.godotengine.Godot.xml
/usr/share/man/man6/godot.6
```

**Comment by Luciogi** [comment]
ping for maintainer @dataCobra

**Comment by dataCobra** [comment]
Hey,

I'm not the maintainer but did work on the package in the last couple of month.

I had a surgery last week and because of this I'm not able to work on the package myself.

Could you try to find a person in one of the IRC Channels that could fix this? That would be great.

Regards
Ben/dataCobra

**Comment by Luciogi** [comment]
@dataCobra May you get well soon.
Thanks for response

**Comment by Luciogi** [comment]
you could tell me estimated compilation time for godot?

**Comment by dataCobra** [comment]
Heyho,

thanks for contributing. :)
