### ISSUE TITLE
[cross-arm-none-eabi-gcc] / outdated?

### ISSUE THREAD

**Issue by riddicc** [void-linux/void-packages#46239]
This bug seems to be fixed in GCC 10 (and later): https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111582

Can we have a newer version of cross-arm-none-eabi-gcc than 9.3.0, please?

**Comment by riddicc** [comment]
how could i become the maintainer?
i mean: isn't it easy to change the version to 13.2.0? and then tell ur compute server to wrangle it?

**Comment by ahesford** [comment]
We ask that users not contribute "outdated package" issues because we have scripts to automatically identify outdated packages. If it hasn't been updated, either nobody has taken an interest or there is some non-obvious complexity holding up an update.

If you don't see a PR dealing with the desired update, we invite you to contribute one.
