### ISSUE TITLE
gzdoom does not function, simply displays "Cannot find gzdoom.pk3"

### ISSUE THREAD

**Issue by mayhair** [void-linux/void-packages#46386]
### Is this a new report?

Yes

### System Info

Void 6.5.5_2 x86_64 GenuineIntel uptodate FFFFFFFFFF

### Package(s) Affected

gzdoom-4.11.0_1

### Expected behaviour

A window prompting to select a folder where .wad files (DOOM engine games) are stored pops up.

### Actual behaviour

A window pops up, simply saying "Cannot find gzdoom.pk3". The only option is "exit".

### Steps to reproduce

1. Make a fresh installation of gzdoom.
2. Launch it.

**Comment by SpidFightFR** [comment]
'sup i had this issue, basically since a recent release, GZDoom Devs removed by default a line in a conf file that allows gzdoom to search for `pk3` files.

To solve this, head over to `~/.config/gzdoom/gzdoom.ini` and add `Path=$HOME/.config/gzdoom` to both `IWAD.directories` and `FileSearch.directories`.

It will solve this issue.

**Comment by mayhair** [comment]
I still get the problem even after adding those lines to the config file ...

**Comment by SpidFightFR** [comment]
Oh right! Sorry yes it depends on your install. 😅

**Comment by ahesford** [comment]
Seems this has been fixed in a prior update.
