### ISSUE TITLE
Ulauncher broken after python 3.12 upgrade

### ISSUE THREAD

**Issue by dom0** [void-linux/void-packages#46545]
### Is this a new report?

Yes

### System Info

Void 6.5.6_1 x86_64

### Package(s) Affected

ulauncher-5.15.4_1, python3-Levenshtein-0.12.0_9

### Expected behaviour

ulauncher command should open application popup

### Actual behaviour

Command fails with python undefined symbol error due to **PyUnicode_AS_UNICODE** remotion on python 3.12
Affected package is python3-Levenshtein

```py
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 27, in <module>
    from ulauncher.main import main
  File "/usr/lib/python3.12/site-packages/ulauncher/main.py", line 25, in <module>
    from ulauncher.ui.windows.UlauncherWindow import UlauncherWindow
  File "/usr/lib/python3.12/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 23, in <module>
    from ulauncher.search.Search import Search
  File "/usr/lib/python3.12/site-packages/ulauncher/search/Search.py", line 3, in <module>
    from ulauncher.api.server.ExtensionSearchMode import ExtensionSearchMode
  File "/usr/lib/python3.12/site-packages/ulauncher/api/server/ExtensionSearchMode.py", line 3, in <module>
    from ulauncher.api.server.DeferredResultRenderer import DeferredResultRenderer
  File "/usr/lib/python3.12/site-packages/ulauncher/api/server/DeferredResultRenderer.py", line 11, in <module>
    from ulauncher.api.shared.item.ResultItem import ResultItem
  File "/usr/lib/python3.12/site-packages/ulauncher/api/shared/item/ResultItem.py", line 5, in <module>
    from ulauncher.utils.text_highlighter import highlight_text
  File "/usr/lib/python3.12/site-packages/ulauncher/utils/text_highlighter.py", line 1, in <module>
    from ulauncher.utils.fuzzy_search import get_matching_indexes
  File "/usr/lib/python3.12/site-packages/ulauncher/utils/fuzzy_search.py", line 4, in <module>
    from Levenshtein import distance
  File "/usr/lib/python3.12/site-packages/Levenshtein/__init__.py", line 1, in <module>
    from Levenshtein import _levenshtein
ImportError: /usr/lib/python3.12/site-packages/Levenshtein/_levenshtein.so: undefined symbol: PyUnicode_AS_UNICODE
```

### Steps to reproduce

1. Open terminal
2. execute command ulauncher

**Comment by icp1994** [comment]
Probably because the the Levenshtein package is so old. Also looks like that version doesn't even support Cython3. But updating it requires a new build backend package, scikit-buid.

**Comment by ahesford** [comment]
Unfortunately, `python3-Levenshtein` is kind of a mess. Updating fully is kind of ugly because it depends a new RapidFuzz package, and both of those depend on scikit-build, which 1) I suspect would require some hacking to work with our cross-compilation setup; and 2) the authors of scikit-build already seem to be deprecating it in favor of another variant. I considered patching the version we have to work around the Levenshtein problem, but that is a non-trivial patch that requires some thought about Python object lifetimes in C extensions. Because I don't actually use this software, I don't know anything about Levenshtein and am not sure what the right approach is there. Finally, I considered updating to a newer (but still outdated) Levenshtein, which uses Cython without CMake and scikit-build. The newer version probably avoids our issues, but still depends on RapidFuzz and may or may not require scikit-build anyway. I haven't looked very closely at this option.

For now, a workaround seems to be shadoing the Levenshtein package in a virtual environment:

```sh
python3 -m venv --system-site-packages ${HOME}/ulauncher.venv
${HOME}/ulauncher.venv/bin/pip install -U Levenshtein
```

Whenever you want to run `ulauncher`, run it as

```sh
${HOME}/ulauncher.venv/bin/python3 /usr/bin/ulauncher
```

instead. This will at least bring up the program for me, but I can't test it any more thoroughly. You can, of course, put the venv anywhere you like.

**Comment by dom0** [comment]
> Unfortunately, `python3-Levenshtein` is kind of a mess. Updating fully is ugly because it depends a new RapidFuzz package, and both of those depend on scikit-build, which 1) I suspect would require some hacking to work with our cross-compilation setup; and 2) the authors of scikit-build already seem to be deprecating it in favor of another variant. I considered patching the version we have to work around the Levenshtein problem, but that is a non-trivial patch that requires some thought about Python object lifetimes in C extensions. Because I don't actually use this software, I don't know anything about Levenshtein and am not sure what the right approach is there. Finally, I considered updating to a newer (but still outdated) Levenshtein, which uses Cython without CMake and scikit-build. The newer version probably avoids our issues, but still depends on RapidFuzz and may or may not require scikit-build anyway. I haven't looked very closely at this option.
> 
> For now, a workaround seems to be shadoing the Levenshtein package in a virtual environment:
> 
> ```shell
> python3 -m venv --system-site-packages ${HOME}/ulauncher.venv
> ${HOME}/ulauncher.venv/bin/pip install -U Levenshtein
> ```
> 
> Whenever you want to run `ulauncher`, run it as
> 
> ```shell
> ${HOME}/ulauncher.venv/bin/python3 /usr/bin/ulauncher
> ```
> 
> instead. This will at least bring up the program for me, but I can't test it any more thoroughly. You can, of course, put the venv anywhere you like.


Thanks for the feedback and help. I tried the same workarounds before opening issue and in the end I opted to switch to wofi. "It's a Python Thing :)"

For those who are looking for an alternative, below are the wofi options that I am using to have similar behavior (not feature complete) to ulauncher:

`wofi -n -i --show drun --allow-images --allow-markup --matching=fuzzy`
