### ISSUE TITLE
VirtualBox DKMS modules don't load on Linux 6.5

### ISSUE THREAD

**Issue by too-vague** [void-linux/void-packages#46912]
### Is this a new report?

Yes

### System Info

Void 6.5.9_1 x86_64 AuthenticAMD uptodate FF

### Package(s) Affected

virtualbox-ose-dkms-7.0.10_4, linux6.5-6.5.9_1

### Expected behaviour

Compile and load Virtualbox DKMS modules (vboxdrv, vboxnetadp, vboxnetflt), as seen in linux6.4 and below

### Actual behaviour

DKMS modules compile properly but fail to load both during boot and manually

modprobe:
```
modprobe: ERROR: could not insert 'vboxdrv': Key was rejected by service
modprobe: ERROR: could not insert 'vboxnetadp': Key was rejected by service
modprobe: ERROR: could not insert 'vboxnetflt': Key was rejected by service
```

dmesg:
```
[ 1168.956122] Loading of module with unavailable key is rejected
[ 1168.961298] Loading of module with unavailable key is rejected
[ 1168.966354] Loading of module with unavailable key is rejected
```

### Steps to reproduce

1. Install linux6.5 and virtualbox-ose
2. Run virtualbox on new kernel

**Comment by nezos** [comment]
For me:

Building DKMS module: virtualbox-ose-guest-7.0.10... FAILED!

for kernel 6.5.8

According to the recent changelog (https://www.virtualbox.org/wiki/Changelog):

Since version 7.0.12...
"Linux Guest Additions: Added initial support for kernels 6.5 and 6.6" 

An update would probably solve the issue.

**Comment by classabbyamp** [comment]
#47037
