### ISSUE TITLE
GZDoom reports its version as "<unknown version>"

### ISSUE THREAD

**Issue by Jjp137** [void-linux/void-packages#47787]
### Is this a new report?

Yes

### System Info

Void 6.1.67_1 x86_64 GenuineIntel uptodate FFFFFF

### Package(s) Affected

gzdoom-4.11.3_1

### Expected behaviour

GZDoom should display the correct version number (4.11.3 as of this writing) where appropriate, including during startup and within the in-game console.

### Actual behaviour

First few lines of output:
```
$ gzdoom -iwad doom.wad
GZDoom <unknown version> -  - SDL version
Compiled on Nov 18 2023

OS: Void Linux, Linux 6.1.67_1 on x86_64
GZDoom version <unknown version>
```

In-game, `<unknown version>` is shown on the bottom-right corner of the console.

### Steps to reproduce

Run GZDoom from the command line in order to see the terminal output, which is always printed even without an IWAD present.

If an IWAD can be found on your system, after GZDoom starts, open the console (default: ~) and observe that the bottom-right corner says `<unknown version>`.

**Comment by meator** [comment]
I will take a look at this.

**Comment by meator** [comment]
I won't make an effort fixing this because this doesn't affect the functionality of GZDoom. This is only "cosmetic".

If anyone else wants to fix this:
The relevant file is [https://github.com/ZDoom/gzdoom/blob/master/tools/updaterevision/UpdateRevision.cmake](https://github.com/ZDoom/gzdoom/blob/master/tools/updaterevision/UpdateRevision.cmake) (and https://github.com/ZDoom/gzdoom/blob/master/tools/updaterevision/gitinfo.h.in). It uses git to determine the version, hash and timestamp. Git isn't installed on host and the source comes from a tarball and not from git so this mechanism fails and defaults to `<unknown version>`.
