### ISSUE TITLE
Packages installed through void-packages do not produce audio

### ISSUE THREAD

**Issue by WagyuDEV** [void-linux/void-packages#47863]
### Is this a new report?

Yes

### System Info

Void 6.5.13_1 x86_64 AuthenticAMD uptodate rFFFFF

### Package(s) Affected

brave-browser-1.61.104_1, discord-0.0.38_1

### Expected behaviour

Expect audio to be produced when playing video or the application produces sound of any kind.

### Actual behaviour

No audio is produced, under any circumstances.

### Steps to reproduce

1. install application EX: discord
`$ echo XBPS_ALLOW_RESTRICTED=yes >> etc/conf`
`./xbps-src pkg <package_name>`
`xi discord`

Similar steps for installing Brave, but you must add a template. I am using [this](https://codeberg.org/mobinmob/abyss-packages) one.

2. launch the application
3. Play video/audio or join a call. No audio produced

I have tested this only occurs with packages installed through this medium. I installed Firefox using the normal package manager `sudo xbps-install -S firefox` and audio works just fine.

**Comment by Duncaen** [comment]
`firefox` is actually build from void-packages, which works fine. discord and brave both are actually not build at all, they are just binaries that get repackages, xbps-src/void-packages has not influence over how audio works with them.

There is some issue with your system or the audio setup your use that is specific to your system and not a general issue as described in this thread.

See the documentation https://docs.voidlinux.org/config/media/index.html and make sure you've setup pulseaudio or pipewire correctly. Otherwise open an issue in a support forum in the github discussion or on reddit, this is not really a bug report/issue for this repo.
