### ISSUE TITLE
`build_helper=qemu` has no effect with `build_style=cmake`?

### ISSUE THREAD

**Issue by MIvanchev** [void-linux/void-packages#48034]
I'm trying to build LibreSprite here https://github.com/void-linux/void-packages/pull/48030 but the cross-compiling checks are failing because the build depends on a compiled binary. I'm setting `build_helper=qemu` in the template and the host dependency is added but QEMU is not used to run the custom command here: https://github.com/LibreSprite/LibreSprite/blob/v1.0/src/app/CMakeLists.txt#L10. Could it be that the `build_style` script is broken somehow?

**Comment by oreo639** [comment]
That is an issue with LibreSprite's cmake stuff.

The `add_custom_command()` calls do not specify a target with CROSSCOMPILING_EMULATOR enabled, so, from my understanding qemu won't be used.
See here for more information:
https://cmake.org/cmake/help/latest/variable/CMAKE_CROSSCOMPILING_EMULATOR.html

**Comment by chrysos349** [comment]
> Could it be that the `build_style` script is broken somehow?

no, it's not broken. see here - https://github.com/void-linux/void-packages/pull/48030#issuecomment-1874765705

**Comment by MIvanchev** [comment]
Thanks to you both @chrysos349 and @oreo639!! It worked but I was somehow expecting for the emulation to happen automatically. At least that's what the docs on this property say https://cmake.org/cmake/help/latest/prop_tgt/CROSSCOMPILING_EMULATOR.html but I guess one has to set it manually.

**Comment by sgn** [comment]
- No, it's not broken, `CROSSCOMPILING_EMULATOR` works
- No, your reading in https://cmake.org/cmake/help/latest/prop_tgt/CROSSCOMPILING_EMULATOR.html is not wrong, you're reading it correctly
- However, it's not simply like that.
- In order to ask cmake use `CROSSCOMPILING_EMULATOR` to run those foreign executable, you need to tell cmake to run a target, instead of running some random files.

For example: https://github.com/fcitx/fcitx5/blob/1bf0cebe286aeeb87f9b7ae7e4ad69107abb095a/src/modules/spell/CMakeLists.txt#L24-L45

In your case, remove `${CMAKE_BINARY_DIR}/bin/` from https://github.com/LibreSprite/LibreSprite/blob/e3c4506ebc8f5a25a3e558c9d482445b7bc193be/src/app/CMakeLists.txt#L12 may work (untested)
