### ISSUE TITLE
runit and PR_SET_NO_NEW_PRIVS

### ISSUE THREAD

**Issue by grapeli** [void-linux/void-packages#4926]
Can I run a runit with restriction "no_new_privs".
I tried using setpriv --no-new-privs /sbin/runit-init
and this simple "wrapper" (linked static).
https://gist.github.com/vi/f977cc3097d47b07c3ad
Without success. Maybe I'm doing something wrong, or I do not know something (runit can not be run with the a "helper-wrapper")?               

Systemd from the v239 version allows such a start (NoNewPrivileges=yes). I tested (under Archlinux) and everything works as I expected (including Xorg start with user rights).

Linux allows this from version 3.5 (from 2012).
Chrome OS starts init in such a sandbox from the beginning (7 years ago).

**Comment by CameronNemo** [comment]
Can you tell me what happens when you try this?

**Comment by grapeli** [comment]
Ok. For now, it is not a problem in Runit.
Somewhere I make a mistake, the kernel does not find init. At the start I get a:
kernel panic - not syncnig: Requested init /sbin/init-helper /sbin/runit-init failed (error -2)

Kernel is without initrd, everything is built-in (Void starts and works without problems) the only thing I change is add to boot parameters:
"init=/sbin/init-helper /sbin/runit-init" or
init="/sbin/init-helper /sbin/runit-init".
Kernel is in a different place (partition) than rootfs and init - this is the reason for my failure.

**Comment by CameronNemo** [comment]
I don't believe the kernel command line unit field allows specifying arguments. Only a binary.

**Comment by grapeli** [comment]
That's right!
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/admin-guide/kernel-parameters.txt#n1629
https://unix.stackexchange.com/questions/428347/how-to-pass-arguments-to-a-linux-kernel-init-bootparam

I started runit with the help of a shell script.
Runit-init as the process > 1 accepts only the halt (0) and reboot(6) parameters.
Runit is a special program.
**-runit: fatal: must br run as process no 1.**

Without modification of the source code, it is rather impossible. I give up.
Thanks for guiding on the right tracks.

**Comment by maxice8** [comment]
you can try `exec` into runit-init as it will replace the current process instead of spawing a new one

#!/bin/sh
exec privhelper runit-init

**Comment by grapeli** [comment]
Thanks a lot. Now it is working. I knew about exec, just something did not matter to me that it would still be pid # 2.
I used this simple "helper" https://gist.github.com/vi/f977cc3097d47b07c3ad
The system started correctly, I logged in as a user - attempts to use su - and sudo were unsuccessful, i.e. a success.

An attempt to use setpriv fails.
setpriv: activate capablities: No such file or directory

**Comment by grapeli** [comment]
I'm trying to take a step forward and running X server under user account.
I changed the entry in the Xwrapper.config file to "needs_root_rights = no".
I use the modesetting driver because only this one worked under Archlinux (the version of the kernel, Xorg is the same, under the Void there is no systemd).
The user belongs to video and input groups.

startx -- :0 vt2
tail .local/share/xorg/Xorg.0.log
(EE) modeset(0): drmSetMaster failed: Permission denied

strace -ff -o xorg.log startx -- :0 vt2
grep denied xorg.log
xorg.log.1530:setpriority(PRIO_PROCESS, 1531, -1)     = -1 EACCES (Permission denied)
xorg.log.1531:openat(AT_FDCWD, "/proc/mtrr", O_WRONLY|O_LARGEFILE|O_CLOEXEC) = -1 EACCES (Permission denied)
xorg.log.1531:openat(AT_FDCWD, "/proc/mtrr", O_WRONLY|O_LARGEFILE|O_CLOEXEC) = -1 EACCES (Permission denied)
xorg.log.1531:ioctl(10, DRM_IOCTL_SET_MASTER, 0)      = -1 EACCES (Permission denied)

https://bugs.gentoo.org/635102#c18

**Comment by etosan** [comment]
@grapeli just curious what's the point of this exercise? I mean I fail to understand why are you setting it on init level?

Once successfully set on init (PID1), you won't able to suid at all (eg invoke passwd or whatever) so the machine becomes unmanageable without booting it other way (rescue key + chroot, original init). Or do you plan using it for runit in containers?

Regarding `init=` kernel command line parameter, value of that key/value pair is expected to be full path, as you noticed. So `init="/sbin/init-helper /sbin/runit-init"` will try to open file `/sbin/init-helper /sbin/runit-init`, which does not exist, naturally. If  am not mistaken you should have `init=` as last parameter for minimal problems. If you really want to pass parameters to init, my memory is bit hazy about the details, but I think every `word` after `init=` is passed into init's `argv` as expected. The trick lies in having them as last components of kernel line.

For more sensible approach I would suggest to use your `non_new_privs` **`chainer`** in runfile of the service you want to "isolate". That way you can control `new_privs` removal and privdrops on service level:

**`/etc/sv/my-no_new_privs-xorg/run`**
```lang=sh
#!/bin/sh
exec \
  privhelper  \
  chpst -u :myuser:video \
  /usr/libexec/Xorg  
```

Sadly shell does not allow detailed comments in `exec()` chains, so I will use `execline` to clarify further.  `execline`'s `execlineb` "interpreter" (hint: it is not interpreter) works by constructing very long `argv` vector defining single, long, `exec()` chain and then `exec()`'s into it. It also allows you to use comments in there and whatnot, so you don't need to write overly long "undocumented" exec chains in shell.

So this runfile version allows me to explain steps better:

**`/etc/sv/my-no_new_privs-xorg/run`**
```lang=sh
#!/bin/execlineb -P
# at this point proctree looks like this:
#  runit-init  as [root:root new_privs=yes]
#  └─ runsvdir -P /run/runit/runsvdir/current as [root:root new_privs=yes]
#     └─ runsv my-no_new_privs-xorg as [root:root new_privs=yes]
#        └─ ./run (aka this execlineb script) as [root:root new_privs=yes]

privhelper  # this will prevent this process 
            # to gain new privs in the future 
            # so after this line 
            # we are running as [root:root new_privs=no]
  chpst -u :myxuser:video # now we privdrop process owner into more limited user (myxuser)
                          # I think to manipulate DRI video devices you must be in `video` 
                          # group maybe that will solve your problem 
                          # (but maybe not - maybe Linux + DRI driver needs `root` to modeset)
                          #
                          # anyway, after this line 
                          # we are running as [myxuser:video new_privs=no]
                          #
                          # because we privdropped, it should be impossible to invoke
                          # sudo or anything that setuids or gain new privs after this
                          # (if it is still possible after this, it is kernel bug)
    /usr/libexec/Xorg # finally we exec() into xorg process, replacing current process with X
                      #
                      # because we privdropped, we don't need silly /usr/libexec/Xorg.wrap 
                      # (it wouldn't work anyway, as it's setuid root and we removed that with new_privs=no!) 
                      # nor /usr/sbin/Xorg, which is yet another script around /usr/libexec/Xorg.wrap

# so at this point proctree looks like this:
#  runit-init  as [root:root new_privs=yes]
#  └─ runsvdir -P /run/runit/runsvdir/current as [root:root new_privs=yes]
#     └─ runsv my-no_new_privs-xorg as [root:root new_privs=yes]
#        └─ /usr/libexec/Xorg as [myxuser:video new_privs=no]
```

I hope, I got my point across. Also, this is, what I believe, that systemd really does when you do `NoNewPrivileges=yes` eg it does first parts of the `execlineb` script on it's own and then execs into your `ExecStart=` process. I doubt it sets PR_SET_NO_NEW_PRIVS  on itself (PID1) otherwise it would be unable to spawn services where you want to be able do new_privs.

Now this is fine for "simpler" services but there are few problems with "sandboxing" X like this. Don't take me wrong, it's not bad to isolate X this way. Go for it.

The problem lies elsewhere - sandboxing X does not actually prevent programs in your "xsession" (that is how people tend to call it) from gaining new_privs. In this example X could be run as `nobody` (even better under someone like `sys-xorg`) and you can still talk to it from your own user. Or rather any program with `DISPLAY=` env variable set properly, access permissions to X11 unix socket and proper `Xauthority` can connect to that display. It's not like Xorg itself spawns it's children.

**The truth is there is no xsession!** 

So where does this notion of `xsession` comes from?

Usually it is done by `startx` wrapper, or, on user friendly desktops, by so called `display manager`.

These two tools, `startx` and especially `display manager` are something between `runit` (`daemontools`, `s6`) and graphical X application. Looking at them with `runit vision` uncovers they are, in fact `supervisors` (and are often done poorly too).

So both `display manager` and `startx`, are essentially supervisors like `runit`, that start and supervise Xorg in similar way that `runit` supervises our `my-no_new_privs-xorg` service. 

In case of `display manager`(DM) this `supervisor` (eg DM) itself connects to this X server that it itself spawned and supervises, and uses this connection to display login GUI. Older display managers do this as `root` from the same process, more modern ones follow better practice, and `fork()` so called `greeter` child that draws that logon GUI from DM's sub-process, running under user with lover level privileges. When you enter the proper user name and password tuple into this GUI/greeter, it is by some ipc sent over to `supervisor` part of DM. if valid, DM finally forks second child under **your username** and it is this child that starts your "xsession". This `xsession` is process, that is roughly equivalent to 'init for X proctree', that will spawn the rest of your GUI/DE. Actual xsession itself, again, can be "defined" in zilliard places (.xinitrc, but also freedesktop crap) but in the end it usually ends up execing into small wrapper like `startlxde` that in turn execs into `lxsession`shim. This final `*session` shim process is a linchpin that holds your "xsession" together. Phew. 

Number of lingering shell processes in between stages of such contraption is directly proportional to quality of DE and distribution you are using.

This still, however, is not full image. On `systemd` infected systems, this whole dance is further complicated by `logind` thing - which runs as it's own `systemd` service, and is responsible to control access bits to `/dev` device nodes (for mouse input, keyboard input, maybe video cameras and who knows what other shit) and some more (magic sauce), to construct concept of `login session`, enveloping our `display manager` (DM) or `startx` into yet another warm layer of poo. Don't get me wrong, it's solid idea actually, it's just that implementation is lacking a bit (like it communicates over dbus) and is "very well documented" (not). In `systemd` land DM "service" (eg xorg supervisor + login GUI + xsession) must somehow associate itself with `login session` through wonderful magic of `dbus` apis, otherwise `xsession` will not work.

In case of `startx` the whole dance is bit less convoluted, because `startx` needs only to supervise exactly two children - `Xorg` and `xsession` linchpin. No "login GUI" shenanigans needed. `logind` thing is sidestepped elegantly as well, because `login session` is associated beforehand (maybe at a tty service level  + pam magic perhaps, who knows?). Doesn't really matter for us.

Because majority of these things came into being when runit-like service supervision already existed (`daemontools`, `runit`, `s6`) but was still best kept secret of unix zen (and this didn't change until `systemd` bulldozer arrived), they are what they are.

Fortunately, in our `runit` world, we can throw most of this crap right out of window. Things have potential to be **simple** again, so most straightforward and naive solution is to compose your "DE-like-thing" from **two** `runit services! 

The one we already have, is used to supervise xorg, and second, the new one, will be used to supervise "xsession" of given user.

So if you want to sandbox `xsession`, which I guess is what you really want, you just need to repeat same thing we did with `xorg` service with some more sauce in between:

`/etc/sv/myuser-xsession/run`
```lang=sh
#!/bin/execlineb -P

# we are running as [root:root new_privs=yes]

privhelper # we are running as [root:root new_privs=no]

  chpst -u myuser # this should privdrop into myuser
                     # if I remember correctly chpst will set proper aux groups from passwd db
                     # if no groups are specified
  ... # here should be come some magic sauce to import proper DISPLAY=
  ... # and user level X session env vars, run shell profiles and other crap
  start*de # not sure if this exec()s or leaves lingering shell in-between
  # it obviously depends on quality of your DE implementation

# once session is spawned, proctree should look like this:
#  runit-init  as [root:root new_privs=yes]
#  └─ runsvdir -P /run/runit/runsvdir/current as [root:root new_privs=yes]
#     └─ runsv myuser-xsession as [root:root new_privs=yes]
#        └─ *session as [myuser:bla,bla,bla new_privs=no]
#                ├─ crappy-panel
#                ├─ crappy-widget
#                └─ xterm as [myuser:... new_privs=no]
#                       └─ shell as [myuser:... new_privs=no] <- no sudo, no suid etc
```

So there you have it. If we take into account that latest `daemontools` release is from 2001, and that it is possible to run whole machine under `svscan` from `daemontools` as PID1 since this page came into existence: http://code.dogmap.org/svscan-1 (which I would date somewhere around 2003-2005) your guesstimate of "possibility" timeframe is almost one decade off. 

Conceptually this all is very well possible at least since 2005 (if not taking into account missing new_privs bit, nonexistence of rootless X at that time and Linux missing KMS at that time, of course). So "it being possible" is not the problem. Problem is coming up with trimmed down reusable interfaces and properly split modular designs.
