### ISSUE TITLE
Issues with resizing X11/XWayland gtk4 windows on first login after restart

### ISSUE THREAD

**Issue by Jaymz665** [void-linux/void-packages#49575]
### Is this a new report?

Yes

### System Info

Void 6.6.22_1 x86_64 GenuineIntel notuptodate rrrmFFFF

### Package(s) Affected

gtk4-4.14.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://gitlab.gnome.org/GNOME/gtk/-/issues/6558

### Expected behaviour

It is expected that on windows open, for example, on the same qt, you can change the size by simply dragging the left mouse button over the edges and corners.

### Actual behaviour

At the moment, on gnome 45.5 and gnome 46.0 (compiled from murge templates), it is noticed that when you first log into the shell, windows opened in qt or wine do not interact correctly. It is impossible to change the window size using the usual mouse action (edge or corner). Windows are open in wine as if they physically have the wrong size (when displayed correctly) and the mouse, when interacting, seems to go beyond the edges of the window.
Corrected by relogin.

### Steps to reproduce

Run gnome-45.5 or higher
Launch an application written in qt

**Comment by oreo639** [comment]
> Gnome 45.5 is a problem with windows not based on gtk

It is the exact opposite, it specifically affects gtk4 windows.

> Launch an application written in qt

This happens for qt applications using SSDs which uses gtk4 in gnome 44+.


This issue only applies to X11, and not Wayland (although it does affect XWayland, which if you are seeing SSDs, the application is using XWaland).
This is the upstream issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/6558

It is likely due to some dbus activation not having finished yet.

**Comment by oreo639** [comment]
I updated the title, please let me know if it is incorrect.

**Comment by Jaymz665** [comment]
Yes, I think that's right.

**Comment by chrysos349** [comment]
> it specifically affects gtk4 windows.

Not in my case. gtk4 windows are not affected at all.

It looks like the bug affects apps run under XWayland (run `xlsclients` to determine which apps run under XWayland). 

In my case, the buggy apps are the gtk3 app, the electronjs app, and the app run under wine. 
When maximized, the apps can't be closed with the mouse, but clicking on the close button instead switches to the window in the background. Also parts of the interface of the electronjs apps can't be accessed via mouse (again, clicking switches to the windows in the background).

**Solutions:**
- logging out, and logging back in solves the issue
- waiting a bit before first logging in after a restart
- downgrading to `gtk4-4.12.5` (see my comment https://github.com/void-linux/void-packages/pull/49428#issuecomment-2020596662)

**Comment by oreo639** [comment]
Alright, I looked more in to this and it seems with gtk4-4.14, for SSDs this issue persists until you log out and back in, whereas on gtk4-4.12, this issue does not persist for SSDs if you close and re-open the application, but the issue still happens if you auto-launch the SSD application.

For auto-launched libadwaita applications on gtk4-4.12, they can still be resized as they have appear to have visible borders in this circumstance, whereas with gtk4-4.14, they do not. (same version of libadwaita)

**Comment by oreo639** [comment]
> Not in my case. gtk4 windows are not affected at all.
>
> It looks like the bug affects apps run under XWayland (run xlsclients to determine which apps run under XWayland).

Hence why I specified X11/XWayland gtk4 windows. It doesn't affect Wayland gtk4 windows..

> When maximized, the apps can't be closed with the mouse, but clicking on the close button instead switches to the window in the background.

Thanks for pointing this out, I've run in to that issue for a while with auto-started applications using SSDs. Recently, I noticed that simply closing the window and reopening it doesn't work around it anymore, which is consistent with the behavior I noticed when experimenting rn.

> the gtk3 app

What application is this?

**Comment by chrysos349** [comment]
> What application is this?

`deluge-gtk-1.3.15` (AppImage)

**Comment by oreo639** [comment]
> `deluge-gtk-1.3.15` (AppImage). It's gtk2, actually

Afaict, deluge-gtk uses SSDs on its main window. (I have a custom gtk4 css so it is apparent when gtk4 is being used)

**Comment by chrysos349** [comment]
Yes, ALL apps run in XWayland use SSDs.

**Comment by oreo639** [comment]
> Yes, ALL apps run in XWayland use SSDs.

That's just not true. A lot of X11 applications happen to use SSDs due to individual preferences, but that doesn't mean all X11 applications use SSDs and many gtk3 applications do not even when running under X11. (Wayland applications can't on GNOME because GNOME explicitly does not support it)

In the case of deluge, it explicitly sets GTK_CSD to 0 (which disables CSDs on X11): https://github.com/deluge-torrent/deluge/blob/7f3f7f69ee78610e95bea07d99f699e9310c4e08/packaging/win/pyi_rth_gtk_csd.py#L3

gtk2 applications do always use SSDs and only support X11.

**Comment by chrysos349** [comment]
> That's not true.

Thanks for the explanation!

> In the case of deluge, it explicitly sets GTK_CSD to 0 (which disables CSDs on X11): https://github.com/deluge-torrent/deluge/blob/7f3f7f69ee78610e95bea07d99f699e9310c4e08/packaging/win/pyi_rth_gtk_csd.py#L3

Isn't this for packaging deluge-gtk for windows?

**Comment by oreo639** [comment]
> Isn't this for packaging deluge-gtk for windows?

Yeah, you're right, sorry. Not entirely sure what deluge-gtk is doing to disable CSDs by default on Linux.

**Comment by chrysos349** [comment]
`gtk4-4.14.2` is out. it doesn't fix the issue.

**Comment by oreo639** [comment]
https://gitlab.gnome.org/GNOME/mutter/-/issues/3417

**Comment by oreo639** [comment]
Alright the issue has been diagnosed, a patch has been submitted upstream but I will wait for some feedback before applying it downstream: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/7145

**Comment by oreo639** [comment]
Can you verify this works for you: https://github.com/void-linux/void-packages/pull/49869

**Comment by chrysos349** [comment]
> Can you verify this works for you: #49869

it did for me. great job debugging the issue!

**Comment by Jaymz665** [comment]
@oreo639 I confirm that it works for me too! 👍
