### ISSUE TITLE
Raspberry Pi: `08-sysctl.sh` fails to load rules at boot

### ISSUE THREAD

**Issue by camj2** [void-linux/void-packages#50669]
### Is this a new report?

Yes

### System Info

Void 6.1.77_1 aarch64-musl Unknown uptodate F

### Package(s) Affected

rpi-kernel-6.1.77_1

### Expected behaviour

`/etc/runit/core-services/08-sysctl.sh` loads rules from `/etc/sysctl.conf`.

### Actual behaviour

Some rules, such as `net.ipv6.conf.all.forwarding = 1`, fail to load at boot. Running `sysctl -p` manually loads them fine just though.

![sysctl](https://github.com/void-linux/void-packages/assets/139597610/058d6904-a273-48ae-8ac4-22131ad591e8)

### Steps to reproduce

1. Add `net.ipv6.conf.all.forwarding = 1` to `/etc/sysctl.conf`.
2. Reboot.
3. `sysctl -a | grep net.ipv6.conf.all.forwarding` shows the rule wasn't applied at boot.

**Comment by classabbyamp** [comment]
the issue is that the rpi kernel has the ipv6 module built as a module, not as built-in (like the regular kernels). this causes the module not to be loaded at the time the sysctl command is run during boot.

the next rpi kernel will have this fixed: https://github.com/void-linux/void-packages/pull/50647/files#diff-7c06a56d03c82f4f91449e0b8baba00fa54433735eee8b84183aa75909a25b34R137

but I guess you could put `ipv6` in [`modules-load.d`](https://man.voidlinux.org/man8/modules-load.8) for now

**Comment by camj2** [comment]
Great, thank you!
