### ISSUE TITLE
xbps-src: bootstrap fails

### ISSUE THREAD

**Issue by rawhuul** [void-linux/void-packages#51172]
### Is this a new report?

Yes

### System Info

Void 6.6.35_1 x86_64 GenuineIntel uptodate rF

### Package(s) Affected

binutils-2.41

### Expected behaviour

During the bootstrap process, the `binutils` package encounters post-compilation failures that need to be resolved for successful bootstrap.

### Actual behaviour

![Screenshot from 2024-07-09 15-00-51](https://github.com/void-linux/void-packages/assets/84739019/ea68dab6-093c-483c-8bb2-4098b1213555)

### Steps to reproduce

1. Clone the repo and cd into it
2. Run `./xbps-src bootstrap`

**Comment by rawhuul** [comment]
Yes @classabbyamp, using `bootstrap` was intended. You can find logs [here](https://paste2.org/nGUVF9vE) (I only included for `binutils` only)

**Comment by classabbyamp** [comment]
```
../../gold/compressed_output.cc:26:10: fatal error: zstd.h: No such file or directory
 26 | #include <zstd.h>
 | ^~~~~~~~
compilation terminated.
```

**Comment by rawhuul** [comment]
Cool, how come I overlooked it. So, `bootstrap` basically builds `binutils` first and fails as it depends on `libzstd-devel`, which will compile later. Right?

**Comment by oreo639** [comment]
`binary-bootstrap` downloads the packages necessary for setting up a chroot.
`bootstrap` builds the compiler and libraries necessary for setting up a chroot using the host system's compiler, tools, and libraries (with features missing, so that you can then build the compiler and libraries in a proper chroot with all supported features afterwords and use those for the chroot).

In this case, since you are building binutils outside of a working chroot is is trying to find libzstd from your machine, this is expected.
You probably want `./xbps-src binary-bootstrap` which pulls the packages from the repos and uses those to set up the chroot.

**Comment by rawhuul** [comment]
Okay, got it @oreo639

**Comment by sgn** [comment]
https://github.com/void-linux/void-packages/commit/5704c8e5608ad53a3538b0691794c3170f27a298
