### ISSUE TITLE
Package request: Hyprland (wlroots-independet)

### ISSUE THREAD

**Issue by Stridsvagn69420** [void-linux/void-packages#51610]
### Package name

hyprland

### Package homepage

https://github.com/hyprwm/Hyprland

### Description

Hyprland is an independent, highly customizable, dynamic tiling Wayland compositor that doesn't sacrifice on its looks.

There has already been a Package Request for Hyprland (see #37544), but that was over 2 years ago when it was still depending on an untagged wlroots version. However, about two weeks ago, Hyprland has become wlroots-independent (see [here](https://hyprland.org/news/independentHyprland/)). Basically, it is still wlroots-compatible, but it does not require wlroots anymore.
 
I wasn't able to send a bump message in the original Package Request, so I decided to make a new one.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

No

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/issues/50824
https://github.com/void-linux/void-packages/issues/51414

**Comment by Stridsvagn69420** [comment]
So it's also not planned to package it starting with 0.42.0?

**Comment by classabbyamp** [comment]
correct.

**Comment by 0x62797465** [comment]
Is there any real reason?

**Comment by itshog** [comment]
Sorry, could anyone elaborate further on this decision? I'm not trying to start an argument or anything, I'm just curious about the reason for not wanting to package Hyprland.

**Comment by Stridsvagn69420** [comment]
I assume it's more because of the entire drama that happened and not really building Hyprland itself.

**Comment by EmilyShepherd** [comment]
@classabbyamp I wonder if I might be able to request again if it is possible to have further context for this decision.

Before I continue I want to be very clear: I can only speak for myself but, as @itshog as said, I completely agree that in the end of the day the project is managed by the maintainers, so I for one will respect the decision of the maintainers. I cannot, and indeed have no interest in, forcing Void to do one thing or another. Having said that, I think giving the community an insight into _what that decision actually is_ might be helpful.

When this was discussed pre Hyprland 0.42 the reason given for the non-inclusion was the issue of Hyprland using a non-tagged version of wl-roots, therefore making it a PITA to build against either a system wlroots, and against the philosophy of most distros to allow the project to bundle its own version. A perfectly reasonable stance for a distro to take.

In all of those discussions, the implication seemed to be that if that situation ever changed with the upstream project, that stance may be reconsidered. This is summed up well by the closing line from @JamiKettunen in #37544 before the issue was locked:

> it won't be in the repo until the situation changes.

Now that the situation has changed, we have seen a few follow on requests asking for Hyprland again. Some of these requests were made by people who were aware of the original reason, and proceeded to raise issues post 0.42 because they assumed that that reason was no longer a blocker, because of statements made by project Members and Contributors.

All of these post 0.42 requests have been closed, without explanation. Most issues link back to #50824 which was closed by @ahesford with the statement:

> We have no interest in maintaining a hyprland package.

I'll say again: Void has the right to hold whatever stance it wants. Void even has the right to not elaborate further if it does not wish to. However, I would gently suggest that if you don't elaborate or put a note somewhere, you are likely to continue to get people asking.

Is this because of the freedesktop situation / toxic community suggestions of hyprland? CoC breaches, or even culture fit reasons, are a perfectly valid reason for one community not to work with another.

Is it, perhaps, the opinion of Void is that the way hyprland ported wl-roots into its codebase still kind of counts as a sneaking inclusion of a should-be system library?

As Void will not be including hyprland officially, would an alternative solution be to add a note somewhere, nudging users towards a third party package for Void such as: [Makrennel/hyprland-void](https://github.com/Makrennel/hyprland-void), which is what the hyprland project itself links to on its installation page for Void Linux. This would at least serve to satisfy those that want it, and would reduce the load on you for people asking you for it repeatedly.

Apologies, also, for the necrobump. This was the most recent unlocked issue, and I felt that opening a new issue for this given Void's clear unhappiness with the repeat issues raised over this topic would be bad form.

--
_I have daily driven Void Linux on both my laptop and my desktop for many years. I love the project and am vastly appreciative of the work you do. Projects like Void make linux the awesome ecosystem that it is._ <3
