### ISSUE TITLE
IRSSI not cross compiling perl

### ISSUE THREAD

**Issue by sww1235** [void-linux/void-packages#5353]
### System

* xuname:  
Void 4.14.84_1 armv7l-musl  uptodate rF
* package:  
irssi 1.1.1

### Expected behavior

perl scripts work on all architectures.

### Actual behavior

when trying to load the perl module

`Irssi: Error loading module perl/core: Error loading shared library /usr/lib/irssi/modules/libperl_core.so: No such file or 
          directory`

as seen in [the template](https://github.com/void-linux/void-packages/blob/master/srcpkgs/irssi/template) the perl module is not loaded if xbps-src is cross compiling. 

according to [this](https://github.com/irssi/irssi/blob/master/INSTALL): static perl libs might have to be enabled instead.

### Steps to reproduce the behavior

`xbps-install irssi`
`irssi`

then try and load the perl module within in irssi using command `/load perl`

**Comment by newbluemoon** [comment]
I don’t think this is easily feasible (either dynamic or static linking), because in a cross build `configure` isn’t aware of the target perl and will always use the host perl (cf. irssi’s `configure` script line 13916ff).

I think for cross builds a perl setup similar to how it’s done in the perl-module build style in `common/build-style/perl-module.sh` would be necessary. But most likely this would require heavy patching and I don’t think it would be worth the trouble since it’s a (relatively) small package and building it yourself natively even on a Raspberry Pi should be no problem. :)
