### ISSUE TITLE
Something weird in fontconfig

### ISSUE THREAD

**Issue by philipgg** [void-linux/void-packages#5533]
### System

* xuname:  Void 4.19.7_1 x86_64 GenuineIntel uptodate FFFFFFFFFFFFFFFFFFFFFFFF
  *output of ``xuname`` (part of xtools)*
* package:  fontconfig-2.13.1_1
  *affected package(s) including the version*

### Actual behavior
````
$ cat /var/cache/fontconfig/CACHEDIR.TAG
Signature: 
# This file is a cache directory tag created by fontconfig.
# For information about cache directory tags, see:
#       http://www.brynosaurus.com/cachedir/
````

And if you go to the website, you'll see:

**Yale ITS**

**Web Page Blocked**

Access to the website you have attempted to reach has been blocked from the Yale network.
Additional information about Yale University`s filtering policies can be found here.
If you have any questions or believe you have received this message in error, please
contact the ITS Service Desk at 203-432-9000 or helpdesk@yale.edu

**URL:** www.brynosaurus.com/cachedir/

**Category:** malware

:confused:

**Comment by pobetiger** [comment]
If you go to the website without the www, it takes you to a page that looks a bit more like the originally intended page.

Either there's a typo in the package or the www page got disabled?

It does look weird.

Someone on the Rpi forum mentioned this: http://www.brynosaurus.com/cachedir/

The answer questioner was opening bin files with text editor and the answerer did not sufficiently address the issue if there's suspicious about the domain.

But it looks like there's some kind of misconfiguration on the Yale's website that's prohibiting this site:

http://www.brynosaurus.com/cachedir/


But allowing these sites:
http://brynosaurus.com/cachedir/
http://www.brynosaurus.com/

All of which goes to Profession Bryan Ford's website. But I don't know why Yale is the one that's doing the blocking. Since he went to MIT and works in a Switzerland company?
