### ISSUE TITLE
make doesn't seem to use g++ for perl-Wx (perl-module)

### ISSUE THREAD

**Issue by Gigahawk** [void-linux/void-packages#627]
### System

* xuname:  
  * Void 4.16.14_1 x86_64 GenuineIntel notuptodate rrm

I'm trying to create a [template](https://github.com/Gigahawk/void-packages/blob/perl-Wx/srcpkgs/perl-Wx/template) for the Wx module on [CPAN](https://metacpan.org/pod/release/MDOOTSON/Wx-0.9932/Wx.pm).

Running `./xbps-src install perl-Wx` fails in do_build() with lines like
```
/usr/include/wx-3.0/wx/buffer.h:19:1: error: unknown type name 'class'; did you mean 'OPclass'?
 class WXDLLIMPEXP_FWD_BASE wxCStrData;
 ^~~~~
 OPclass
```
```
/usr/include/wx-3.0/wx/buffer.h:27:1: error: unknown type name 'namespace'; did you mean 'isspace'?
 namespace wxPrivate
 ^~~~~~~~~
 isspace
```
```
/usr/include/wx-3.0/wx/stringimpl.h:66:10: fatal error: string: No such file or directory
 #include <string>
          ^~~~~~~~
```

This looks like the compiler is trying to compile C++ files with gcc instead of g++.

Full log: https://pastebin.com/CbRgcXi5

**Comment by Gigahawk** [comment]
Ok I seem to have fixed it by replacing `do_build()` with just a simple make call instead of using the one in the script with all of the other variables and flags and things. It seems to work for now but I'm assuming it's not an optimal solution.

**Comment by newbluemoon** [comment]
As a workaround you could copy `do_build()` from `common/build-style/perl-module.sh` and replace `CC="$CC"` with `CC="$CXX"`, etc., like e.g.

```
do_build() {
	make CC="$CXX" LD="$CXX" CXXFLAGS="$CXXFLAGS" OPTIMIZE="$CXXFLAGS" \
		LDFLAGS="$LDFLAGS -L${XBPS_CROSS_BASE}/usr/lib -lperl" \
		LDDLFLAGS="-shared $CFLAGS -L${XBPS_CROSS_BASE}/usr/lib -lperl" \
		${makejobs} ${make_build_args} ${make_build_target}
}
```

But maybe there’s a better way; I’ll keep on looking. :)

And please remove `post_extract()`: that’s what the `wrksrc` variable is for. E.g.:
`wrksrc="${pkgname#perl-}-${version}"`

`homepage` should be `https://metacpan.org/release/Wx` and use `$CPAN_SITE` for distfiles, like
`distfiles="${CPAN_SITE}/Wx/${pkgname#perl-}-${version}.tar.gz"` or when the `pkgname` is short like
`distfiles="${CPAN_SITE}/Wx/Wx-${version}.tar.gz"`

Don’t know how much WIP this is, or if you’re planning on opening a PR, but the license is wrong, should be
`Artistic-1.0-Perl, GPL-1.0-or-later`. (Didn’t check the others.)

Similar for the other new required perl modules. However, the other new packages (unlike this one) should also be `noarch=yes` because they don’t provide any binaries, just perl scripts.

**Comment by Gigahawk** [comment]
Yea my bad I'm super new at this, PR for this is #634, working on fixing everything now.
