### ISSUE TITLE
package request: picprog

### ISSUE THREAD

**Issue by aGaTHoS** [void-linux/void-packages#7768]
http://hyvatti.iki.fi/~jaakko/pic/picprog.html

PIC16, PIC12 and PIC18 microcontroller programmer for Linux and Windows/Cygwin.

**Comment by bobertlo** [comment]
I got this to compile (finally) but then find out it's using inline assembly and just all messed up, so it's not going to work for other platforms. I will give you the template that works on x86_64-glibc though:

```
# Template file for 'picprog'
pkgname=picprog
version=1.9.1
revision=1
short_desc="PIC16, PIC12 and PIC18 microcontroller programmer"
maintainer="Robert Lowry <bobertlo@gmail.com>"
license="GPL-3.0-or-later"
homepage="http://hyvatti.iki.fi/~jaakko/pic/picprog.html"
distfiles="http://www.iki.fi/hyvatti/pic/picprog-${version}.tar.gz"
checksum=057572133390122051622c412b8b3abeb38487a205645c427252ec61c38304e4

do_build() {
        echo "CXX=${CXX}" >> Makefile
        make dep
        make
}

do_install() {
        vbin picprog
        install -m644 -D *.1 ${DESTDIR}/usr/share/man/man1
}
```

**Comment by aGaTHoS** [comment]
Sorry I'm new in void linux, what its supposed i have to do with this, just put it somewhere in  my pc I guess and compile myself the package and install locally?
If some package does not compile in all platforms is not aded to repositories?

**Comment by bobertlo** [comment]
That's as far as I got with a package template. It looks like it simply will not compile to other platforms, and doesn't want to even cross compile for i686 and musl x86 platforms. If you wanted to read the documentation on this repo, it is not hard to copy that into `srcpkgs/picprog/template` and build yourself a package.

Maybe someone smarter than me could get it to compile on all the x86 platforms and it could be considered for inclusion. The source is not maintained, so that makes packaging it a tougher sell also.

**Comment by aGaTHoS** [comment]
ok
