### ISSUE TITLE
Package Request: rpi-kernel-4.19

### ISSUE THREAD

**Issue by 0x0f0f0f** [void-linux/void-packages#8030]
Related to issue [#6293](https://github.com/void-linux/void-packages/issues/6293#issuecomment-457699301).

As reported by @kervel, linux 4.19 from the raspberry GitHub fixes the ethernet driver not being loaded.

**Comment by Hoshpak** [comment]
I don't think we should have several versions of the rpi-kernel in the repository. Please report the issue upstream so it gets fixed. The rpi-kernel will be updated to 4.19 some day and in the meantime the issue should be solved for the existing kernel.

**Comment by Piraty** [comment]
ping @pbui , what do you  think?

Isn't upstream into fixing it for 4.14?

**Comment by pbui** [comment]
Upstream is preparing to move to 4.19: 

https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=224931&sid=26059e7ef06c11673e6e9c4d08a4e277

That said, it looks like it will be a few months yet before 4.19 is considered stable and upstream makes the switch.  Moreover, I am not sure if they are aware or working on the fix for the ethernet driver.

**Comment by pbui** [comment]
Please see PR #9047
