### ISSUE TITLE
distcc no longer works

### ISSUE THREAD

**Issue by youngjinpark20** [void-linux/void-packages#8238]
### Expected behavior
- distcc by enabling XBPS_DISTCC=yes

### Actual behavior
- distcc doesn't work until manually you manually chroot and install chroot-distcc.
- probably because someone removed chroot-distcc dependency #6562.
  
### Steps to reproduce the behavior
- Enable `XBPS_DISTCC=yes`
- Add host `XBPS_DISTCC_HOSTS="..."`
- Only compiles locally

**Comment by pullmoll** [comment]
I think we need to add the regular `distcc` into the chroot if `XBPS_DISTCC=yes` at some place.
The problem was that `chroot-distcc` introduced dependencies which could not be solved with `bootstrap=yes`  packages (automake and libtool).

The only other way out would be to revive `chroot-distcc` and put the `distcc` package's generated `configure` script into its `${FILESDIR}` to avoid running `./autogen.sh` when building the package. This would have to be done for every update of `distcc`.

**Comment by pullmoll** [comment]
I reintroduced `chroot-distcc` with the required files copied from the `distcc` package's generated files.
LMK if this solves the problem, i.e. if `chroot-distcc` is working again for you.

**Comment by youngjinpark20** [comment]
works now :+1:
