### ISSUE TITLE
Package Request: Anaconda IDE for Python

### ISSUE THREAD

**Issue by OtakuSenpai** [void-linux/void-packages#8892]
Description:
---------------

   Anaconda IDE is a Python IDE for IT professionals or Data Scientists working on Machine Learning or AI in general.

URL: 
------
https://www.anaconda.com/

Source:
----------
Unknown

Use cases:
--------------

Will greatly help ML/AI students/professionals/scientists who are also using Void Linux.

**Comment by Johnnynator** [comment]
Isn't Spyder the IDE https://github.com/spyder-ide ? Anaconda is a Python distribution that ships spyder + python + python libs together. I'm not sure if there is any advantage to package Anaconda since it seems to be intended to be distribution independent and probably shoudln't be managed by a package manager (?).

**Comment by CameronNemo** [comment]
Pretty minimal build dependencies, but quite a few runtime dependencies.

https://github.com/spyder-ide/spyder#dependencies

**Comment by OtakuSenpai** [comment]
It is a one stop show for ML enthusiasts, using it will help them install everything from Jupyter to Spyder to Python3.
Consider another example. There is already a kotlin compiler in the repos, but we also ship IntelliJ Community edition, which ships a kotlin compiler with it.
Please consider this, it could greatly help.
