### ISSUE TITLE
Package request: Compiz 0.9.14

### ISSUE THREAD

**Issue by veyselerden** [void-linux/void-packages#9114]
A new compiz version released almost 1 week ago but you switched to compiz-reloaded. Since compiz-reloaded and compiz are two different version I think they should be seperated. They've ported a lot of stuff to new versions like gtk3 and python3 and removed old code so this is a really important version and should be landed on Void repos. 

https://launchpad.net/compiz

**Comment by ruegerjr** [comment]
Both 0.8 and 0.9 branches are in active development.  I will preface my remarks by pointing out I am only using XFCE, and mostly emerald for my compiz decorator.  After not trying it for 3 years or so, I installed compiz-0.9(.14) on one Arch partition, and compared it to compiz-reloaded on a second Arch partition, as well as compiz-reloaded on Void.  Compiz 0.9.14 ran fine, but certainly no better than compiz-reloaded.  I think compiz-reloaded still supports more plugins, although I rely mostly on cube plugins and wobbly windows, so have not tested that assertion.  I believe the version of compiz-reloaded built in Void uses the gtk3 version of Metacity,  and has been using python3 since at least 8.14. (Arch/AUR may still be using python2?).  That's not to say there isn't a compelling reason to add compiz 0.9, but please provide it, as I  am not seeing it.
