### ISSUE TITLE
Packaging Java libraries

### ISSUE THREAD

**Issue by youngjinpark20** [void-linux/void-packages#9726]
Many java programs seem to ship with pre-built dependencies with them, but voidlinux generally builds most things from source. Should we use these libraries or package our own? and if we were to package them, should we call it like java-* like we do perl and python?

**Comment by Hoshpak** [comment]
I don't think we should package those at all. The Java ecosystem nowadays usually works the way that a piece of software requires a specific version of each of its dependencies which is then downloaded in binary form via maven. Most projects probably wouldn't use libraries provided by us at all and if they tried, it would fail in many cases because we could not provide the exact version that is required.

My take on this currently it to avoid packaging Java software at all and if it is really necessary, accept that it will use vendored or automatically downloaded binary versions of its dependencies.

**Comment by youngjinpark20** [comment]
Alright, thanks, that answers my question :)
