### ISSUE TITLE
man 3 syslog shows klogctl(3) if mandoc.db is present

### ISSUE THREAD

**Issue by loreb** [void-linux/void-packages#9868]
### System

* xuname:  
  Void 4.19.29_1 x86_64-musl GenuineIntel uptodate rFFF
* package:  
  mdocml-1.14.5_1

### Expected behavior
man 3 syslog shows syslog(3)

### Actual behavior
klogctl(3)

### Steps to reproduce the behavior
As above (no idea if it's the same problem as #2575, it shows a different man page).
On both musl/glibc man 3 syslog does the right thing if there's no mandoc.db and shows klogctl(3) if mandoc.db exists; I have zero familiarity with the code, but strace shows that man calls

> access("man3/syslog.3", R_OK)           = 0
> access("man3/klogctl.3", R_OK)          = 0
> access("man3p/closelog.3p", R_OK)       = 0
> access("man3p/syslog.3p", R_OK)         = 0

and then prefers klogctl.3 for some reason ("man -a" shows all).

Atm I couldn't find another manpage with the same problem.

**Comment by loreb** [comment]
More, running (with bash)

`for i in *.3; do echo "$i"; head $i|grep '^.so ma'&&continue; cmp <(man 3  ${i%.3}) <(mandoc $i)||echo>>/tmp/3.broken "$i"; done`

Produces this on my system:

> bzero.3
> memccpy.3
> memchr.3
> memcmp.3
> memcpy.3
> memfrob.3
> memmem.3
> memmove.3
> memset.3
> readdir.3
> stralloc_diffs.3
> strlen.3
> strpbrk.3
> strsep.3
> strspn.3
> strstr.3
> strtok.3
> strxfrm.3
> syslog.3

Other than syslog(3) all the others give a generic page when mandoc.db is present (eg strlen(3) gives string(3)) and the proper page without mandoc.db

---

Btw, I also tried
for sec in 1 2 3 4 5 6 7 8 ; do ( cd man$sec || exit; for i in *.$sec; do echo "$i"; head $i|grep '^.so ma'&&continue; cmp <(man $sec  ${i%.$sec}) <(mandoc $i)||echo>>/tmp/$sec.broken "$i"; done; ); done

... and it failed when bash ran out of file descriptors, wtf?
The file descriptor failure happened in both musl and glibc, but for some reason it seems it happened sooner in musl. Still, one bug at at time :)

**Comment by loreb** [comment]
I tried the following script to save a list of mismatched manpages in /tmp/:
```sh
#! /bin/sh
# Using "<( cmd )" runs out of descriptors after a while...
# XXX "man mkfs.btrfs" segfaults???
set -e
cd /usr/share/man
sections() {
	ls -d man* |
		while read m ; do
			test -d "$m" || continue
			m="${m%/}"
			m="${m#man}"
			echo $m
		done
}

for sec in $(sections) ; do
	(
	cd man$sec
	for i in *.$sec ; do
		echo "$i"
		cat "$i" >/dev/null || continue # some broken links
	       	head $i|grep '^.so ma'&&continue
	       	#cmp <(man $sec  ${i%.$sec}) <(mandoc $i)||echo>>/tmp/$sec.broken "$i"
		MAN=/dev/shm/man.output
		MANDOC=/dev/shm/mandoc.output
	       	man $sec  ${i%.$sec} >"$MAN"
	       	mandoc $i >"$MANDOC"
		cmp "$MAN" "$MANDOC" || echo>>/tmp/$sec.broken "$i"
       	done
       	)
done

```
It produces a few false positives, mostly posix manpages (eg acosl(3p) simply says "Refer to acos()" - which man does automagically) and it uncovered a crash rendering mkfs.btrfs(8) (and ONLY mkfs.btrfs).

Some are funny - eg "man openbox" shows obxprop - but overall it seems that makewhatis is trying to avoid stub manpages ("just refer to xyz(1)") and makes some mistakes along the way.

**Comment by jnbr** [comment]
Can you take a look at this @leahneukirchen ?

**Comment by ischwarze** [comment]
Upstream maintainer of mandoc speaking here.

According to Leah, your file klogctl.3 starts like this:

    .TH KLOGCTL 3  2017-09-15 "Linux" "Linux Programmer's Manual"
    .SH NAME
    syslog, klogctl \- read and/or clear [...]

So, the page itself says that it *is* a manual page for syslog(3): you see the "3" in the .TH line and the "syslog" in the NAME section?  That's why man(1) finds it.  Since you have *two* manual pages matching *all* your search criteria, man(1) cannot know which one you want, and you can't rely on getting a specific one.

Admittedly, the ordering *did* change in the past, see for example the commit
http://mandoc.bsd.lv/cgi-bin/cvsweb/mansearch.c#rev1.79
and that certainly wasn't the first time it was tweaked.
Before that commit, the old behaviour confused other people, see for example
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227408

I doubt it is feasible to make everybody completely happy, given the conflicting expectations.  But there appears to be some low-hanging fruit: you should keep your manual pages consistent about what they claim to describe.  For example, string(3) certainly shouldn't advertise strlen(3) in NAME.

makewhatis(8) does recognize .so links and treats them the same way as soft links (ln -s) and hard links (ln without -s).  Can you be more specific what you mean by "makes some mistakes along the way"?  Keep in mind that i do *not* have a Void system, so i have no easy way to find out what your manual pages contain, under which names they are stored, and how they are linked to each other.

Finally, i suspect the mkfs.btrfs(8) crash may be fixed in:
http://mandoc.bsd.lv/cgi-bin/cvsweb/out.c#rev1.78

**Comment by loreb** [comment]
First of all, mkfs.8 worked in the previous release, sorry that I failed to mention that!

I see what you mean with NAME, but in the case of eg syslog there exists a page called "syslog.3", so I'd expect that "man 3 syslog" would use that.

I can't see the cvsweb pages (http 500), but if you think the current situation is the lesser evil I'll trust your judgement; the reason imho it would be better to default to $page.$section if present is that linux doesn't have a base/ports distinction, so fixing manpages means dealing with many independent projects.

By "mistakes along the way" I was trying to convey my interpretation of the weird behavior - eg "man 3p acosl" showing "acos(3p)" because /usr/share/man/man3p/acosl.3p literally just says "Refer to acos()", and I guessed that you were trying to do that automatically; this is BY FAR the source of most mismatches in the above script in sections 3 and 3p (the POSIX manpages that is).

The weirdest example I found is that "man 1 openbox" shows obxprop.1 instead of openbox.1, but "less $(man -w openbox)" shows that it's the same problem as syslog.3, it advertises itself as "openbox".

idn2.1 is empty (you don't get that in openbsd :), my script caught it because man(1) and mandoc(1) produce different output.

lvm-config.8 (and all the other broken manpages in section 8) is reported as missing from mandoc.db - all it contains is ".so lvmconfig.8"

I'm attaching my /usr/share/man and the output of the script above; if you think that uploading a voidlinux virtual machine might be useful that can be done,
anything else just let me know.

[output.tar.gz](https://github.com/void-linux/void-packages/files/3025675/output.tar.gz)
[usr_share_man.tar.gz](https://github.com/void-linux/void-packages/files/3025676/usr_share_man.tar.gz)

**Comment by loreb** [comment]
Forgot one - "man 3 readdir" shows man3/readdir.3am instead of man3/readdir.3, while "man 3am readdir" shows readdir(2);
the other ambiguous page is fnmatch.3 vs fnmatch.3am ("man 3 fnmatch" and "man 3am fnmatch" always show fnmatch.3)

**Comment by ischwarze** [comment]
> First of all, mkfs.8 worked in the previous release, sorry that I failed to mention that!

Yes, the "trailing span" crash was a regression from 1.14.4 to 1.14.5, caused by this new feature mentioned in NEWS: "tbl(7): better column widths in the presence of horizontal spans".  Sorry about that.

> I see what you mean with NAME, but in the case of eg syslog there exists a page called "syslog.3", so I'd expect that "man 3 syslog" would use that.

Given the sheer amount of cases in Linux that you are showing, i think you have convinced me that restoring man(1) sorting by name flags is the way to go - even though doing so for man(1) only and not for apropos(1) causes slight complication.  So i'm adding this TODO item:

    restore flags for result ordering, but only for man(1), not for apropos(1)
    such that man 3 syslog show syslog.3 not klogctl.3
    and such that man 3p acosl shows acosl.3p not acos.3p
    loc *  exist **  algo *  size *  imp ***

> I can't see the cvsweb pages (http 500),

slowcgi(8) crashed; should be back to normal operation now.

> eg "man 3p acosl" showing "acos(3p)" because /usr/share/man/man3p/acosl.3p literally just says "Refer to acos()", and I guessed that you were trying to do that automatically;

No, that isn't the reason; that happens because acos.3p says acosl in .SH NAME.

> idn2.1 is empty (you don't get that in openbsd :), my script caught it because man(1) and mandoc(1) produce different output.

Yes: makewhatis(8) records an empty file as preformatted, so man(1) simply shows the totally empty file. By contrast, mandoc(1) always formats, so you get the header and the footer.  I don't think there is anything to fix in this respect.

> lvm-config.8 (and all the other broken manpages in section 8) is reported as missing from mandoc.db - all it contains is ".so lvmconfig.8"

Hm, good point, i'm adding this TODO entry:

    dead .so links should be entered into the database to avoid:
    man -M. lvm-config
    man: outdated mandoc.db lacks lvm-config(8) entry, run makewhatis /co/void-man
    loc *  exist **  algo *  size *  imp **

> I'm attaching my /usr/share/man

That's useful for reproducing problems, thank you.  It helped understand several of the above.

> voidlinux virtual machine

No, i don't  use virtualization and wouldn't have any use for it.

**Comment by ischwarze** [comment]
> Forgot one - "man 3 readdir" shows man3/readdir.3am instead of man3/readdir.3, while "man 3am readdir" shows readdir(2);

That's *two* rather than *one*, and both are reports of new bugs that i weren't aware of yet.  I'm adding these two TODO entries:

    man 3am readline
    does not work because man(1) only accepts digit + one letter,
    otherwise explicit -s is currently required
    loc *  exist *  algo *  size *  imp ***

    man 3 readline may show readline(3m)
    because in manpage_compare, "3" and "3am" compare equal
    probably requires putting string version of section into struct manpage
    loc *  exist **  algo *  size *  imp ***

All new TODOs listed here carry a certain risk of regressions in OpenBSD and we are now right before freeze for the 6.5 release, so i won't do these mandoc changes now.  But i will do them after unlock, maybe about two or three weeks from now.

> the other ambiguous page is fnmatch.3 vs fnmatch.3am ("man 3 fnmatch" and "man 3am fnmatch" always show fnmatch.3)

Same as above, i think.

Thanks for the reports.

This is likely to require additional testing once i have implemented those improvements, so please stay tuned if you don't mind.

**Comment by loreb** [comment]
Ok, got it.

And while we are at it, mandoc's speed advantage is especially noticeable (and welcome) on cygwin, thank you!

**Comment by ischwarze** [comment]
> > I see what you mean with NAME, but in the case of eg syslog there exists a page called "syslog.3", so I'd expect that "man 3 syslog" would use that.
> 
> Given the sheer amount of cases in Linux that you are showing, i think you have convinced me that restoring man(1) sorting by name flags is the way to go - even though doing so for man(1) only and not for apropos(1) causes slight complication. So i'm adding this TODO item:
> 
> ```
> restore flags for result ordering, but only for man(1), not for apropos(1)
> such that man 3 syslog show syslog.3 not klogctl.3
> and such that man 3p acosl shows acosl.3p not acos.3p
> loc *  exist **  algo *  size *  imp ***
> ```

I just resolved this part of the ticket with the following commit:
  
[patch.txt](https://github.com/void-linux/void-packages/files/3132731/patch.txt)

The other three parts of this ticket are still open.

**Comment by ischwarze** [comment]
>> Forgot one - "man 3 readdir" shows man3/readdir.3am instead of man3/readdir.3, while "man 3am readdir" shows readdir(2);
 
> That's _two_ rather than _one_, and both are reports of new bugs that i weren't aware of yet. I'm adding these two TODO entries:
> 
> ```
> man 3am readline
> does not work because man(1) only accepts digit + one letter,
> otherwise explicit -s is currently required
> loc *  exist *  algo *  size *  imp ***
> ```

This is now resolved with the following commit:

[patch.txt](https://github.com/void-linux/void-packages/files/3141350/patch.txt)

Two parts of this ticket are still open.

**Comment by ischwarze** [comment]
>> Forgot one - "man 3 readdir" shows man3/readdir.3am instead of man3/readdir.3, while "man 3am readdir" shows readdir(2);
> 
> That's _two_ rather than _one_, and both are reports of new bugs that i weren't aware of yet. I'm adding these two TODO entries:
> 
> ```
> man 3 readline may show readline(3m)
> because in manpage_compare, "3" and "3am" compare equal
> probably requires putting string version of section into struct manpage
> loc *  exist **  algo *  size *  imp ***
> ```

I just fixed this part, too:

[patch.txt](https://github.com/void-linux/void-packages/files/3142736/patch.txt)

Only one part of the ticket remains open now.

**Comment by loreb** [comment]
I've just rerun the script above with a fresh cvs checkout - what a difference!

**Comment by ischwarze** [comment]
>> lvm-config.8 (and all the other broken manpages in section 8) is reported as missing from mandoc.db - all it contains is ".so lvmconfig.8"
> 
> Hm, good point, i'm adding this TODO entry:
> 
> ```
> dead .so links should be entered into the database to avoid:
> man -M. lvm-config
> man: outdated mandoc.db lacks lvm-config(8) entry, run makewhatis /co/void-man
> loc *  exist **  algo *  size *  imp **
> ```

Finally, i fixed that one, too:

[patch.txt](https://github.com/void-linux/void-packages/files/3143171/patch.txt)

Unless i missed something, all issues mentioned in this ticket are now fixed.  Please re-test from CVS.  If everything now works for you, consider closing the ticket.

All fixes will be contained in the next release.  There are no plans for a release date yet.

**Comment by loreb** [comment]
Everything ok (other than empty files, but like you said that's only because man adds headers and mandoc does not, I just forgot to teach my script about it).

Thank you for the hard work!

**Comment by ischwarze** [comment]
Hi Lorenzo,

Lorenzo Beretta wrote on Sat, May 04, 2019 at 01:22:50PM +0000:

> Everything ok

Thank you for checking!

Yours,
  Ingo
